const rawDiseases: { [index: string]: string } = {
    '1': 'Infectious and parasitic diseases',
    '1.1': 'Bacterial infection',
    '1.1.1': 'Tuberculosis',
    '1.1.2': 'Septicemia (except in labor)',
    '1.1.2.1': 'Streptococcal septicemia',
    '1.1.2.2': 'Staphylococcal septicemia',
    '1.1.2.3': 'E. Coli septicemia',
    '1.1.2.4': 'Other gram negative septicemia',
    '1.1.2.5': 'Other specified septicemia',
    '1.1.2.6': 'Unspecified septicemia',
    '1.1.3': 'Sexually transmitted infections (not HIV or hepatitis)',
    '1.1.4': 'Other bacterial infections',
    '1.2': 'Mycoses',
    '1.2.1': 'Candidiasis of the mouth (thrush)',
    '1.2.2': 'Other mycoses',
    '1.3': 'Viral infection',
    '1.3.1': 'HIV infection',
    '1.3.2': 'Hepatitis',
    '1.3.3': 'Other viral infections',
    '1.3.3.1': 'Herpes zoster infection',
    '1.3.3.2': 'Herpes simplex infection',
    '1.3.3.3': 'Other and unspecified viral infection',
    '1.4': 'Other infections; including parasitic',
    '1.5': 'Immunizations and screening for infectious disease',
    '2': 'Neoplasms',
    '2.1': 'Colorectal cancer',
    '2.1.1': 'Cancer of colon',
    '2.1.2': 'Cancer of rectum and anus',
    '2.2': 'Other gastrointestinal cancer',
    '2.2.1': 'Cancer of esophagus',
    '2.2.2': 'Cancer of stomach',
    '2.2.3': 'Cancer of liver and intrahepatic bile duct',
    '2.2.4': 'Cancer of pancreas',
    '2.2.5': 'Cancer of other GI organs; peritoneum',
    '2.3': 'Cancer of bronchus; lung',
    '2.4': 'Cancer of skin',
    '2.4.1': 'Melanomas of skin',
    '2.4.2': 'Other non-epithelial cancer of skin',
    '2.5': 'Cancer of breast',
    '2.6': 'Cancer of uterus and cervix',
    '2.6.1': 'Cancer of uterus',
    '2.6.2': 'Cancer of cervix',
    '2.7': 'Cancer of ovary and other female genital organs',
    '2.7.1': 'Cancer of ovary',
    '2.7.2': 'Cancer of other female genital organs',
    '2.8': 'Cancer of male genital organs',
    '2.8.1': 'Cancer of prostate',
    '2.8.2': 'Cancer of testis',
    '2.8.3': 'Cancer of other male genital organs',
    '2.9': 'Cancer of urinary organs',
    '2.9.1': 'Cancer of bladder',
    '2.9.2': 'Cancer of kidney and renal pelvis',
    '2.9.3': 'Cancer of other urinary organs',
    '2.10': 'Cancer of lymphatic and hematopoietic tissue',
    '2.10.1': 'Hodgkins disease',
    '2.10.2': 'Non-Hodgkins lymphoma',
    '2.10.3': 'Leukemias',
    '2.10.4': 'Multiple myeloma',
    '2.11': 'Cancer; other primary',
    '2.11.1': 'Cancer of head and neck',
    '2.11.2': 'Cancer; other respiratory and intrathoracic',
    '2.11.3': 'Cancer of bone and connective tissue',
    '2.11.4': 'Cancer of brain and nervous system',
    '2.11.5': 'Cancer of thyroid',
    '2.11.6': 'Cancer; other and unspecified primary',
    '2.12': 'Secondary malignancies',
    '2.12.1': 'Secondary malignancy of lymph nodes',
    '2.12.2': 'Secondary malignancy of lung',
    '2.12.3': 'Secondary malignancy of liver',
    '2.12.4': 'Secondary malignancy of brain/spine',
    '2.12.5': 'Secondary malignancy of bone',
    '2.12.6': 'Other secondary malignancy',
    '2.13': 'Malignant neoplasm without specification of site',
    '2.14': 'Neoplasms of unspecified nature or uncertain behavior',
    '2.15': 'Maintenance chemotherapy; radiotherapy',
    '2.15.1': 'Radiotherapy',
    '2.15.2': 'Chemotherapy',
    '2.16': 'Benign neoplasms',
    '2.16.1': 'Benign neoplasm of uterus',
    '2.16.2': 'Other and unspecified benign neoplasm',
    '2.16.2.1': 'Benign neoplasm of ovary',
    '2.16.2.2': 'Benign neoplasm of colon',
    '2.16.2.3': 'Benign neoplasm of the thyroid',
    '2.16.2.4': 'Benign neoplasm of cerebral meninges',
    '2.16.2.5': 'Other and unspecified benign neoplasms',
    '3':
        'Endocrine; nutritional; and metabolic diseases and immunity disorders',
    '3.1': 'Thyroid disorders',
    '3.1.1': 'Thyrotoxicosis with or without goiter',
    '3.1.2': 'Other thyroid disorders',
    '3.2': 'Diabetes mellitus without complication',
    '3.3': 'Diabetes mellitus with complications',
    '3.3.1': 'Diabetes with ketoacidosis or uncontrolled diabetes',
    '3.3.2': 'Diabetes with renal manifestations',
    '3.3.3': 'Diabetes with ophthalmic manifestations',
    '3.3.4': 'Diabetes with neurological manifestations',
    '3.3.5': 'Diabetes with circulatory manifestations',
    '3.3.6': 'Diabetes with unspecified complications',
    '3.3.7': 'Diabetes with other manifestations',
    '3.4': 'Other endocrine disorders',
    '3.5': 'Nutritional deficiencies',
    '3.5.1': 'Unspecified protein-calorie malnutrition',
    '3.5.2': 'Other malnutrition',
    '3.6': 'Disorders of lipid metabolism',
    '3.7': 'Gout and other crystal arthropathies',
    '3.8': 'Fluid and electrolyte disorders',
    '3.8.1': 'Hyposmolality',
    '3.8.2': 'Hypovolemia',
    '3.8.3': 'Hyperpotassemia',
    '3.8.4': 'Hypopotassemia',
    '3.8.5': 'Other fluid and electrolyte disorders',
    '3.9': 'Cystic fibrosis',
    '3.10': 'Immunity disorders',
    '3.11': 'Other nutritional; endocrine; and metabolic disorders',
    '3.11.1': 'Disorders of mineral metabolism',
    '3.11.2': 'Obesity',
    '3.11.3':
        'Other and unspecified metabolic; nutritional; and endocrine disorders',
    '4': 'Diseases of the blood and blood-forming organs',
    '4.1': 'Anemia',
    '4.1.1': 'Acute posthemorrhagic anemia',
    '4.1.2': 'Sickle cell anemia',
    '4.1.3': 'Deficiency and other anemia',
    '4.1.3.1': 'Iron deficiency anemia',
    '4.1.3.2': 'Other deficiency anemia',
    '4.1.3.3': 'Aplastic anemia',
    '4.1.3.4': 'Chronic blood loss anemia',
    '4.1.3.5': 'Acquired hemolytic anemia',
    '4.1.3.6': 'Other specified anemia',
    '4.1.3.7': 'Anemia; unspecified',
    '4.2': 'Coagulation and hemorrhagic disorders',
    '4.2.1': 'Coagulation defects',
    '4.2.2': 'Thrombocytopenia',
    '4.2.3': 'Other coagulation and hemorrhagic disorders',
    '4.3': 'Diseases of white blood cells',
    '4.4': 'Other hematologic conditions',
    '5': 'Mental illness',
    '5.1': 'Adjustment disorders',
    '5.2': 'Anxiety disorders',
    '5.3': 'Attention deficit, conduct, and disruptive behavior disorders',
    '5.3.1': 'Conduct disorder',
    '5.3.2': 'Oppositional defiant disorder',
    '5.3.3':
        'Attention deficit disorder and Attention deficit hyperactivity disorder',
    '5.4': 'Delirium, dementia, and amnestic and other cognitive disorders',
    '5.5': 'Developmental disorders',
    '5.5.1': 'Communication disorders',
    '5.5.2': 'Developmental disabilities',
    '5.5.3': 'Intellectual disabilities',
    '5.5.4': 'Learning disorders',
    '5.5.5': 'Motor skill disorders',
    '5.6': 'Disorders usually diagnosed in infancy, childhood, or adolescence',
    '5.6.1': 'Elimination disorders',
    '5.6.2': 'Other disorders of infancy  childhood  or adolescence',
    '5.6.3': 'Pervasive developmental disorders',
    '5.6.4': 'Tic disorders',
    '5.7': 'Impulse control disorders, not elsewhere classified',
    '5.8': 'Mood disorders',
    '5.8.1': 'Bipolar disorders',
    '5.8.2': 'Depressive disorders',
    '5.9': 'Personality disorders',
    '5.10': 'Schizophrenia and other psychotic disorders',
    '5.11': 'Alcohol-related disorders',
    '5.12': 'Substance-related disorders',
    '5.13': 'Suicide and intentional self-inflicted injury',
    '5.14': 'Screening and history of mental health and substance abuse codes',
    '5.14.1': 'Codes related to mental health disorders',
    '5.14.2': 'Codes related to substance-related disorders',
    '5.15': 'Miscellaneous mental health disorders',
    '5.15.1': 'Dissociative disorders',
    '5.15.2': 'Eating disorders',
    '5.15.3': 'Factitious disorders',
    '5.15.4': 'Psychogenic disorders',
    '5.15.5': 'Sexual and gender identity disorders',
    '5.15.6': 'Sleep disorders',
    '5.15.7': 'Somatoform disorders',
    '5.15.8':
        'Mental disorders due to general medical conditions not elsewhere classified',
    '5.15.9': 'Other miscellaneous mental conditions',
    '6': 'Diseases of the nervous system and sense organs',
    '6.1': 'Central nervous system infection',
    '6.1.1': 'Meningitis (except that caused by TB or STD)',
    '6.1.2': 'Encephalitis (except that caused by TB or STD)',
    '6.1.3': 'Other CNS infection and poliomyelitis',
    '6.2': 'Hereditary and degenerative nervous system conditions',
    '6.2.1': 'Parkinsons disease',
    '6.2.2': 'Multiple sclerosis',
    '6.2.3': 'Other hereditary and degenerative nervous system conditions',
    '6.2.3.1': 'Disorders of the autonomic nervous system',
    '6.2.3.2':
        'Other and unspecified hereditary and degenerative nervous conditions',
    '6.3': 'Paralysis',
    '6.3.1': 'Hemiplegia',
    '6.3.2': 'Other paralysis',
    '6.4': 'Epilepsy; convulsions',
    '6.4.1': 'Epilepsy',
    '6.4.2': 'Convulsions',
    '6.5': 'Headache; including migraine',
    '6.5.1': 'Migraine',
    '6.5.2': 'Other headache',
    '6.6': 'Coma; stupor; and brain damage',
    '6.7': 'Eye disorders',
    '6.7.1': 'Cataract',
    '6.7.2':
        'Retinal detachments; defects; vascular occlusion; and retinopathy',
    '6.7.2.1': 'Retinal detachment with defect',
    '6.7.2.2': 'Other retinal detachment or defect',
    '6.7.2.3': 'Other retinal disorders',
    '6.7.3': 'Glaucoma',
    '6.7.4': 'Blindness and vision defects',
    '6.7.5': 'Inflammation; infection of eye (except that caused by TB or STD)',
    '6.7.6': 'Other eye disorders',
    '6.8': 'Ear conditions',
    '6.8.1': 'Otitis media and related conditions',
    '6.8.1.1': 'Suppurative and unspecified otitis media',
    '6.8.1.2': 'Other otitis media and related conditions',
    '6.8.2': 'Conditions associated with dizziness or vertigo',
    '6.8.3': 'Other ear and sense organ disorders',
    '6.9': 'Other nervous system disorders',
    '6.9.1': 'Disorders of the peripheral nervous system',
    '6.9.2': 'Other central nervous system disorders',
    '6.9.3': 'Other nervous system symptoms and disorders',
    '7': 'Diseases of the circulatory system',
    '7.1': 'Hypertension',
    '7.1.1': 'Essential hypertension',
    '7.1.2': 'Hypertension with complications and secondary hypertension',
    '7.1.2.1': 'Hypertensive heart and/or renal disease',
    '7.1.2.2': 'Other hypertensive complications',
    '7.2': 'Diseases of the heart',
    '7.2.1': 'Heart valve disorders',
    '7.2.1.1': 'Chronic rheumatic disease of the heart valves',
    '7.2.1.2': 'Nonrheumatic mitral valve disorders',
    '7.2.1.3': 'Nonrheumatic aortic valve disorders',
    '7.2.1.4': 'Other heart valve disorders',
    '7.2.2':
        'Peri-; endo-; and myocarditis; cardiomyopathy (except that caused by TB or STD)',
    '7.2.2.1': 'Cardiomyopathy',
    '7.2.2.2': 'Other peri-; endo-; and myocarditis',
    '7.2.3': 'Acute myocardial infarction',
    '7.2.4': 'Coronary atherosclerosis and other heart disease',
    '7.2.4.1': 'Angina pectoris',
    '7.2.4.2': 'Unstable angina (intermediate coronary syndrome)',
    '7.2.4.3': 'Other acute and subacute forms of ischemic heart disease',
    '7.2.4.4': 'Coronary atherosclerosis',
    '7.2.4.5': 'Other forms of chronic heart disease',
    '7.2.5': 'Nonspecific chest pain',
    '7.2.6': 'Pulmonary heart disease',
    '7.2.7': 'Other and ill-defined heart disease',
    '7.2.8': 'Conduction disorders',
    '7.2.8.1': 'Atrioventricular block',
    '7.2.8.2': 'Bundle branch block',
    '7.2.8.3': 'Anomalous atrioventricular excitation',
    '7.2.8.4': 'Other conduction disorders',
    '7.2.9': 'Cardiac dysrhythmias',
    '7.2.9.1': 'Paroxysmal supraventricular tachycardia',
    '7.2.9.2': 'Paroxysmal ventricular tachycardia',
    '7.2.9.3': 'Atrial fibrillation',
    '7.2.9.4': 'Atrial flutter',
    '7.2.9.5': 'Premature beats',
    '7.2.9.6': 'Sinoatrial node dysfunction',
    '7.2.9.7': 'Other cardiac dysrhythmias',
    '7.2.10': 'Cardiac arrest and ventricular fibrillation',
    '7.2.11': 'Congestive heart failure; nonhypertensive',
    '7.2.11.1': 'Congestive heart failure',
    '7.2.11.2': 'Heart failure',
    '7.3': 'Cerebrovascular disease',
    '7.3.1': 'Acute cerebrovascular disease',
    '7.3.1.1': 'Intracranial hemorrhage',
    '7.3.1.2': 'Occlusion of cerebral arteries',
    '7.3.1.3': 'Acute but ill-defined cerebrovascular accident',
    '7.3.2': 'Occlusion or stenosis of precerebral arteries',
    '7.3.3': 'Other and ill-defined cerebrovascular disease',
    '7.3.4': 'Transient cerebral ischemia',
    '7.3.5': 'Late effects of cerebrovascular disease',
    '7.4': 'Diseases of arteries; arterioles; and capillaries',
    '7.4.1': 'Peripheral and visceral atherosclerosis',
    '7.4.1.1': 'Atherosclerosis of arteries of extremities',
    '7.4.1.2': 'Peripheral vascular disease unspecified',
    '7.4.1.3': 'Other peripheral and visceral atherosclerosis',
    '7.4.2': 'Aortic; peripheral; and visceral artery aneurysms',
    '7.4.2.1': 'Abdominal aortic aneurysm; without rupture',
    '7.4.2.2': 'Other aneurysm',
    '7.4.3': 'Aortic and peripheral arterial embolism or thrombosis',
    '7.4.3.1': 'Arterial embolism and thrombosis of lower extremity artery',
    '7.4.3.2': 'Other arterial embolism and thrombosis',
    '7.4.4': 'Other circulatory disease',
    '7.4.4.1': 'Hypotension',
    '7.4.4.2': 'Other and unspecified circulatory disease',
    '7.5': 'Diseases of veins and lymphatics',
    '7.5.1': 'Phlebitis; thrombophlebitis and thromboembolism',
    '7.5.1.1': 'Phlebitis and thrombophlebitis',
    '7.5.1.2': 'Other venous embolism and thrombosis',
    '7.5.2': 'Varicose veins of lower extremity',
    '7.5.3': 'Hemorrhoids',
    '7.5.4': 'Other diseases of veins and lymphatics',
    '8': 'Diseases of the respiratory system',
    '8.1': 'Respiratory infections',
    '8.1.1': 'Pneumonia (except that caused by TB or STD)',
    '8.1.1.1': 'Pneumococcal pneumonia',
    '8.1.1.2': 'Other bacterial pneumonia',
    '8.1.1.3': 'Pneumonia; organism unspecified',
    '8.1.1.4': 'Other pneumonia',
    '8.1.2': 'Influenza',
    '8.1.3': 'Acute and chronic tonsillitis',
    '8.1.4': 'Acute bronchitis',
    '8.1.5': 'Other upper respiratory infections',
    '8.1.5.1':
        'Acute upper respiratory infections of multiple or unspecified sites',
    '8.1.5.2': 'Chronic sinusitis',
    '8.1.5.3': 'Croup',
    '8.1.5.4': 'Other and unspecified upper respiratory infections',
    '8.2': 'Chronic obstructive pulmonary disease and bronchiectasis',
    '8.2.1': 'Emphysema',
    '8.2.2': 'Chronic airway obstruction; not otherwise specified',
    '8.2.3': 'Obstructive chronic bronchitis',
    '8.2.4': 'Other chronic pulmonary disease',
    '8.3': 'Asthma',
    '8.3.1.1':
        'Chronic obstructive asthma without status asthmaticus or exacerbation',
    '8.3.1.2': 'Chronic obstructive asthma with status asthmaticus',
    '8.3.1.3': 'Chronic obstructive asthma with acute exacerbation',
    '8.3.2.1': 'Other asthma without status asthmaticus or exacerbation',
    '8.3.2.2': 'Other asthma with status asthmaticus',
    '8.3.2.3': 'Other asthma with acute exacerbation',
    '8.4': 'Aspiration pneumonitis; food/vomitus',
    '8.5': 'Pleurisy; pneumothorax; pulmonary collapse',
    '8.5.1': 'Pleurisy; pleural effusion',
    '8.5.2': 'Pulmonary collapse; interstitial and compensatory emphysema',
    '8.5.3': 'Empyema and pneumothorax',
    '8.6': 'Respiratory failure; insufficiency; arrest (adult)',
    '8.6.1': 'Respiratory failure',
    '8.6.2': 'Other respiratory insufficiency',
    '8.7': 'Lung disease due to external agents',
    '8.8': 'Other lower respiratory disease',
    '8.8.1': 'Postinflammatory pulmonary fibrosis',
    '8.8.2': 'Painful respiration',
    '8.8.3': 'Other and unspecified lower respiratory disease',
    '8.9': 'Other upper respiratory disease',
    '9': 'Diseases of the digestive system',
    '9.1': 'Intestinal infection',
    '9.2': 'Disorders of teeth and jaw',
    '9.3': 'Diseases of mouth; excluding dental',
    '9.4': 'Upper gastrointestinal disorders',
    '9.4.1': 'Esophageal disorders',
    '9.4.1.1': 'Esophagitis',
    '9.4.1.2': 'Other esophageal disorders',
    '9.4.2': 'Gastroduodenal ulcer (except hemorrhage)',
    '9.4.2.1': 'Gastric ulcer',
    '9.4.2.2': 'Duodenal ulcer',
    '9.4.2.3': 'Peptic ulcer; site unspecified',
    '9.4.2.4': 'Gastrojejunal ulcer',
    '9.4.3': 'Gastritis and duodenitis',
    '9.4.3.1': 'Acute gastritis',
    '9.4.3.2': 'Other specified gastritis',
    '9.4.3.3': 'Unspecified gastritis and gastroduodenitis',
    '9.4.3.4': 'Duodenitis',
    '9.4.4': 'Other disorders of stomach and duodenum',
    '9.5': 'Abdominal hernia',
    '9.5.1.1': 'Inguinal hernia with obstruction or gangrene',
    '9.5.1.2': 'Inguinal hernia without obstruction or gangrene',
    '9.5.2': 'Diaphragmatic hernia',
    '9.5.3.1': 'Femoral hernia with obstruction/gangrene',
    '9.5.3.2': 'Femoral hernia without obstruction/gangrene',
    '9.5.3.3': 'Umbilical hernia with obstruction/gangrene',
    '9.5.3.4': 'Umbilical hernia without obstruction/gangrene',
    '9.5.3.5': 'Ventral hernia with obstruction/gangrene',
    '9.5.3.6': 'Ventral hernia without obstruction/gangrene',
    '9.5.3.7': 'Incisional hernia with obstruction/gangrene',
    '9.5.3.8': 'Incisional hernia without obstruction/gangrene',
    '9.5.3.9': 'Other and unspecified hernia',
    '9.6': 'Lower gastrointestinal disorders',
    '9.6.1': 'Appendicitis and other appendiceal conditions',
    '9.6.1.1': 'Acute appendicitis with abscess or peritonitis',
    '9.6.1.2': 'Acute appendicitis without abscess or peritonitis',
    '9.6.1.3': 'Acute appendicitis; not otherwise specified',
    '9.6.1.4': 'Other appendiceal conditions',
    '9.6.2': 'Regional enteritis and ulcerative colitis',
    '9.6.3': 'Intestinal obstruction without hernia',
    '9.6.3.1': 'Paralytic ileus',
    '9.6.3.2': 'Impaction of intestine',
    '9.6.3.3': 'Peritoneal or intestinal adhesions',
    '9.6.3.4': 'Other intestinal obstruction',
    '9.6.4': 'Diverticulosis and diverticulitis',
    '9.6.4.1': 'Diverticulosis',
    '9.6.4.2': 'Diverticulitis',
    '9.6.5': 'Anal and rectal conditions',
    '9.6.6': 'Peritonitis and intestinal abscess',
    '9.7': 'Biliary tract disease',
    '9.7.1': 'Cholelithiasis with acute cholecystitis',
    '9.7.2': 'Cholelithiasis with other cholecystitis',
    '9.7.3': 'Cholelithiasis without mention of cholecystitis',
    '9.7.4': 'Calculus of bile duct',
    '9.7.5': 'Cholecystitis without cholelithiasis',
    '9.7.6': 'Other biliary tract disease',
    '9.8': 'Liver disease',
    '9.8.1': 'Liver disease; alcohol-related',
    '9.8.2': 'Other liver diseases',
    '9.8.2.1': 'Cirrhosis of liver without mention of alcohol',
    '9.8.2.2': 'Liver abscess and sequelae of chronic liver disease',
    '9.8.2.3': 'Ascites',
    '9.8.2.4': 'Other and unspecified liver disorders',
    '9.9': 'Pancreatic disorders (not diabetes)',
    '9.9.1': 'Acute pancreatitis',
    '9.9.2': 'Chronic pancreatitis',
    '9.9.3': 'Other pancreatic disorders',
    '9.10': 'Gastrointestinal hemorrhage',
    '9.10.1': 'Hemorrhage from gastrointestinal ulcer',
    '9.10.2': 'Melena',
    '9.10.3': 'Gastroesophageal laceration syndrome',
    '9.10.4': 'Other esophageal bleeding',
    '9.10.5': 'Hemorrhage of rectum and anus',
    '9.10.6': 'Hematemesis',
    '9.10.7': 'Hemorrhage of gastrointestinal tract',
    '9.11': 'Noninfectious gastroenteritis',
    '9.12': 'Other gastrointestinal disorders',
    '9.12.1': 'Constipation',
    '9.12.2': 'Dysphagia',
    '9.12.3': 'Other and unspecified gastrointestinal disorders',
    '10': 'Diseases of the genitourinary system',
    '10.1': 'Diseases of the urinary system',
    '10.1.1': 'Nephritis; nephrosis; renal sclerosis',
    '10.1.2': 'Acute and unspecified renal failure',
    '10.1.2.1': 'Acute renal failure',
    '10.1.2.2': 'Unspecified renal failure',
    '10.1.3': 'Chronic kidney disease',
    '10.1.4': 'Urinary tract infections',
    '10.1.4.1': 'Infections of kidney',
    '10.1.4.2': 'Cystitis and urethritis',
    '10.1.4.3': 'Urinary tract infection; site not specified',
    '10.1.5': 'Calculus of urinary tract',
    '10.1.5.1': 'Calculus of kidney',
    '10.1.5.2': 'Calculus of ureter',
    '10.1.5.3': 'Other and unspecified urinary calculus',
    '10.1.6': 'Other diseases of kidney and ureters',
    '10.1.6.1': 'Hydronephrosis',
    '10.1.6.2': 'Other and unspecified diseases of kidney and ureters',
    '10.1.7': 'Other diseases of bladder and urethra',
    '10.1.7.1': 'Bladder neck obstruction',
    '10.1.7.2': 'Other and unspecified diseases of bladder and urethra',
    '10.1.8': 'Genitourinary symptoms and ill-defined conditions',
    '10.1.8.1': 'Hematuria',
    '10.1.8.2': 'Retention of urine',
    '10.1.8.3': 'Other and unspecified genitourinary symptoms',
    '10.2': 'Diseases of male genital organs',
    '10.2.1': 'Hyperplasia of prostate',
    '10.2.2': 'Inflammatory conditions of male genital organs',
    '10.2.3': 'Other male genital disorders',
    '10.3': 'Diseases of female genital organs',
    '10.3.1': 'Nonmalignant breast conditions',
    '10.3.2': 'Inflammatory diseases of female pelvic organs',
    '10.3.2.1': 'Pelvic peritoneal adhesions',
    '10.3.2.2': 'Cervicitis and endocervicitis',
    '10.3.2.3': 'Pelvic inflammatory disease (PID)',
    '10.3.2.4': 'Other inflammatory diseases of female pelvic organs',
    '10.3.3': 'Endometriosis',
    '10.3.4': 'Prolapse of female genital organs',
    '10.3.5': 'Menstrual disorders',
    '10.3.6': 'Ovarian cyst',
    '10.3.7': 'Menopausal disorders',
    '10.3.8': 'Female infertility',
    '10.3.9': 'Other female genital disorders',
    '10.3.9.1': 'Female genital pain and other symptoms',
    '10.3.9.2': 'Other and unspecified female genital disorders',
    '11': 'Complications of pregnancy; childbirth; and the puerperium',
    '11.1': 'Contraceptive and procreative management',
    '11.1.1': 'Sterilization',
    '11.1.2': 'Other contraceptive and procreation management',
    '11.2': 'Abortion-related disorders',
    '11.2.1': 'Spontaneous abortion',
    '11.2.2': 'Induced abortion',
    '11.2.3': 'Postabortion complications',
    '11.3': 'Complications mainly related to pregnancy',
    '11.3.1': 'Ectopic pregnancy',
    '11.3.2': 'Hemorrhage during pregnancy; abruptio placenta; placenta previa',
    '11.3.2.1': 'Placenta previa',
    '11.3.2.2': 'Abruptio placenta',
    '11.3.2.3':
        'Other hemorrhage during pregnancy; childbirth and the puerperium',
    '11.3.3':
        'Hypertension complicating pregnancy; childbirth and the puerperium',
    '11.3.3.1': 'Preeclampsia and eclampsia',
    '11.3.3.2': 'Other hypertension in pregnancy',
    '11.3.4': 'Early or threatened labor',
    '11.3.4.1': 'Threatened premature labor',
    '11.3.4.2': 'Early onset of delivery',
    '11.3.4.3': 'Other early or threatened labor',
    '11.3.5': 'Prolonged pregnancy',
    '11.3.6':
        'Diabetes or abnormal glucose tolerance complicating pregnancy; childbirth; or the pue -',
    '11.3.7': 'Other complications of pregnancy',
    '11.3.7.1': 'Infections of genitourinary tract during pregnancy',
    '11.3.7.2': 'Anemia during pregnancy',
    '11.3.7.4': 'Missed abortion',
    '11.3.7.5': 'Hyperemesis gravidarum',
    '11.3.7.6':
        'Infectious and parasitic complications in mother affecting pregnancy',
    '11.3.7.7': 'Other and unspecified complications of pregnancy',
    '11.4': 'Indications for care in pregnancy; labor; and delivery',
    '11.4.1': 'Malposition; malpresentation',
    '11.4.1.1': 'Breech presentation',
    '11.4.1.2': 'Other malposition; malpresentation',
    '11.4.2': 'Fetopelvic disproportion; obstruction',
    '11.4.2.1': 'Fetopelvic disproportion',
    '11.4.2.2': 'Other disproportion or obstruction',
    '11.4.3': 'Previous cesarean section',
    '11.4.4': 'Fetal distress and abnormal forces of labor',
    '11.4.4.1': 'Fetal distress',
    '11.4.4.2': 'Uterine inertia',
    '11.4.4.3': 'Precipitate labor',
    '11.4.4.4': 'Other abnormal forces of labor',
    '11.4.5': 'Polyhydramnios and other problems of amniotic cavity',
    '11.4.5.1': 'Premature rupture of membranes',
    '11.4.5.2': 'Infection of amniotic cavity',
    '11.4.5.3': 'Other problems of amniotic cavity',
    '11.5': 'Complications during labor',
    '11.5.1': 'Umbilical cord complication',
    '11.5.1.1': 'Cord around neck with compression',
    '11.5.1.2':
        'Other and unspecified cord entanglement with or without compression',
    '11.5.1.3': 'Other umbilical cord complications',
    '11.5.2': 'Trauma to perineum and vulva',
    '11.5.2.1': 'First degree perineal laceration',
    '11.5.2.2': 'Second degree perineal laceration',
    '11.5.2.3': 'Third degree perineal laceration',
    '11.5.2.4': 'Fourth degree perineal laceration',
    '11.5.2.5': 'Other perineal laceration and trauma',
    '11.5.3': 'Forceps delivery',
    '11.6':
        'Other complications of birth; puerperium affecting management of mother',
    '11.6.1': 'Postpartum hemorrhage',
    '11.6.2': 'Complications of the puerperium',
    '11.6.3': 'Cervical incompetence',
    '11.6.4': 'Rhesus isoimmunization',
    '11.6.5': 'Intrauterine death',
    '11.6.6': 'Failed induction',
    '11.6.7': 'Other obstetrical trauma',
    '11.6.8':
        'Other and unspecified complications of birth; puerperium affecting management of moth -',
    '11.7': 'Normal pregnancy and/or delivery',
    '11.7.1': 'Normal delivery',
    '11.7.2': 'Multiple gestation',
    '11.7.3': 'Outcome of delivery (V codes)',
    '12': 'Diseases of the skin and subcutaneous tissue',
    '12.1': 'Skin and subcutaneous tissue infections',
    '12.1.1.1': 'Cellulitis and abscess of fingers and toes',
    '12.1.1.2': 'Cellulitis and abscess of face',
    '12.1.1.3': 'Cellulitis and abscess of arm',
    '12.1.1.4': 'Cellulitis and abscess of hand',
    '12.1.1.5': 'Cellulitis and abscess of leg',
    '12.1.1.6': 'Cellulitis and abscess of foot',
    '12.1.1.7': 'Other cellulitis and abscess',
    '12.1.2': 'Other skin and subcutaneous infections',
    '12.2': 'Other inflammatory condition of skin',
    '12.3': 'Chronic ulcer of skin',
    '12.3.1': 'Decubitus ulcer',
    '12.3.2': 'Chronic ulcer of leg or foot',
    '12.3.3': 'Other chronic skin ulcer',
    '12.4': 'Other skin disorders',
    '13': 'Diseases of the musculoskeletal system and connective tissue',
    '13.1':
        'Infective arthritis and osteomyelitis (except that caused by TB or STD)',
    '13.2': 'Non-traumatic joint disorders',
    '13.2.1': 'Rheumatoid arthritis and related disease',
    '13.2.2': 'Osteoarthritis',
    '13.2.2.1': 'Osteoarthritis; localized',
    '13.2.2.2': 'Osteoarthritis; generalized and unspecified',
    '13.2.3': 'Other non-traumatic joint disorders',
    '13.3': 'Spondylosis; intervertebral disc disorders; other back problems',
    '13.3.1': 'Spondylosis and allied disorders',
    '13.3.2': 'Intervertebral disc disorders',
    '13.3.3.1': 'Cervical radiculitis',
    '13.3.3.2': 'Spinal stenosis; lumbar region',
    '13.3.3.3': 'Lumbago',
    '13.3.3.4': 'Sciatica',
    '13.3.3.5': 'Thoracic or lumbosacral neuritis or radiculitis; unspecified',
    '13.3.3.6': 'Backache; unspecified',
    '13.3.3.7': 'Other back pain and disorders',
    '13.4': 'Osteoporosis',
    '13.5': 'Pathological fracture',
    '13.6': 'Acquired deformities',
    '13.6.1': 'Acquired foot deformities',
    '13.6.2': 'Other acquired deformities',
    '13.7': 'Systemic lupus erythematosus and connective tissue disorders',
    '13.8': 'Other connective tissue disease',
    '13.9': 'Other bone disease and musculoskeletal deformities',
    '14': 'Congenital anomalies',
    '14.1': 'Cardiac and circulatory congenital anomalies',
    '14.1.1': 'Transposition of great vessels',
    '14.1.2': 'Tetralogy of Fallot',
    '14.1.3': 'Ventricular septal defect',
    '14.1.4': 'Atrial septal defect',
    '14.1.5': 'Endocardial cushion defects',
    '14.1.6': 'Pulmonary valve atresia and stenosis',
    '14.1.7': 'Aortic valve stenosis',
    '14.1.8': 'Patent ductus arteriosus',
    '14.1.9': 'Coarctation of aorta',
    '14.1.10': 'Pulmonary artery anomalies',
    '14.1.11': 'Cerebrovascular anomalies',
    '14.1.12': 'Double outlet right ventricle',
    '14.1.13': 'Common ventricle',
    '14.1.14': 'Congenital insufficiency of aortic valve',
    '14.1.15': 'Hypoplastic left heart syndrome',
    '14.1.16': 'Gastrointestinal vessel congenital anomaly',
    '14.1.17': 'Persistent fetal circulation',
    '14.1.18': 'Other anomalies of bulbus cordis and cardiac septal closure',
    '14.1.19': 'Other heart valve congenital anomalies',
    '14.1.20': 'Other congenital anomalies of the heart',
    '14.1.21': 'Other congenital anomalies of aorta',
    '14.1.22': 'Other circulatory congenital anomalies',
    '14.2': 'Digestive congenital anomalies',
    '14.2.1': 'Esophageal atresia/tracheoesophageal fistula',
    '14.2.2': 'Pyloric stenosis',
    '14.2.3': 'Rectal and large intestine atresia/stenosis',
    '14.2.4': 'Hirshsprungs disease',
    '14.2.5': "Meckel's diverticulum",
    '14.2.6': 'Atresia and stenosis of small intestine',
    '14.2.7': 'Anomalies of intestinal fixation',
    '14.2.8': 'Other upper gastrointestinal congenital anomalies',
    '14.2.9': 'Other lower gastrointestinal congenital anomalies',
    '14.3': 'Genitourinary congenital anomalies',
    '14.3.1': 'Undescended testicle',
    '14.3.2': 'Hypospadias and epispadias',
    '14.3.3': 'Obstructive genitourinary defect',
    '14.3.4': 'Polycystic kidney',
    '14.3.5': 'Other cystic kidney disease',
    '14.3.6': 'Embyronic cyst of fallopian tubes and broad ligaments',
    '14.3.7': 'Other congenital anomalies of genitalia',
    '14.3.8': 'Other congenital anomalies of urinary system',
    '14.4': 'Nervous system congenital anomalies',
    '14.4.1': 'Spina bifida',
    '14.4.2': 'Congenital hydrocephalus',
    '14.4.3': 'Other spinal cord congenital anomalies',
    '14.4.4': 'Microcephalus',
    '14.4.5': 'Other nervous system congenital anomalies',
    '14.5': 'Other congenital anomalies',
    '14.5.1': 'Cleft palate without cleft lip',
    '14.5.2': 'Cleft lip with or without cleft palate',
    '14.5.3': 'Congenital anomalies of the eye',
    '14.5.4': 'Microtia (incomplete development of external ear)',
    '14.5.5': 'Branchial cleft cyst or fistula',
    '14.5.6': 'Other face and neck congenital anomalies',
    '14.5.7': 'Congenital anomalies of larynx trachea and bronchus',
    '14.5.8': 'Other respiratory congenital anomalies',
    '14.5.9': 'Foot deformities',
    '14.5.10': 'Congenital hip dislocation',
    '14.5.11':
        'Polydactyly (extra digits) and syndactyly (webbing between digits)',
    '14.5.12': 'Congenital absence of lower limb',
    '14.5.13': 'Congenital hip deformity',
    '14.5.14': 'Other congenital anomalies of limbs',
    '14.5.15': 'Congenital anomalies of skull and facial bones',
    '14.5.16': 'Lumbosacral spondylolysis',
    '14.5.17': 'Spondylolisthesis',
    '14.5.18': 'Other spinal congenital anomalies',
    '14.5.19': 'Osteogenesis imperfecta',
    '14.5.20': 'Congenital anomalies of the diaphragm',
    '14.5.21': 'Congenital anomalies of abdominal wall',
    '14.5.22': 'Congenital pigmentary anomalies of skin',
    '14.5.23': 'Other congenital anomalies of integument',
    '14.5.24': 'Pectus excavatum',
    '14.5.25': "Down's Syndrome",
    '14.5.26': 'All other congenital anomalies',
    '15': 'Certain conditions originating in the perinatal period',
    '15.1': 'Liveborn',
    '15.2': 'Short gestation; low birth weight; and fetal growth retardation',
    '15.3': 'Intrauterine hypoxia and birth asphyxia',
    '15.4': 'Respiratory distress syndrome',
    '15.5': 'Hemolytic jaundice and perinatal jaundice',
    '15.6': 'Birth trauma',
    '15.7': 'Other perinatal conditions',
    '15.7.1':
        'Respiratory conditions of fetus and newborn; other than respiratory distress',
    '15.7.2': 'Infections specific to the perinatal period',
    '15.7.3': 'Endocrine and metabolic disturbances of fetus and newborn',
    '15.7.4': 'Other and unspecified perinatal conditions',
    '16': 'Injury and poisoning',
    '16.1': 'Joint disorders and dislocations; trauma-related',
    '16.2': 'Fractures',
    '16.2.1': 'Fracture of neck of femur (hip)',
    '16.2.2': 'Skull and face fractures',
    '16.2.3': 'Fracture of upper limb',
    '16.2.3.1': 'Fracture of humerus',
    '16.2.3.2': 'Fracture of radius and ulna',
    '16.2.3.3': 'Other fracture of upper limb',
    '16.2.4': 'Fracture of lower limb',
    '16.2.4.1': 'Fracture of tibia and fibula',
    '16.2.4.2': 'Fracture of ankle',
    '16.2.4.3': 'Other fracture of lower limb',
    '16.2.5': 'Other fractures',
    '16.2.5.1':
        'Fracture of vertebral column without mention of spinal cord injury',
    '16.2.5.2': 'Fracture of ribs; closed',
    '16.2.5.3': 'Fracture of pelvis',
    '16.2.5.4': 'Other and unspecified fracture',
    '16.3': 'Spinal cord injury',
    '16.4': 'Intracranial injury',
    '16.4.1': 'Concussion',
    '16.4.2': 'Other intracranial injury',
    '16.5': 'Crushing injury or internal injury',
    '16.6': 'Open wounds',
    '16.6.1': 'Open wounds of head; neck; and trunk',
    '16.6.2': 'Open wounds of extremities',
    '16.7': 'Sprains and strains',
    '16.8': 'Superficial injury; contusion',
    '16.9': 'Burns',
    '16.10': 'Complications',
    '16.10.1': 'Complication of device; implant or graft',
    '16.10.1.1': 'Malfunction of device; implant; and graft',
    '16.10.1.2':
        'Infection and inflammation--internal prosthetic device; implant; and graft',
    '16.10.1.3':
        'Other complications of internal prosthetic device; implant; and graft',
    '16.10.1.4': 'Complications of transplants and reattached limbs',
    '16.10.2': 'Complications of surgical procedures or medical care',
    '16.10.2.1': 'Cardiac complications',
    '16.10.2.2': 'Respiratory complications',
    '16.10.2.3': 'Gastrointestinal complications',
    '16.10.2.4': 'Urinary complications',
    '16.10.2.5': 'Hemorrhage or hematoma complicating a procedure',
    '16.10.2.6': 'Postoperative infection',
    '16.10.2.7': 'Other complications of surgical and medical procedures',
    '16.11': 'Poisoning',
    '16.11.1': 'Poisoning by psychotropic agents',
    '16.11.2': 'Poisoning by other medications and drugs',
    '16.11.3': 'Poisoning by nonmedicinal substances',
    '16.12': 'Other injuries and conditions due to external causes',
    '17':
        'Symptoms; signs; and ill-defined conditions and factors influencing health status',
    '17.1': 'Symptoms; signs; and ill-defined conditions',
    '17.1.1': 'Syncope',
    '17.1.2': 'Fever of unknown origin',
    '17.1.3': 'Lymphadenitis',
    '17.1.4': 'Gangrene',
    '17.1.5': 'Shock',
    '17.1.6': 'Nausea and vomiting',
    '17.1.7': 'Abdominal pain',
    '17.1.8': 'Malaise and fatigue',
    '17.1.9': 'Allergic reactions',
    '17.2': 'Factors influencing health care',
    '17.2.1':
        'Rehabilitation care; fitting of prostheses; and adjustment of devices',
    '17.2.2': 'Administrative/social admission',
    '17.2.3': 'Medical examination/evaluation',
    '17.2.4': 'Other aftercare',
    '17.2.5':
        'Other screening for suspected conditions (not mental disorders or infectious disease) -',
    '18': 'Residual codes; unclassified; all E codes',
};

const diseases = [
    {
        key: '',
        value: '',
        text: '',
    },
];

for (const d in rawDiseases) {
    diseases.push({
        key: d,
        value: `${d} ${rawDiseases[d]}`,
        text: rawDiseases[d],
    });
}

export default diseases;
