export const favChiefComplaints = [
    'Hypertension',
    'Diabetes',
    'Urinary Symptoms/UTI',
    'Upper Respiratory Infection',
    'Depression',
    'Insomnia',
    'Hyperlipidemia',
    'Opiate Use',
    'Genital Symptoms/STI',
    'ADHD',
    'Urination or Bladder Concerns',
    'High Cholesterol/Triglycerides',
    'High Blood Pressure',
];
