export const PART_OF_SPEECH_CORRECTION_MAP: Map<string, string> = new Map([
    [' he sometimes drink ', ' he sometimes drinks '],
    [' she sometimes drink ', ' she sometimes drinks '],
    [' they is ', ' they are '],
    [' he have ', ' he has '],
    [' she have ', ' she has '],
    [' make he ', ' make him '],
    [' make she ', ' make her '],
    [' he to ', ' him to '],
    [' she to ', ' her to '],
    [' he do ', ' he does '],
    [' she do ', ' she does '],
    [' he expel ', ' he expels '],
    [' she expel ', ' she expels '],
    [' he are ', ' he is '],
    [' she are ', ' she is '],
    [' he wish ', ' he wishes '],
    [' she wish ', ' she wishes '],
    [' wake up he ', ' wake up him '],
    [' wake up she ', ' wake up her '],
    [' wake he up ', ' wake him up '],
    [' wake she up ', ' wake her up '],
    [' affected he ', ' affected him '],
    [' affected she ', ' affected her '],
    [' he were ', ' he was '],
    [' she were ', ' she was '],
    [' he have had ', ' he has had '],
    [' she have had ', ' she has had '],
    [' causes he ', ' causes him '],
    [' causes she ', ' causes her '],
    [' he smoke ', ' he smokes '],
    [' she smoke ', ' she smokes '],
    [' they reports ', ' they report '],
    [' they has ', ' they have '],
    [' they does ', ' they do '],
    [' hisself ', ' himself '],
]);
