import { getOptionMapping } from '../_processOptions';

const medications = [
    'R-Gene 10 Injection (10% arginine hydrochloride, USP)',
    'Gelsyn-3 (3 injection hyaluronic acid)',
    'Humalog Mix 50/50 (50% Insulin Lispro Protamine Suspension, 50% Insulin Lispro Injection (rDNA))',
    'Novolin N Vials (70% NPH/30% regular human insulin (rDNA))',
    'Ziagen (abacavir sulfate)',
    'Epzicom tablets (abacavir sulfate and lamivudine)',
    'Trizivir (Tablets) (abacavir sulfate, lamivudine, and zidovudine))',
    'Triumeq (abacavir/dolutegravir/lamivudine)',
    'Tymlos (abaloparatide)',
    'Orencia (abatacept)',
    'Verzenio (abemaciclib)',
    'Yonsa (abiraterone acetate)',
    'Zytiga tablets (abiraterone acetate)',
    'Dysport Injection (abobotulinumtoxinA)',
    'Calquence (acalabrutinib)',
    'Campral (acamprosate)',
    'Precose (acarbose)',
    'Sectral (acebutolol)',
    'Tylenol (Acetaminophen)',
    'Paracetamol (Acetaminophen)',
    'Aceta (Acetaminophen)',
    'Panadol (Acetaminophen)',
    'Esgic (Acetaminophen; Butalbital)',
    'Fioricet (Acetaminophen; Butalbital)',
    'Vicodin (Acetaminophen; Hydrocodone Bitartrate)',
    'Norco (Acetaminophen; Hydrocodone Bitartrate)',
    'Stagesic (Acetaminophen; Hydrocodone Bitartrate)',
    'Zydone (Acetaminophen; Hydrocodone Bitartrate)',
    'Diamox (acetazolamide)',
    'Percocet (acetominophen, oxycodone)',
    'Roxicet (acetominophen, oxycodone)',
    'Mucomyst (acetylcysteine)',
    'Soriatane Capsules (acitretin)',
    'Zovirax (acyclovir)',
    'HUMIRA (adalimumab)',
    'Hepsera (adefovir dipivoxil)',
    'Adenocard (adenosine)',
    'Adenoscan (adenosine)',
    'Detachol (adhesive remover)',
    'Kadcyla (ado-trastuzumab emtansine)',
    'Gilotrif Tablet (afatinib)',
    'Eylea injection (aflibercept)',
    'Fabrazyme (agalsidase beta)',
    'Abraxane (albumin-bound paclitaxel)',
    'Proventil HFA Inhaler (albuterol)',
    'Proventil (albuterol)',
    'ProAir (albuterol)',
    'Ventolin (albuterol)',
    'ProAir Hfa inhaler (albuterol hfa)',
    'Proair Respiclick (albuterol sulfate)',
    'Ventolin HFA (albuterol sulfate HFA inhalation aerosol)',
    'DuoNeb (albuterol sulfate; ipratropium bromide)',
    'Aclovate (alclometasone dipropionate cream)',
    'Proleukin (aldesleukin)',
    'Alecensa (alectinib)',
    'Lemtrada (alemtuzumab)',
    'Binosto (alendronate tablet)',
    'Fosamax (alendronate tablet)',
    'Fosamax Plus D (alendronate tablet)',
    'Uroxatral (alfuzosin hcl)',
    'Lumizyme IV (alglucosidase alfa)',
    'Praluent (alirocumab)',
    'Panretin gel (alitretinoin)',
    'Zyloprim (allopurinol tablet)',
    'Aloprim (allopurinol tablet)',
    'Nesina (alogliptin)',
    'Kazano (alogliptin and metformin HCL)',
    'Oseni (alogliptin and pioglitazone)',
    'Lotronex (alosetron HCL)',
    'Piqray (alpelisib)',
    'Prolastin C (alpha1-proteinase inhibitor (human))',
    'Zemaira (Alpha1-Proteinase Inhibitor (Human))',
    'Xanax (alprazolam)',
    'Caverject (alprostadil)',
    'Hexalen capsules (altretamine)',
    'Mylanta (aluminum hydroxide, magnesium hydroxide)',
    'Maalox (aluminum hydroxide, magnesium hydroxide)',
    'Osmolex ER (amantadine)',
    'Symmetrel (amantadine)',
    'Gocovri (amantadine; extended release capsule)',
    'Letairis Tablets (ambrisentan)',
    'Firdapse (amifampridine tablet)',
    'Ethyol (amifostine)',
    'Arikayce (amikacin liposome inhalation suspension)',
    'Midamor (amiloride)',
    'Pacerone (Amiodarone Hydrochloride)',
    'Nexterone (Amiodarone Hydrochloride)',
    'Cordarone (amiodarone tablet)',
    'Endep (amitriptyline)',
    'Elavil (amitriptyline tablet)',
    'Exforge (amlodipine and valsartan)',
    'Norvasc (amlodipine besylate)',
    'Caduet (amlodipine besylate/atorvastatin calcium)',
    'Katerzia (amlodipine oral suspension)',
    'Exforge HCT (amlodipine, valsartan, hydrochlorothiazide)',
    'Lotrel (Amlodipine/Benazepril capsule)',
    'Moxatag (amoxacillin)',
    'Augmentin (amoxacillin-clavulanate)',
    'Defanyl (amoxapine)',
    'Demolox (amoxapine)',
    'Moxadil (amoxapine)',
    'Asendin (amoxapine tablet)',
    'Dyanavel XR (amphetamine)',
    'Evekeo (amphetamine)',
    'Adderall (amphetamine aspartate)',
    'Adderall (amphetamine sulfate tablet)',
    'AmBisome (injection) (amphotericin B, lipid-based)',
    'Ampi (ampicillin)',
    'Omnipen (ampicillin)',
    'Penglobe (ampicillin)',
    'Principen (ampicillin)',
    'Unasyn (ampicllin, sulbactam)',
    'Pertzye capsule (amylase/lipase/pancrelipase/protease)',
    'Agrylin (anagrelide hydrochloride)',
    'Kineret (anakinra)',
    'Arimidex (anastrazole)',
    'Eraxis (anidulafungin IV)',
    'Thymoglobulin Vial (Anti-thymocyte Globulin (Rabbit))',
    'Xyntha (antihemophiliam factor (recombinant))',
    'Advate (antihemophilic factor)',
    'Monoclate-P (Antihemophilic Factor (Human) Factor VIII:C Pasteurized)',
    'Afstyla (antihemophilic factor (recombinant))',
    'Helixate FS (antihemophilic factor (recombinant))',
    'Kogenate FS (antihemophilic factor (recombinant))',
    'Kovaltry (antihemophilic factor (recombinant))',
    'Obizur (Antihemophilic Factor (Recombinant))',
    'Jivi (antihemophilic factor (recombinant) PEGylated)',
    'Novoeight vial (antihemophilic factor (recombinant) vial)',
    'Adynovate (Antihemophilic Factor (Recombinant), PEGylated)',
    'Eloctate Injection (antihemophilic factor recombinant fc fusion protein)',
    'Esperoct solution (antihemophilic factor recombinant injection; iv lyophilized powder)',
    'Alphanate injection (antihemophilic factor/von willebrand factor complex (human))',
    'Humate-P (antihemophilic factor/von willebrand factor complex (Human))',
    'Corzide (antihypertensive combinations)',
    'Erleada Tablets (apalutamide)',
    'Eliquis (apixaban)',
    'Otezla Tablet (apremilast)',
    'EMEND (aprepitant)',
    'Cinvanti (aprepitant injectable emulsion; iv)',
    'Abilify (aripiprazole)',
    'Abilify Maintena injection (aripiprazole)',
    'Aristada (aripiprazole lauroxil)',
    'Nuvigil (armodafinil)',
    'Trisenox (arsenic trioxide)',
    'Artificial Tears 1.4% drops (OTC) (artificial tears 1.4% drops (OTC))',
    'Coartem (artmether and lumefantrine tablets)',
    'Saphris sublingual tablets (asenapine maleate)',
    'Secuado (asenapine transdermal system)',
    'Strensiq injection (asfotase alfa injection)',
    'Erwinaze Injection (asparaginase erwinia chrysanthemi)',
    'Ascriptin (aspirin)',
    'Aspergum (aspirin)',
    'Aspirtab (aspirin)',
    'Bayer (aspirin)',
    'Easprin (aspirin)',
    'Ecotrin (aspirin)',
    'Ecpirin (aspirin)',
    'Entercote (aspirin)',
    'Genacote (aspirin)',
    'Halfprin (aspirin)',
    'Ninoprin (aspirin)',
    'Norwich Aspirin (aspirin)',
    'Aspirin EC Tablet (OTC) (aspirin EC tablet (OTC))',
    'Tenormin (atenolol tablet)',
    'Tenoretic (atenolol/chlorthalidone tablet)',
    'Tecentriq (atezolizumab)',
    'Strattera (atomoxetine hcl)',
    'Torvast (atorvastatin)',
    'Lipitor (atorvastatin calcium)',
    'Mepron suspension (atovaquone)',
    'Malarone tablets (atovaquone and proguanil hcl)',
    'Tracrium (only generic) (atracurium besylate)',
    'Atropine Care (atropine sulfate (ophthalmic route))',
    'Isopto Atropine (atropine sulfate (ophthalmic route))',
    'Ocu-Tropine (atropine sulfate (ophthalmic route))',
    'AtroPen (atropine)',
    'Diprolene Cream (augmented betamethasone dipropionate)',
    'Ridaura (auranofin)',
    'Ayvakit tablet (avapritnib tablet)',
    'Doptelet (avatrombopag)',
    'Bavencio (avelumab injection)',
    'Yescarta (axicabtagene ciloleucel)',
    'Inlyta (axitinib)',
    'Vidaza (azacitidine)',
    'Imuran (azathioprine)',
    'Azasan (azathioprine)',
    'Astepro (azelastine)',
    'Astelin (Azelastine nasal spray)',
    'Edarbyclor Tablet (azilartan medoxomil/chlorthalidone)',
    'Edarbi Tablet (azilsartan medoxomil)',
    'Zithromax (azithromycin)',
    'Zmax (azithromycin extended release)',
    'Cayston (aztreonam for inhalation solution)',
    'Similac PM 60/40 (baby formula)',
    'Bacitracin (bacitracin)',
    'baciim (Bacitracin)',
    'Neosporin (Bacitracin; Neomycin; Polymyxin B)',
    'Lioresal injectable (baclofen injectable; intrathecal)',
    'Lioresal (baclofen tablet)',
    'Colazal (balsalazide)',
    'Olumiant (baricitinib)',
    'Beconase AQ (nasal spray) (beclomethasone dipropionate)',
    'QNASL Nasal Aerosol (beclomethasone dipropionate)',
    'Qvar (beclomethasone dipropionate hfa)',
    'Sirturo Tablets (bedaquiline)',
    'Blenrep (belantamab mafodotin)',
    'Nulojix (belatacept)',
    'Benlysta (belimumab)',
    'Beleodaq Powder (belinostat)',
    'Donnatal Tablet (Belladonna Alkaloids with Phenobarbital)',
    'Lotensin HCT (benazepril HCTZ tablet)',
    'Lotensin (benazepril tablet)',
    'Bendeka Injection (bendamustine HCl)',
    'Treanda (bendamustine hcl)',
    'Fasenra (benralizumab)',
    'Fasenra Pen (benralizumab)',
    'Lindane (gamma benzene hexachloride)',
    'Hurricaine (benzocaine spray)',
    'Tessalon Capsule (benzonatate)',
    'Cogentin (benztropine tablet)',
    'Bepreve Ophthalmic Solution 1.5% (bepotastine besilate)',
    'Vascor (bepridil)',
    'Besivance (besifloxacin ophthalmic suspension)',
    'Cystadane (betaine anhydrous)',
    'Kerlone (betaxolol)',
    'Urecholine (bethanechol tablet)',
    'Avastin (bevacizumab)',
    'Mvasi (bevacizumab-awwb)',
    'Zirabev (bevacizumab-bvzr)',
    'Targretin (bexarotene)',
    'Zinplava (bezlotoxumab)',
    'Apligraf (bi-layered skin substitute)',
    'Casodex (bicalutamide)',
    'Biktarvy (bictegravir/emtricitabine/tenofovir alafenamide)',
    'Durysta (bimatoprost implant)',
    'Lumigan (bimatoprost ophthalmic solution)',
    'Pylera Capsules (bismuth subcitrate potassuim, metronidazole, tetracycline HCI)',
    'Pepto-Bismol (bismuth subsalicylate)',
    'Zebeta (bisoprolol)',
    'Ziac (bisoprolol/HCTZ tablet)',
    'Blenoxane (bleomycin)',
    'Blincyto (blinatumomab)',
    'Prodigy Preferred Blood Glucose Monitor (blood glucose monitor)',
    'Prodigy No Coding Blood Glucose Strips (blood glucose strips)',
    'Vectra DA (blood test)',
    'Velcade (bortezomib)',
    'Tracleer tablets (bosentan)',
    'Bosulif (bosutinib)',
    'Botox (botulinum toxin type A)',
    'Adcetris (brentuximab vedotin)',
    'Zulresso (brexanolone injection)',
    'Rexulti tablet (brexpiprazole tablet)',
    'Tecartus (brexucabtagene autoleucel)',
    'Alunbrig (brigatinib)',
    'Brimonidine Tartrate 0.2% Solution (brimonidine tartrate)',
    'Alphagan P 1% (brimonidine tartrate ophthalmic solution)',
    'Combigan (brimonidine tartrate/timolol maleate opthalmic solution)',
    'Azopt (brinzolamide suspension)',
    'Simbrinza (brinzolamide/brimonidine tartrate suspension)',
    'Briviact (brivaracetam)',
    'Siliq (brodalumab)',
    'Beovu (brolucizumab-dbll)',
    'Prolensa (bromfenac sodium solution)',
    'Cycloset tablet (bromocriptine mesylate tablets)',
    'Parlodel (bromocriptine tablet)',
    'Uceris rectal foam (budesonide)',
    'entocort (budesonide  )',
    'uceris (budesonide  )',
    'Pulmicort Flexhaler (budesonide inhalation powder)',
    'Pulmicort Respules (budesonide inhalation suspension)',
    'Symbicort (budesonide/formoterol fumarate dihydrate)',
    'Bumex (bumetanide)',
    'Marcane (bupivicaine)',
    'Suboxone Sublingual Film (buprenorphine and naloxone)',
    'Zubsolv Tablet; Sublingual (buprenorphine/naloxone)',
    'Zyban (bupropion)',
    'Wellbutrin   (bupropion)',
    'Wellbutrin (bupropion HCL tablet)',
    'Wellbutrin XL (bupropion HCL XL)',
    'Crysvita (burosumab-twza injection)',
    'Buspar (buspirone tablet)',
    'Busulfex (busulfan)',
    'Stadol (butorphanol tartrate)',
    'Cinryze (c1 esterase inhibitor)',
    'Berinert (c1 esterase inhibitor)',
    'Haegarda (C1 esterase inhibitor human injection; subcutaneous)',
    'Ruconest (C1esterase inhibitor (recombinant))',
    'Jevtana (cabazitaxel)',
    'Cabometyx (cabozantinib s-malate)',
    'Cometriq capsule (cabozantinib s-malate capsule)',
    'Rayaldee (calcifediol)',
    'Calcilo XD Powder (Calcilo XD Powder)',
    'Fortical Nasal Spray (Calcitonin-salmon (rDNA origin))',
    'Rocaltrol (calcitriol capsule)',
    'Phoslyra (calcium acetate)',
    'PhosLo gelcaps (calcium acetate)',
    'Tums (calcium carbonate)',
    'Rolaids (calcium carbonate)',
    'Chooz (calcium carbonate)',
    'Gluconate (calcium gluconate)',
    'Invokana (canagliflozin)',
    'Invokamet (canagliflozin-metformin)',
    'Invokamet XR (canagliflozin/metformin HCI)',
    'Ilaris (canakinumab)',
    'Atacand HCT (candesartan cilexetil-hydrochlorothiazide)',
    'Atacand (candesartan cilextil)',
    'Epidiolex (cannabidiol)',
    'Xeloda (capecitabine)',
    'Cablivi (caplacizumab-YHDP)',
    'Tabrecta (capmatinib)',
    'Qutenza Patch (capsaicin)',
    'Capsaicin Cream, 0.035% (OTC) (capsaicin cream, 0.035% (OTC))',
    'Capoten (captopril tablet)',
    'Miostat (carbachol)',
    'Carbatrol (carbamazepine)',
    'Equetro (carbamazepine)',
    'Tegretol (carbamazepine)',
    'Tegretol XR (carbamazepine extended release)',
    'lodosyn (carbidopa)',
    'Sinemet (carbidopa/levodopa tablet)',
    'Rytary (carbidopa/levodopa tablet)',
    'Duopa (carbidopa/levodopa tablet)',
    'Hemabate (carboprost tromethamine,USP)',
    'Kyprolis Injection (carfilzomib)',
    'Carbaglu (carglumic acid)',
    'Vraylar (cariprazine)',
    'Bicnu (carmustine)',
    'Cartrol (carteolol)',
    'Coreg (carvedilol)',
    'Coreg CR (carvedilol phosphate extended release capsules)',
    'Cancidas (caspofungin acetate)',
    'Ancef (cefazolin)',
    'Omnicef (cefdinir)',
    'Cefobid (cefoperazone)',
    'Cefotan (cefotetan)',
    'Mefoxin (cefoxitin)',
    'Teflaro (ceftaroline)',
    'Avycaz Vials (ceftazidime/avibactam)',
    'Zerbaxa Injection (ceftolozane/tazobactam)',
    'Rocephin (ceftriaxone)',
    'Celebrex (celecoxib)',
    'Libtayo injection (cemiplimab-rwlc)',
    'Xcopri (cenobamate tablets)',
    'Keflex (cephalexin)',
    'Panixine (cephalexin)',
    'Disperidose (cephalexin)',
    'Zykadia (ceritinib)',
    'Brineura (cerliponase alpa)',
    'CIMZIA (certolizumab pegol)',
    'Zyrtec OTC (cetirizine HCl tablet - OTC)',
    'Aller-Tec (cetirizine HCl tablet - OTC)',
    'Wal-Zyr (cetirizine HCl tablet - OTC)',
    'Erbitux (cetuximab)',
    'Evoxac (cevimeline HCl)',
    'Ocu-Chlor (chloramphenicol)',
    'Librium (chlordiazepoxide)',
    'Chlordiazepoxide capsule (chlordiazepoxide capsule)',
    'Diuril (chlorothiazide)',
    'Thorazine (chlorpromazine)',
    'Chlorpromazine HCL (chlorpromazine HCL)',
    'Hygroton (chlorthalidone tablet)',
    'Thalitone (chlorthalidone tablet)',
    'Chlorthalid (chlorthalidone tablet)',
    'Delta D3 (cholecalciferol)',
    'Prevalite Powder (cholestyramine)',
    'Cholbam capsule (cholic acid capsule)',
    'Primaxin IM (cilastatin, imipenem)',
    'Primaxin IV (cilastatin, imipenem)',
    'Pletal (cilostazol tablet)',
    'Tagamet (cimetidine)',
    'Sensipar (cinacalcet HCl)',
    'Otiprio (ciprofloxacin)',
    'Cipro (ciprofloxacin)',
    'Ciprodex (ciprofloxacin and dexamethasone)',
    'Cipro HC Otic (ciprofloxacin hydrochloride and hydrocortisone suspension)',
    'Nimbex (cisatracurium)',
    'Platinol  (cisplatin)',
    'Platinol-AQ (cisplatin)',
    'Celexa (citalopram tablet)',
    'Mavenclad (cladribine tablet)',
    'Biaxin (clarithromycin)',
    'Biaxin Filmtab (clarithromycin)',
    'Biaxin XL (clarithromycin)',
    'Clindagel Topical Gel (clinclamycin phosphate gel)',
    'Dalacin (clindamycin)',
    'Cleocin HCl (clindamycin)',
    'Clinacin (clindamycin  )',
    'Cleocin Phosphate (clindamycin phosphate)',
    'Cleocin (clindamycin phosphate)',
    'Evoclin (clindamycin phosphate)',
    'Acanya (clindamycin phosphate and benzoyl peroxide)',
    'Onexton Gel (clindamycin phosphate and benzoyl peroxide)',
    'Onfi Tablet (clobazam)',
    'Clomid (clomiphene)',
    'Serophene (clomiphene)',
    'Anafranil (clomipramine hcl)',
    'Klonopin (clonazepam tablet)',
    'Kapvay (clonidine)',
    'Catapres (clonidine HCL tablets)',
    'Clorpres (clonidine hydrochloride and chlorthalidone)',
    'Combipres (clonidine hydrochloride and chlorthalidone)',
    'Catapres TTS -3 (clonidine patch)',
    'Clopilet (clopidogrel)',
    'Plavix (clopidogrel bisulfate tablets)',
    'Tranxene (clorazepate dipotassium)',
    'Lotrisone Cream (clotrimazole/betamethasone cream)',
    'Clozapine (clozapine)',
    'Clozaril (clozapine)',
    'FazaClo (clozapine)',
    'Versacloz (clozapine)',
    'Feiba VH powder (coagulant complex inhibitor)',
    'AlphaNine SD (coagulation factor ix (human))',
    'Ixinity injection (coagulation factor IX (recombinant))',
    'Rixubis (coagulation factor IX (recombinant))',
    'Rebinyn (coagulation factor IX (recombinant) glycopegylated)',
    'Idelvion (coagulation factor IX (recombinant), albumin fusion protein)',
    'Alprolix (Coagulation Factor IX (Recombinant), Fc Fusion Protein)',
    'NovoSeven RT injection (coagulation factor viia (recombinant))',
    'Coagadex (Coagulation Factor X, Human)',
    'Tretten Injection (coagulation factor Xlll A-Subunit (rDNA))',
    'Tybost (cobicistat)',
    'Cotellic (cobimetinib)',
    'Colcrys tablet (colchicine)',
    'Mitigare (colchicine)',
    'Colestid (colestipol hcl)',
    'Xiaflex Injection (collagenase clostridium histolyticum)',
    'Compleat (compleat)',
    'Compleat Pediatric (compleat pediatric)',
    'Premarin (conjugated estrogens)',
    'Premarin vaginal cream (conjugated estrogens)',
    'Prempro (conjugated estrogens; medroxyprogesterone acetate)',
    'Duavee Tablet (conjugated estrogens/bazedoxifene)',
    'Premphase (conjugated estrogens/medroxyprogesterone acetate tablets)',
    'Aliqopa (copanlisib)',
    'Adakveo (crizanlizumab-tmca)',
    'Xalkori (crizotinib)',
    'Mytesi tablet; delayed-release (crofelemer)',
    'Vitamin B12 (cyanocobalamin)',
    'Cyclinex-1 Powder (Cyclinex-1 Powder)',
    'Cyclinex-2 Powder (Cyclinex-2 Powder)',
    'Flexeril (Cyclobenzaprine)',
    'Cytoxan (cyclophosphamide)',
    'Cytoxan Lyophilized (cyclophosphamide)',
    'Neoral (cyclosporine)',
    'Restasis (cyclosporine)',
    'Sandimmune (cyclosporine)',
    'Gengraf Capsules (cyclosporine capsules, USP modified)',
    'Procysbi (cysteamine bitartrate delayed-release capsule)',
    'CytoGam Injection (Cytomegalovirus Immune Globulin Intravenous Human CMV-IGIV injection; iv)',
    'Pradaxa Capsules (dabigatran etexilate)',
    'Tafinlar (dabrafenib)',
    'Vizimpro (dacomitinib)',
    'Cosmegen Injection (dactinomycin injectable)',
    'Dalvance Vials (dalbavancin)',
    'Ampyra Tablet (dalfampridine)',
    'Fragmin (dalteparin sodium)',
    'Orgaran (danaparoid)',
    'Farxiga Tablet (dapagliflozin)',
    'Qtern (dapagliflozin and saxagliptin)',
    'Xigduo XR (dapagliflozin/metformin)',
    'Aczone (dapsone)',
    'Cubicin injection (daptomycin)',
    'Darzalex (daratumumab)',
    'Darzelex Faspro (daratumumab and hyaluronidase-fihj, Injection for subcutaneous use)',
    'Aranesp (darbepoetin alfa)',
    'Enablex (darifenacin)',
    'Nubeqa (darolutamide)',
    'Prezista (darunavir)',
    'Symtuza (darunavir, cobicistat, emtricitabine, and tenofovir alafenamide)',
    'Prezcobix Tablets (darunavir/cobicistat)',
    'Sprycel (dasatinib)',
    'Cerubidine (daunorubicin)',
    'Vyxeos (daunorubicin/cytarabine)',
    'Dacogen (decitabine)',
    'Inqovi (decitabine and cedazuridine)',
    'Exjade (deferasirox)',
    'Jadenu Sprinkle granules (deferasirox)',
    'Jadenu Tablet (deferasirox)',
    'Jadenu (deferasirox)',
    'Ferriprox (deferiprone)',
    'Desferal (deferoxamine)',
    'Defitelio (Defibrotide sodium)',
    'Emflaza (deflazacort)',
    'Declomycin (demeclocycline)',
    'Prolia (denosumab)',
    'XGEVA (denosumab)',
    'Depo-Provera (depot medroxyprogesterone acetate)',
    'Dermagraft Dermal Substitute 2x3 (dermagraft)',
    'Norpramin (desipramine)',
    'Stimate (desmopressin acetate)',
    'Apri (desogestrel; ethinyl estradiol)',
    'Caziant (desogestrel; ethinyl estradiol)',
    'Cesia (desogestrel; ethinyl estradiol)',
    'Cyclessa (desogestrel; ethinyl estradiol)',
    'Desogen (desogestrel; ethinyl estradiol)',
    'Enskyce (desogestrel; ethinyl estradiol)',
    'Kariva (desogestrel; ethinyl estradiol)',
    'Mircette (desogestrel; ethinyl estradiol)',
    'Ortho-Cept (desogestrel; ethinyl estradiol)',
    'Reclipsen (desogestrel; ethinyl estradiol)',
    'Solia (desogestrel; ethinyl estradiol)',
    'Velivet (desogestrel; ethinyl estradiol)',
    'Pristiq (desvenlafaxine)',
    'Austedo (deutetrabenazine)',
    'Ozurdex Intravitreal Implant (dexamethasone)',
    'Dextenza (dexamethasone ophthalmic insert)',
    'Maxidex (dexamethasone suspension)',
    'Dexilant (dexlansoprazole)',
    'Focalin (Dexmethylphenidate HCl tablet)',
    'Zinecard (dextrazoxane)',
    'Totect (dextrazoxane)',
    'Dexedrine (dextroamphetamine)',
    'Adderall (dextroamphetamine Saccharate)',
    'Adderall (dextroamphetamine Sulfate)',
    'Nuedexta (dextromethorphan hydrobromide and quinidine sulfate)',
    'Dalgan (dezocine)',
    'Diabetisource AC (diabetisource AC)',
    'Valtoco (diazepam nasal spray)',
    'Valium (diazepam tablet)',
    'Proglycem oral suspension (diazoxide)',
    'Keveyis tablet (dichlorphenamide tablet)',
    'Voltaren (diclofenac EC tablet)',
    'Flector Patch 1.3% (diclofenac epolamine topical patch)',
    'Voltaren XR (diclofenac ER tablet)',
    'Pennsaid (diclofenac sodium solution; topical)',
    'Arthrotec (diclofenac sodium/misoprostol)',
    'Bentyl (dicyclomine capsule)',
    'Videx (didanosine)',
    'Videx EC (didanosine)',
    'Durezol (difluprednate emulsion)',
    'Lanoxin (digoxin tablets)',
    'Digitek (digoxin tablets)',
    'Digox (digoxin tablets)',
    'Lanoxicaps (digoxin tablets)',
    'Cardizem (diltiazem)',
    'Tiazac (diltiazem)',
    'Dilacor XR (diltiazem ER capsule)',
    'Cardizem CD (diltiazem hcl cd)',
    'BAL (dimercaprol)',
    'Tecfidera Capsule; Delayed Release (dimethyl fumarate)',
    'Lomotil (diphenoxylate hydrochloride/atropine sulfate)',
    'Lonox (diphenoxylate/atropine tablet)',
    'Pentacel (Diptheria and Tetanus Toxoids and Acellular Pertussis Adsorbed, Inactivated Poliovirus and Haemophilus b Conjugate (Tetanus Toxoid Conjugate) Vaccine)',
    'Vumerity (diroximel fumarate)',
    'Norpace (disopyramide)',
    'Depakote Sprinkles (divalproex sodium capsule)',
    'Depakote ER Tablets (divalproex sodium extended release tablets)',
    'Depakote (divalproex sodium tablet, delayed release)',
    'Depakote ER (divalproex sodium tablet, delayed release)',
    'Dobutrex (dobutamine)',
    'Colace (docusate sodium)',
    'Enemeez (docusate sodium)',
    'Tivicay tablet (dolutegravir)',
    'Juluca (dolutegravir and rilpivirine)',
    'Aricept (donepezil HCI)',
    'Namzaric (donepezil hydrochloride capsule and memantine hydrochloride)',
    'Donepezil (donepezil hydrochloride tablet)',
    'Inotropin (dopamine)',
    'Pifeltro (doravirine)',
    'Delstrigo (doravirine, lamivudine, and tenofovir disoproxil fumarate)',
    'Pulmozyme (dornase alfa recombinant inhalation solution)',
    'Trusopt (dorzolamide HCL)',
    'Cardura (doxazosin mesylate)',
    'Cardura XL (doxazosin mesylate)',
    'Adapin (doxepin)',
    'Doxepin capsule (doxepin capsule)',
    'Adriamycin (doxorubicin)',
    'Adoxa (doxycycline)',
    'Doryx (doxycycline)',
    'Monodox (doxycycline)',
    'Oracea (doxycycline)',
    'Periostat (doxycycline)',
    'Vibramycin (doxycycline)',
    'Multaq (dronedarone tablets)',
    'Inapsine (droperidol)',
    'Beyaz (drospirenon/ethinyl estradiol/levomefolate calcium)',
    'Yaz (drospirenone & ethinyl estradiol)',
    'Angeliq (drospirenone/estradiol)',
    'Yasmin (drospirenone/ethinyl estradiol tablets)',
    'Safyral (drospirenone/ethinyl estradiol/levomefolate calcium)',
    'Northera Capsule (droxidopa)',
    'Trulicity (dulaglutide)',
    'Cymbalta (duloxetine hcl)',
    'Dupixent (dupilumab injection)',
    'Imfinzi (durvalumab)',
    'Jalyn (dutasteride and tamsulosin hydrochloride)',
    'Copiktra (duvelisib)',
    'Kalbitor (ecallantide)',
    'Phospholine Iodide for Ophthalmic Solution (echothiophate iodide)',
    'Soliris (eculizumab)',
    'Radicava iv (edaravone iv)',
    'Savaysa (edoxaban)',
    'Enlon (edrophonium)',
    'Reversol (edrophonium)',
    'Disotate (EDTA)',
    'Endrate (EDTA)',
    'Atripla (efavirenx/emtricitabine/tenofovir disoproxil fumarate)',
    'Jublia (efinaconazole)',
    'egometrine maleate (egometrine maleate)',
    'Orilissa (elagolix)',
    'Zepatier (elbasvir/grazoprevir)',
    'EleCare (EleCare)',
    'Relpax (eletriptan HBr)',
    'Trikafta tablet (elexacaftor/tezacaftor/ivacaftor)',
    'Cerdelga (eliglustat capsule)',
    'Vimizim (elosulfase alfa)',
    'Empliciti (elotuzumab)',
    'Promacta (eltrombopag)',
    'Viberzi (eluxadoline)',
    'Genvoya (elvitegravir/cobicistat/emtricitabine/tenofovir alafenamide)',
    'Stribild tablet (elvitegravir/cobicistat/emtricitabine/tenofovir disoproxil fumarate)',
    'Gamifant (emapalumab-lzsg)',
    'Hemlibra (emicizumab-kxwh)',
    'Biafine (emollient cream)',
    'Jardiance Tablet (empagliflozin)',
    'Glyxambi Tablet (empagliflozin/linagliptin)',
    'Synjardy XR (empagliflozin/metformin HCl Extended Release)',
    'Synjardy (empagliflozin/metformin hydrochloride)',
    'Emtriva (emtricitabine)',
    'Odefsey (emtricitabine/rilpivirine/tenofovir alafenamide)',
    'Complera (emtricitabine/rilpivirine/tenofovir disoproxil fumarate)',
    'Descovy (emtricitabine/tenofovir alafenamide)',
    'Lexxel (enalapril and felodipine)',
    'Vasotec (enalapril maleate tablet)',
    'Vaseretic (enalapril maleate-hydrochlorothiazide tablets)',
    'Idhifa (enasidenib)',
    'Braftovi capsules (encorafenib)',
    'Ethrane (enflurane)',
    'Padcev (enfortumab vedotin-ejfv)',
    'Lovenox (enoxaparin sodium)',
    'Ensure (Ensure)',
    'Ensure Plus (Ensure Plus)',
    'Baraclude (entecavir)',
    'Rozlytrek (entrectinib)',
    'Xtandi (enzalutamide)',
    'Akovaz (ephedrine)',
    'Corphedra (ephedrine)',
    'EpiPen (epinephrine)',
    'EpiPen Jr (epinephrine)',
    'Adrenalin (epinephrine)',
    'Epinephrine auto injector .15mg (epinephrine auto injector)',
    'Epinephrine Auto Injector .3mg (epinephrine auto injector)',
    'Auvi-Q (epinephrine injection)',
    'Ellence (epirubicin hcl)',
    'Inspra (eplerenone)',
    'Epogen (epoetin alfa)',
    'Procrit (epoetin alfa)',
    'Retacrit (epoetin alfa-epbx)',
    'Veletri Injection (epoprostenol)',
    'Teveten (eprosartan)',
    'Vyepti (eptinezumab-jjmr injection)',
    'Balversa (erdafitinib)',
    'Aimovig (erenumab)',
    'Calciferol (Ergocalciferol)',
    'Drisdol (Ergocalciferol)',
    'Ergotrate (ergometrine)',
    'Ergotrate Maleate (ergometrine)',
    'Halaven Injection (eribulin mesylate)',
    'Tarceva (erlotinib)',
    'Invanz (ertapenem)',
    'Eryc (erythromycin)',
    'Eryped (erythromycin)',
    'Ery-Tab (erythromycin)',
    'Erythrocin (erythromycin)',
    'Ilosone (erythromycin)',
    'PCE (erythromycin)',
    'PCE Dispertab (erythromycin)',
    'EES Granules (erythromycin)',
    'Erythrocin Stearate (erythromycin)',
    'Benzamycin Topical Gel (erythromycin; benzoyl peroxide)',
    'Lexapro (escitalopram oxalate)',
    'Spravato Nasal Spray CIII (esketamine)',
    'Aptiom Tablet (eslicarbazepine acetate)',
    'Brevibloc (esmolol)',
    'Nexium (esomeprazole DR capsule)',
    'Menest (esterified estrogens)',
    'Vagifem (estradiol hemihydrate)',
    'Estrace (estradiol tablet)',
    'Menostar (estradiol transdermal system)',
    'Estrace Cream (estradiol vaginal cream)',
    'Estring (estradiol vaginal ring)',
    'Natazia (estradiol valerate and estradiol valerate/dienogest)',
    'Climara Pro 0.045mg/.015mg (estradiol/levonorgestrel transdermal system)',
    'Emcyt (estramustine phosphate sodium)',
    'Depo Estradiol (estrodiol cypionate in oil)',
    'Ortho-Prefest (estrogens and progestins)',
    'Ogen (estropipate tablet)',
    'Lunesta (eszopiclone)',
    'Enbrel (etanercept)',
    'Parsabiv (etelcalcetide)',
    'Exondys 51 (eteplirsen injection)',
    'Myambutol (ethambutol)',
    'NuvaRing (ethinyl estradiol; etonogestrel)',
    'Levora (ethinyl estradiol; levonorgestrel)',
    'Alesse (ethinyl estradiol; levonorgestrel)',
    'Altavera (ethinyl estradiol; levonorgestrel)',
    'Amethia (ethinyl estradiol; levonorgestrel)',
    'Aviane (ethinyl estradiol; levonorgestrel)',
    'Camrese (ethinyl estradiol; levonorgestrel)',
    'Enpresse (ethinyl estradiol; levonorgestrel)',
    'Introvale (ethinyl estradiol; levonorgestrel)',
    'Jolessa (ethinyl estradiol; levonorgestrel)',
    'Lessina (ethinyl estradiol; levonorgestrel)',
    'Microgestin (ethinyl estradiol; norethindrone)',
    'Loestrin (ethinyl estradiol; norethindrone)',
    'Ortho Tri-Cyclen (ethinyl estradiol; norgestimate)',
    'Estarylla (ethinyl estradiol; norgestimate)',
    'MonoNessa (ethinyl estradiol; norgestimate)',
    'Previfem (ethinyl estradiol; norgestimate)',
    'Sprintec (ethinyl estradiol; norgestimate)',
    'TiNessa (ethinyl estradiol; norgestimate)',
    'Tri-Lo-Sprintec (ethinyl estradiol; norgestimate)',
    'Tri-Previfem (ethinyl estradiol; norgestimate)',
    'Tri-Sprintec (ethinyl estradiol; norgestimate)',
    'Trecator Tablets (ethionamide)',
    'Zarontin (ethosuximide)',
    'Peganone Tablets (ethotoin)',
    'Didronel (etidronate)',
    'Lodine (etodolac capsule)',
    'Amidate (etomidate)',
    'Implanon (etonogestrel)',
    'Nexplanon (etonogestrel)',
    'Intelence (etravirine)',
    'Afinitor (everolimus)',
    'Afinitor Disperz (everolimus)',
    'Zortress (everolimus)',
    'Repatha (evolocumab)',
    'Aromasin (exemestane)',
    'Byetta (exenatide)',
    'Bydureon BCise (exenatide extended-release)',
    'Bydureon (exenatide extended-release for injection suspension)',
    'Zetia (ezetimibe)',
    'Vytorin (ezetimibe/simvastatin)',
    'MonoNine Injection (factor ix)',
    'Corifact (factor xiii concentrate (human))',
    'Enhertu (fam-trastuzumab deruxtecan-nxki)',
    'Famvir (famciclovir tablet)',
    'Pepcid (famotidine tablet)',
    'ProfilNine (faxtor ix complex)',
    'Inrebic (fedratinib)',
    'Plendil (felodipine)',
    'Plendil ER (felodipine ER tablet)',
    'Fintepla (fenfluramine)',
    'Tricor (fenofibrate)',
    'Lofibra (fenofibrate, micronized capsule)',
    'Trilipix (fenofibric acid DR capsule)',
    'Corlopam (fenoldopam)',
    'Sublimaze (fentanyl citrate)',
    'Injectafer (ferric carboxymaltose injection)',
    'Auryxia Tablet (ferric citrate)',
    'Iron Sulfate (ferrous sulfate EC tablet)',
    'FeroSul (ferrous sulfate EC tablet)',
    'Slow Fe (ferrous sulfate EC tablet)',
    'Feosol Original (ferrous sulfate EC tablet)',
    'Feraheme Injection (ferumoxytol)',
    'Toviaz (fesoterodine fumarate)',
    'Allegra OTC (fexofenadine OTC tablet)',
    'RiaSTAP (fibrinogen concentrate (human))',
    'Neupogen (filgrastim)',
    'Nivestym (filgrastim-aafi)',
    'Zarxio (filgrastim-sndz)',
    'Proscar (finasteride tablet)',
    'Gilenya (fingolimod)',
    'Flecainide Acetate tablet (flecainide acetate tablet)',
    'Diflucan (fluconazole)',
    'Ancobon Caps (flucytosine)',
    'Florinef (fludrocortisone acetate)',
    'Romazicon (flumazenil)',
    'Iluvien (fluocinolone acetonide implant)',
    'Retisert (fluocinolone acetonide intravitreal implant)',
    'Efudex (fluorouracil)',
    'Carac Cream (fluorouracil cream)',
    'Sarafem (fluoxetine)',
    'Symbyax (fluoxetine HCl, olanzapine)',
    'Prozac (fluoxetine HCL)',
    'Prozac Weekly (fluoxetine HCL)',
    'Prolixin (fluphenazine)',
    'Breo Ellipta (fluticasone furoate and vilanterol inhalation powder)',
    'Arnuity Ellipta (fluticasone furoate inhalation powder)',
    'Trelegy Ellipta (fluticasone furoate, umeclidinium)',
    'Flonase (fluticasone nasal spray)',
    'Flovent (fluticasone propionate)',
    'Advair HFA (fluticasone propionate and salmeterol)',
    'Flovent HFA 110 mcg (fluticasone propionate inhalation aerosol)',
    'Flovent HFA 220 mcg (fluticasone propionate inhalation aerosol)',
    'Flovent HFA 44 mcg (fluticasone propionate inhalation aerosol)',
    'Flovent Diskus 100mcg (fluticasone propionate inhalation power)',
    'Flovent Diskus 250 mcg (fluticasone propionate inhalation power)',
    'Flovent Diskus 50mcg (fluticasone propionate inhalation power)',
    'Advair diskus 500/50 (fluticasone propionate/salmeterol)',
    'AirDuo RespiClick (fluticasone propionate/salmeterol)',
    'Advair diskus 100/50 (fluticasone/propionate/salmeterol)',
    'Advair diskus 250/50 (fluticasone/propionate/salmeterol)',
    'Lescol (fluvastatin)',
    'Lescol XL (fluvastatin)',
    'Fevarin (fluvoxamine)',
    'Dumyrox (fluvoxamine)',
    'Luvox (fluvoxamine maleate tablet)',
    'FA-8 (folic acid)',
    'Folacin-800 (folic acid)',
    'Antizol (fomepizole)',
    'Arixtra (fondaparinux)',
    'Perforomist (formoterol)',
    'Lexiva (fosamprenavir calcium)',
    'Monurol Powder (fosfomycin)',
    'Monopril (fosinopril)',
    'Cerebyx (fosphenytoin)',
    'Tavalisse (fostamatinib disodium hexahydrate)',
    'Rukobia (fostemsavir)',
    'Ajovy (fremanezumab-vfrm)',
    'Faslodex (fulvestrant)',
    'Lasix (furosemide tablet)',
    'Neurontin (gabapentin)',
    'Horizant (gabapentin enacarbil)',
    'Gralise (gabapentin kit)',
    'Razadyne (galantamine)',
    'Razadyne ER (galantamine)',
    'Razadyne IR (galantamine)',
    'Emgality injection (galcanezumab-gnlm)',
    'Naglazyme (galsulfase)',
    'Xyrem (gammahydroxybutyrate)',
    'Cytovene (ganciclovir)',
    'Cytovene IV (ganciclovir)',
    'Zirgan (ganciclovir ophthalmic gel)',
    'Iressa (gefitinib)',
    'Lopid (gemfibrozil)',
    'Mylotarg (gemtuzumab)',
    'Garamycin (gentamycin)',
    'Xospata (gilteritinib)',
    'Givlaari (givosiran)',
    'Daurismo (glasdegib sodium)',
    'Copaxone (glatiramer acetate)',
    'Glatopa (glatiramer acetate injection)',
    'Mavyret (glecaprevir/pibrentasvir)',
    'Amaryl (glimepiride)',
    'Glucotrol (glipizide)',
    'Glucotrol XL (glipizide extended release)',
    'Baqsimi (glucagon)',
    'Glucagon (glucagon)',
    'GlucaGen (glucagon)',
    'GlucaGen Hypokit (glucagon (rDNA) for injection)',
    'Gvoke PFS (glucagon injection)',
    'Glucerna 1.0 Cal (glucerna)',
    'Glucerna 1.2 Cal (Glucerna)',
    'Glucerna 1.5 Cal (glucerna)',
    'Glucerna Shake (Glucerna Shake)',
    'Glutarex-1 Powder (Glutarex-1 Powder)',
    'Glutarex-2 Powder (Glutarex-2 Powder)',
    'Micronase (glyburide tablet)',
    'Glucovance (glyburide/Metformin tablet)',
    'Ravicti Liquid (glycerol phenylbutyrate)',
    'Cuvposa (glycopyrrolate)',
    'Glycate (glycopyrrolate)',
    'Robinul (glycopyrrolate)',
    'Robinul Forte (glycopyrrolate)',
    'Bevespi Aerosphere (glycopyrrolate and formoterol fumarate)',
    'Glytrol (glytrol)',
    'Simponi ARIA Injection (golimumab)',
    'Vyondys 53 (golodirsen injection)',
    'Zoladex (goserelin acetate)',
    'Sustol (granisetron injection; extended release)',
    'Sancuso (Granisetron Transdermal System)',
    'Fulvicin PG (griseofulvin)',
    'Fulvicin-UF (griseofulvin)',
    'Grifulvin V (griseofulvin)',
    'Gris-PEG (griseofulvin)',
    'Wytensin (guanabenz acetate)',
    'Intuniv Extended Release Tablets (guanfacine)',
    'Tenex (guanfacine hydrochloride)',
    'Tremfya (guselkumab)',
    'Ultravate (halobetasol prop ointment, 0.05%)',
    'Bryhali lotion (halobetasol propionate)',
    'Duobrii (halobetasol propionate and tazarotene)',
    'Haldol Decanoate Injection (haloperidol)',
    'Haldol (haloperidol)',
    'Fluothane (halothane)',
    'Panhematin Injection (hemin)',
    'heparin (heparin)',
    'Vaqta (Hepatitis A vaccine, inactivated)',
    'HepaGam B (hepatitis B immune globulin i (human))',
    'Recombivax Hb (Hepatitis B vaccine (recombinant))',
    'Hymovis (high molecular weight viscoelastic hyaluronan)',
    'Supprelin LA (histrelin acetate; subcutaneous implant)',
    'Hycodan (homatropine, hydrocodone)',
    'Hydromet (homatropine, hydrocodone)',
    'Tussigon (homatropine, hydrocodone)',
    'Hominex-1 Powder (Hominex-1 Powder)',
    'Hominex-2 Powder (Hominex-2 Powder)',
    'Humalog Mix 75/25 (human insulin lispro (rDNA))',
    'Gardasil 9 (human papillomavirus 9valent recombinant)',
    'Orthovisc (hyaluronan)',
    'Hyalgan (hyaluronate sodium)',
    'Synvisc (hyaluronic acid derivatives)',
    'Durolane (hyaluronic acid injection)',
    'Apresoline (hydralazine hydrochloride)',
    'Aquazide H (hydrochlorothiazide)',
    'Hydrocot (hydrochlorothiazide)',
    'Zide (hydrochlorothiazide)',
    'Esidrix (hydrochlorothiazide)',
    'Hydrodiuril (hydrochlorothiazide)',
    'Microzide (hydrochlorothiazide capsule)',
    'Prinzide (hydrochlorothiazide-lisinopril)',
    'Zestoretic (hydrochlorothiazide-lisinopril)',
    'Hyzaar (hydrochlorothiazide-losartan potassium)',
    'Dyazide (hydrochlorothiazide-triamterine)',
    'Maxzide (hydrochlorothiazide-triamterine)',
    'Diovan HCT (hydrochlorothiazide-valsartan)',
    'Zohydro ER (hydrocodone bitartrate)',
    'SoluCortef (hydrocortisone)',
    'Proctocort suppositories (hydrocortisone acetate rectal suppositories, 30 mg)',
    'Locoid Lotion .1% (hydrocortisone butyrate)',
    'Anusol-HC (cream) (hydrocortisone cream)',
    'Ala-Cort (hydrocortisone cream)',
    'Ala-Scalp HP (hydrocortisone cream)',
    'Anusol HC (hydrocortisone cream)',
    'Aquanil HC (hydrocortisone cream)',
    'Beta HC (hydrocortisone cream)',
    'Caldecort (hydrocortisone cream)',
    'Cetacort (hydrocortisone cream)',
    'Cortaid (hydrocortisone cream)',
    'Corticaine (hydrocortisone cream)',
    'Corticool Maximum Strength (hydrocortisone cream)',
    'Cortizone (hydrocortisone cream)',
    'Cotacort (hydrocortisone cream)',
    'Delacort (hydrocortisone cream)',
    'Dermarest (hydrocortisone cream)',
    'Dermasorb HC Complete Kit (hydrocortisone cream)',
    'Dermtex-HC (hydrocortisone cream)',
    'Hydrozone Plus (hydrocortisone cream)',
    'Hytone (hydrocortisone cream)',
    'Instacort-10 (hydrocortisone cream)',
    'Ivy Soothe (hydrocortisone cream)',
    'IvyStat (hydrocortisone cream)',
    'Keratol HC (hydrocortisone cream)',
    'Kericort 10 (hydrocortisone cream)',
    'Lacticare-HC (hydrocortisone cream)',
    'Locoid (hydrocortisone cream)',
    'Locoid Lipocream (hydrocortisone cream)',
    'Medi-Cortisone Maximum Strength (hydrocortisone cream)',
    'Microcort (hydrocortisone cream)',
    'Mycin Scalp (hydrocortisone cream)',
    'Neutrogena TScalp (hydrocortisone cream)',
    'NuCort (hydrocortisone cream)',
    'Nupercainal HC (hydrocortisone cream)',
    'Nutracort (hydrocortisone cream)',
    'Pandel (hydrocortisone cream)',
    'Pediaderm HC Kit (hydrocortisone cream)',
    'Preparation H Hydrocortisone (hydrocortisone cream)',
    'Proctocream-HC (hydrocortisone cream)',
    'Recort Plus (hydrocortisone cream)',
    'Sarnol-HC Maximum Strength (hydrocortisone cream)',
    'Scalacort (hydrocortisone cream)',
    'Scalpcort (hydrocortisone cream)',
    'Summers Eve Specialcare (hydrocortisone cream)',
    'Texacort (hydrocortisone cream)',
    'Therasoft Anti-Itch Dermatitis (hydrocortisone cream)',
    'U-Cort (hydrocortisone cream)',
    'Westcort (hydrocortisone cream)',
    'Proctocort 1% cream (hydrocortisone cream USP, 1%)',
    'Cortef (hydrocortisone cypionate)',
    'Analpram HC Cream (hydrocortisone/pramoxine)',
    'Dilaudid (hydromorphone)',
    'Plaquenil (hydroxychloroquine tablet)',
    'Makena Injection (hydroxyprogesterone caproate)',
    'Lacrisert Ophthalmic insert (hydroxypropyl cellulose opthalmic insert)',
    'Droxia (hydroxyurea)',
    'Hydrea (hydroxyurea capsule)',
    'Atarax (hydroxyzine HCL tablet)',
    'Vistaril (hydroxyzine pamoate)',
    'Synvisc-One Injection (hylan G-F 20)',
    'Hylatopic Plus Cream (Hylatopic Plus Cream)',
    'Hylatopic Plus Foam (Hylatopic Plus Foam)',
    'Hylatopic Plus Lotion (Hylatopic Plus Lotion)',
    'Anaspaz (hyoscyamine)',
    'Cystospaz (hyoscyamine)',
    'Donnamar (hyoscyamine)',
    'Levsin (hyoscyamine)',
    'I-Valex-1 Powder (I-Valex-1 Powder)',
    'I-Valex-2 Powder (I-Valex-2 Powder)',
    'Trogarzo (ibalizumab-uiyk injection)',
    'Boniva (ibandronate)',
    'Zevalin (ibritumomab tiuxetan)',
    'Imbruvica (ibrutinib)',
    'Motrin IB (ibuprofen)',
    'NeoProfen Injection (ibuprofen lysine)',
    'Motrin (ibuprofen tablet)',
    'Advil (ibuprofen tablet)',
    'Tordol (ibuprofen, IV)',
    'Caldolor (ibuprofen, IV)',
    'NeoProfen (ibuprofen, IV)',
    'Duexis Tablet (ibuprofen/famotidine)',
    'Corvert (ibutilide fumarate)',
    'Firazyr Injection (icatibant)',
    'Idamycin (idarubicin hcl)',
    'Zydelig Tablet (idelalisib)',
    'Elaprase Solution (idsulfase)',
    'Ifex (ifosfamide)',
    'Ventavis (iloprost)',
    'Gleevec (imatinib mesylate)',
    'Cerezyme (imiglucerase)',
    'Recarbrio (imipenem cilastatin and relebactam injection)',
    'Tofranil (imipramine)',
    'Janimine (imipramine)',
    'Aldara (imiquimod)',
    'Zyclara (imiquimod)',
    'Relizorb (immobilized lipase cartridge)',
    'HyQvia Injectable (immune globulin infusion human with recombinant human hyaluronidase)',
    'Gammagard (immune globulin intravenous (human))',
    'Privigen vial 10% (immune globulin intravenous (human))',
    'Flebogamma DIF (immune globulin iv (human))',
    'Cuvitru (Immune Globulin Subcutaneous (Human))',
    'Hizentra vial 20% (immune globulin subcutaneous (human))',
    'Gamunex-C (immune globulin; intravenous)',
    'Gammaplex iv (immune globulin; intravenous iv)',
    'Impact Peptide 1.5 (impact peptide 1.5)',
    'Primaxin injection (impenem-cilastatin)',
    'Xeomin Injection (incobotulinumtoxinA)',
    'Lozol (indapamide tablet)',
    'Crixivan (indinavir sulfate)',
    'Uplizna (inebilizumab-cdon)',
    'Enfamil (infant formula)',
    'InFed (infed)',
    'Remicade (infliximab)',
    'Renflexis (infliximab-ABDA)',
    'Inflectra (infliximab-dyyb)',
    'Flumist Quadrivalent (Influenza Vaccine Live, Intranasal)',
    'Besponsa (inotuzumab ozogamicin)',
    'Novolin 70/30 Vials (insulin (rDNA))',
    'NovoLog (insulin aspart injection)',
    'NovoLog Mix 70/30 (insulin aspart injection)',
    'Fiasp (insulin aspart injection)',
    'Tresiba (insulin degludec injection)',
    'Levemir (insulin detemir (rDNA) injection)',
    'Lantus (insulin glargine)',
    'Lantus (SoloStar pen) (insulin glargine)',
    'Soliqua (insulin glargine)',
    'Toujeo (insulin glargine (rDNA origin) injection)',
    'Basaglar (insulin glargine injection)',
    'Apidra (insulin glulisine)',
    'Novolin R (Insulin Human)',
    'Humulin R (insulin human (rDNA origin))',
    'Admelog (insulin lispro injection)',
    'Humalog Injection (insulin lispro injection)',
    'Humalog KwikPen (insulin lispro injection)',
    'Humalog KwikPen Mix 50/50 (insulin lispro injection (rDNA))',
    'Humalog KwikPen Mix 75/25 (insulin lispro injection (rDNA))',
    'Lyumjev (insulin lispro-aabc injection)',
    'Prodigy Insulin Syringes (Insulin Syringes)',
    'Intron A (interferon alfa-2b)',
    'Avonex (interferon beta-1a)',
    'Rebif subcutaneous (interferon beta-1a)',
    'Betaseron (interferon beta-1b)',
    'Extavia (interferon beta-1b)',
    'Actimmune (interferon gamma-1b)',
    'Roferon-A (interferon-a)',
    'Yervoy (ipilimumab)',
    'Atrovent HFA Inhalation Aerosol (ipratropium bromide)',
    'Atrovent (Ipratropium bromide)',
    'Combivent Inhalation Aerosol (ipratropium bromide; albuterol sulfate)',
    'Avapro (irbesartan)',
    'Avalide (irbesartan-hydrochlorothiazide)',
    'Camptosar (irinotecan hcl)',
    'Onivyde injection (irinotecan liposome)',
    'Sarclisa (isatuximab-irfc)',
    'Cresemba Capsule (isavuconazonium sulfate)',
    'Cresemba Injection (isavuconazonium sulfate)',
    'Marplan (isocarboxazid)',
    'Nydrazid (isoniazid)',
    'Isoniazid/INH (isoniazid tablet)',
    'Humulin 70/30 (isophane human insulin (rDNA); human insulin (rDNA))',
    'Isuprel (isoproterenol hydrochloride)',
    'BiDil (isosorbide dinitrate and hydralazine hydrochloride)',
    'Imdur (isosorbide mononitrate)',
    'Ismo (isosorbide mononitrate (10mg,20mg))',
    'Monoket (isosorbide mononitrate (10mg,20mg))',
    'Absorica (isotretinoin capsule)',
    'Nourianz (istradefylline tablet)',
    'Sporanox Casules (itraconazole)',
    'Sporanox Oral Solution (itraconazole)',
    'Corlanor (ivabradine)',
    'Kalydeco (ivacaftor)',
    'Stromectol (Ivermectin)',
    'Tibsovo (ivosidenib tablet)',
    'Ixempra (ixabepilone)',
    'Ninlaro (ixazomib)',
    'Taltz (ixekizumab)',
    'Jevity 1 Cal (Jevity 1 Cal)',
    'Jevity 1.2 Cal (Jevity 1.2 Cal)',
    'Jevity 1.5 Cal (Jevity 1.5 Cal)',
    'Ketalar (ketamine)',
    'Toradol (keterolac)',
    'Acular (keterolac)',
    'Extina (ketoconazole)',
    'Ketodan Kit (ketoconazole)',
    'Kuric (ketoconazole)',
    'Nizoral (ketoconazole)',
    'Xolegel (ketoconazole)',
    'Ketonex-1 Powder (Ketonex-1 Powder)',
    'Ketonex-2 Powder (Ketonex-2 Powder)',
    'Acuvail (ketorolac tromethamine ophthalmic solution)',
    'Alaway OTC (ketotifen fumerate OTC solution)',
    'Trandate (labetalol HCL tablet)',
    'Normodyne (labetalol hydrochloride)',
    'Vimpat tablets (lacosamide)',
    'Kristalose oral solution (lactulose)',
    'Enulose (lactulose oral solution)',
    'Epivir (lamivudine)',
    'Epivir-HBV oral solution (lamivudine)',
    'Epivir-HBV tablets (lamivudine)',
    'Combivir tablets (lamivudine/ziovudine tablets)',
    'Lamictal (lamotrigine)',
    'Lamictal ODT (patient titration kits) (lamotrigine)',
    'Lamictal Starter Kits (lamotrigine)',
    'Lamictal XR (lamotrigine)',
    'LAMICTAL XR Patient Titration Kits (lamotrigine)',
    'Takhzyro injection (lanadelumab injection)',
    'Prodigy Twist Top Lancets 28G (lancets)',
    'Somatuline Depot Injection (lanreotide acetate)',
    'Prevacid SoluTab (lansoprazole)',
    'Prevacid (lansoprazole DR capsule)',
    'Fosrenol (lanthanum carbonate)',
    'Tykerb (lapatinib tablets)',
    'Aldurazyme (laronidase)',
    'Vitrakvi (larotrectinib)',
    'Reyvow (lasmiditan)',
    'Xalatan (latanoprost solution)',
    'Vyzulta (latanoprostene bunod ophthalmic solution)',
    'Harvoni tablet (ledipasvir/sofosbuvir)',
    'Dayvigo (lemborexant tablet)',
    'Revlimid (lenalidomide)',
    'Lenvima (lenvatinib)',
    'Prevymis (letermovir)',
    'Femara (letrozole)',
    'Eligard (leuprolide acetate)',
    'Fensolvi (leuprolide acetate)',
    'Lupron Depot (leuprolide acetate)',
    'Lupron Depot (ped) (leuprolide acetate for depot supspension)',
    'Lupaneta Pack Injection/Tablet (leuprolide acetate/norethindrone acetate)',
    'Xopenex (levalbuterol hcl)',
    'Keppra XR tablets (levetiracetam ER)',
    'Keppra (levetiracetam tablet)',
    'Xyzal tablets (levocetirizine dihydrochloride)',
    'Inbrija (levodopa inhalation powder)',
    'Levaquin (levofloxacin)',
    'Khapzory (levoleucovorin injection)',
    'Fetzima Extended Release Capsules (levomilnacipran)',
    'Liletta Intrauterine Contraceptive Device (levonorgestrel)',
    'Plan B (levonorgestrel)',
    'Kyleena (levonorgestrel-releasing intrauterine system)',
    'Mirena (levonorgestrel-releasing intrauterine system)',
    'Skyla (levonorgestrel-releasing intrauterine system)',
    'Levoxyl (levothyroxine)',
    'Synthroid (levothyroxine)',
    'Synthroid Tablets (levothyroxine sodium tablets, USP)',
    'Anestacon (lidocaine)',
    'Burnamycin (lidocaine)',
    'Burn-O-Jel (lidocaine)',
    'Lida Mantle (lidocaine)',
    'LidoRx (lidocaine)',
    'LMX 4 (lidocaine)',
    'LMX 5 (lidocaine)',
    'Senatec (lidocaine)',
    'Solarcaine Cool Aloe (lidocaine)',
    'Tropicaine (lidocaine)',
    'Lidocaine 2% viscous solution (lidocaine 2% viscous solution)',
    'Xylocaine (lidocaine hydrochloride)',
    'Lidoderm (lidocaine patch 5%)',
    'LMX Anesthetic Cream 4% (lidocaine topical)',
    'Xiidra (lifitegrast ophthalmic solution))',
    'Linzess Capsules (linaclotide)',
    'Tradjenta (linagliptin)',
    'Jentadueto XR (linagliptin and metformin hydrochloride extended-release)',
    'Jentadueto tablet (linagliptin/metformin HCI)',
    'Lincocin (lincomycin)',
    'Zyvox (linezolid)',
    'Cytomel (liothyronine sodium)',
    'Mastisol (liquid adhesive)',
    'Saxenda (liraglutide)',
    'Victoza injection (liraglutide (rDNA) injection)',
    'Vyvanse (lisdexamfetamine dimesylate capsules)',
    'Prinivil (lisinopril tablet)',
    'Zestril (lisinopril tablet)',
    'Eskalith (Lithium)',
    'Lithobid (Lithium)',
    'Adlyxin (lixisenatide)',
    'Alomide (lodoxamide tromethamine solution)',
    'Lucemyra (lofexidine tablet)',
    'Gleostine capsule (lomustine)',
    'Loperamide capsule (loperamide capsule)',
    'Kaletra tablets (lopinavir/ritonavir capsules)',
    'Kaletra oral solution (lopinavir/ritonavir oral solution)',
    'Lorabid (loracarbef)',
    'Claritin OTC (loratadine OTC tablet)',
    'Ativan (lorazepam tablet)',
    'Lorbrena (lorlatinib)',
    'Cozaar (losartan potassium)',
    'Zylet (loteprednol etabonate and tobramycin ophthalmic suspension)',
    'Lotemax Gel 0.5% (loteprednol etabonate ophthalmic)',
    'Alrex suspension .2% (loteprednol etabonate ophthalmic suspension)',
    'Altocor (lovastatin)',
    'Advicor (lovastatin and niacin)',
    'Mevacor (lovastatin tablet)',
    'Loxitane (loxapine)',
    'Loxapine capsule (loxapine capsule)',
    'Amitiza (lubiprostone)',
    'Luzu Cream (luliconazole)',
    'Orkambi (lumacaftor/ivacaftor)',
    'Caplyta (lumateperone)',
    'Latuda tablets (lurasidone HCI)',
    'Zepzelca (lurbinectedin injection)',
    'Reblozyl (luspatercept-aamt)',
    'Lutathera (lutetium Lu 177 dotatate)',
    'Atgam (lymphocyte immune globulin/anti-thymocyte globulin)',
    'Opsumit Tablet (macitentan)',
    'Mag-Ox (magnesium oxide tablet (OTC))',
    'Uro-Mag (magnesium sulfate)',
    'Osmitrol (mannitol)',
    'Ludiomil (maprotiline)',
    'Selzentry (maraviroc)',
    'M-M-R ll (measles, mumps, and rubella virus vaccine live)',
    'Emverm (mebendazole)',
    'Increlex Injection (mecasermin)',
    'Antivert (meclizine HCI)',
    'ABRA Abdominal (medical device)',
    'ABRA Surgical (medical device)',
    'Cytal Burn Matrix (medical device)',
    'Cytal Wound Matrix (medical device)',
    'Gentrix Hiatal (medical device)',
    'Gentrix Surgical Matrix (medical device)',
    'MicroMatrix (medical device)',
    'Xpansion (medical device)',
    'Pivot 1.5 cal Drink (medical drink)',
    'BCAD (medical food)',
    'Compleat Organic Blends (medical food)',
    'Compleat Pediatric Organic Blends (medical food)',
    'Compleat Pediatric Reduced Calorie (medical food)',
    'EleCare Jr. (medical food)',
    'Enfaport (medical food)',
    'GA (medical food)',
    'HCY (medical food)',
    'LMD (medical food)',
    'Modulen (medical food)',
    'Neocate (medical food)',
    'Novasource Renal (medical food)',
    'Nutramigen (medical food)',
    'Nutramigen with Enflora (medical food)',
    'OA (medical food)',
    'Phenyl-Free (medical food)',
    'Pregestimil (medical food)',
    'PurAmino (medical food)',
    'TYROS (medical food)',
    'WND (medical food)',
    'Depo-subQ Provera 104 (medroxyprogesterone acetate)',
    'Provera (medroxyprogesterone acetate)',
    'Depo Provera (medroxyprogesterone contraceptive injection)',
    'Mobic (meloxicam)',
    'Evomela (melphalan injection)',
    'Namenda XR capsule (memantine)',
    'Namenda (memantine hcl)',
    'Namzaric Capsules (memantine hydrochloride extended-_release and donepezil _hydrochloride)',
    'Trumenba (Meningococcal Group B Vaccine)',
    'Calmoseptine (menthol and zinc oxide)',
    'Gold Bond Medicated Body Powder (menthol and zinc oxide)',
    'Gold Star Medicated (menthol and zinc oxide)',
    'Risamine (menthol and zinc oxide)',
    'Carbocaine (mepivacaine)',
    'Polocaine (mepivacaine)',
    'Nucala (mepolizumab)',
    'Demerol (merperidine)',
    'Canasa (mesalamine)',
    'Delzicol DR Capsules (mesalamine)',
    'Lialda (mesalamine)',
    'Pentasa (mesalamine)',
    'Apriso (mesalamine extended release)',
    'Serentil (mesoridazine)',
    'Skelaxin (metaxalone)',
    'Glucophage (metformin)',
    'Glucophage XR (metformin hcl, extended release)',
    'Janumet (Metformin Hydrochloride; Sitagliptin Phosphate)',
    'Provocholine (methacholine)',
    'Desoxyn tablet (methamphetamine hydrochloride)',
    'Tapazole (methimazole tablets)',
    'Robaxin (methocarbamol tablet)',
    'Brevital (methohexital)',
    'Otrexup Injection (methotrexate)',
    'Trexall (methotrexate)',
    'Rheumatrex Dose pack (methotrexate)',
    'Rasuvo injection (methotrexate injection)',
    'Oxsoralen-Ultra (methoxsalen USP)',
    'Celontin (methsuximide)',
    'Aldochlor (methyldopa and chlorothiazide)',
    'Aldoril (methyldopa and hydrochlorothiazide)',
    'Urolene Blue (methylene blue)',
    'Relistor injection (methylnaltrexone bromide)',
    'Relistor tablets (methylnaltrexone bromide)',
    'Metadate CD (methylphenidate CD capsule)',
    'Ritalin LA (methylphenidate hcl)',
    'Ritalin (methylphenidate tablet)',
    'Medrol (methylprednisolone)',
    'SoluMedrol (methylprednisolone)',
    'Concerta (methyphenidate HCI)',
    'Reglan (metoclopramide HCL tablet)',
    'Mykrox (metolazone)',
    'Zaroxolyn (metolazone tablet)',
    'Toprol XL (metoprolol)',
    'Dutoprol Tablet (metoprolol succinate/hctz)',
    'Lopressor (metoprolol tartrate tablet)',
    'Flagyl (metronidazole)',
    'Noritate Cream (metronidazole)',
    'Demser capsules (metyrosine)',
    'Mevastatin (mevastatin)',
    'Mycamine injection (micafungin sodium)',
    'Glynase PresTab (micronized glyburide)',
    'Nayzilam (midazolam)',
    'Versed (midazolam)',
    'Orvaten (midodrine)',
    'Proamatine (midodrine)',
    'Rydapt (midostaurin capsule)',
    'Korlym tablets (mifepristone)',
    'Glyset (miglitol)',
    'Savella (milnacipran HCl tablets)',
    'Arestin (minocycline)',
    'Minocin (minocycline capsule)',
    'Solodyn (minocycline HCI)',
    'Dynacin (minocycline HCL capsule)',
    'Myrbetriq (mirabegron)',
    'Remeron (mirtazapine tablet)',
    'Cytotec (misoprostol)',
    'Jelmyto (mitomycin)',
    'Mydayis (mixed salts of a single-entity amphetamine product)',
    'Provigil (modafinil)',
    'Univasc (moexipril)',
    'Uniretic (moexipril and hydrochlorotiazide)',
    'Poteligeo (mogamulizumab-KPKC)',
    'Moban (molindone)',
    'Asmanex HFA (mometasone furoate)',
    'Nasonex (mometasone furoate)',
    'Elocon Cream (mometasone furoate)',
    'Elocon Ointment (mometasone furoate)',
    'Asmanex Twisthaler (mometasone furoate inhalation powder)',
    'Dulera Inhalation Aerosol (mometasone furoate/formoterol fumarate dihydrate)',
    'Singulair 4mg Oral Granules (montelukast sodium)',
    'Singulair (montelukast sodium)',
    'Avinza (morphine)',
    'Kadian (morphine)',
    'Morphabond (morphine)',
    'MS Contin (morphine)',
    'Oramorph SR (morphine)',
    'Roxanol (morphine)',
    'Roxanol-T (morphine)',
    'Embeda (morphine sulfate and naltrexone hydrochloride)',
    'Lumoxiti (moxetumomab pasudotox)',
    'Vigamox (moxifloxacin hydrochloride solution)',
    'Bactroban (mupirocin)',
    'Centany (mupirocin)',
    'CellCept (mycophenolate mofetil)',
    'Myfortic (mycophenolic acid)',
    'Acys-5 (N-acetylcysteine)',
    'Cetylev (N-acetylcysteine)',
    'Relafen (nabumetone tablet)',
    'Corgard (nadolol)',
    'Synarel (nafarelin acetate)',
    'Nubain (nalbuphine)',
    'Selincro (nalmefene)',
    'Movantik (naloxegol oxalate)',
    'Narcan (naloxone)',
    'Carimune NF (nanofiltered immune globulin intravenous (human))',
    'Vimovo (naproxen and esomeprazole magnesium)',
    'Aleve (naproxen sodium)',
    'Anaprox (naproxen sodium)',
    'Anaprox DS (naproxen sodium tablet)',
    'Naprosyn (naproxen tablet)',
    'Tysabri Vial (natalizumab)',
    'Bystolic (nebivolol)',
    'Portrazza (necitumumab)',
    'Tilade (nedocromil sodium)',
    'Arranon (nelarabine)',
    'Viracept (nelfinavir mesylate)',
    'Neo-Fradin (neomycin)',
    'Prostigmine Bromide (neostigmine)',
    'Ilevro (nepafenac suspension)',
    'Nevanac (nepafenac suspension)',
    'Nepro with Carb Steady (Nepro)',
    'Nerlynx (neratinib maleate)',
    'Akynzeo capsule (netupitant/palonosetron capsule)',
    'Viramune XR (nevirapine)',
    'Viramune (nevirapine)',
    'Niacin (niacin)',
    'Niaspan ER (niacin extented-release tablets)',
    'Niacin SA capsule (OTC) (niacin SA capsule (OTC))',
    'Nicotrol (nicotine)',
    'Procardia (nifedipine)',
    'Adalat (nifedipine)',
    'Nifedipine capsule (nifedipine capsule)',
    'Adalat cc (nifedipine CR tablet)',
    'Procardia XL (nifedipine extended release)',
    'Tasigna (nilotinib)',
    'Nilandron tablet (nilutamide)',
    'Nimotop (nimodipine)',
    'Ofev Capsule (nintedanib)',
    'Zejula (niraparib)',
    'Sular (nisoldipine)',
    'Orfadin (nitisinone)',
    'Nityr (nitisinone tablet)',
    'Furadantin (nitrofurantoin)',
    'Macrodantin (nitrofurantoin)',
    'Nitrostat (nitroglycerin)',
    'Rectiv ointment (nitroglycerin)',
    'Nitroglycerin SA capsule (nitroglycerin SA capsule)',
    'Nipride (nitroprusside)',
    'Opdivo Injection (nivolumab)',
    'Opdivo Yervoy (nivolumab ipilimumab)',
    'Axid (nizatidine)',
    'Atopiclair Cream (nonsteroidal cream)',
    'Levophed (norepinephrine)',
    'Aygestin (norethindrone acetate tablet)',
    'Ortho Micronor (norethindrone tablet)',
    'Ovcon 35 (norethindrone/ethinyl estradiol tablet)',
    'Aventyl (nortriptyline)',
    'Pamelor (nortriptyline HCL capsule)',
    'Humulin N Injection (NPH human insulin (rDNA))',
    'Spinraza (nusinersen injection)',
    'Nutren 1.0 with Fiber (nutren 1.0 with fiber)',
    'Nutren 1.5 (nutren 1.5)',
    'Nutren Junior (nutren junior)',
    'Nutren Junior Fiber (nutren junior fiber)',
    'Alfamino Infant (nutrition supplement)',
    '3232 A (nutritional supplement)',
    'Alfamino Junior (nutritional supplement)',
    'Boost Kid Essentials (nutritional supplement)',
    'Boost Kid Essentials 1.5 (nutritional supplement)',
    'Boost Kid Essentials 1.5 Fiber (nutritional supplement)',
    'Boost Original (nutritional supplement)',
    'Boost Plus (nutritional supplement)',
    'Boost VHC (nutritional supplement)',
    'Hi-Cal Drink (nutritional supplement)',
    'Peptamen Junior 1.5 (nutritional supplement)',
    'PFD (nutritional supplement)',
    'Portagen (nutritional supplement)',
    'Nystatin powder (nyamyc topical powder)',
    'Mycostatin (nystatin topical)',
    'Nystop (nystatin topical)',
    'Pedi-Dri (nystatin topical)',
    'Ocaliva (obeticholic acid tablet)',
    'Gazyva (obinutuzumab)',
    'Ocrevus (ocrelizumab)',
    'Mycapssa capsule (octreotide)',
    'Sandostatin (octreotide)',
    'Sandostatin LAR Depot (octreotide acetate)',
    'Arzerra (ofatumumab)',
    'Zyprexa (olanzapine)',
    'Zyprexa Relprevv (olanzapine)',
    'Zyprexa Zydis (olanzapine)',
    'Lynparza (olaparib)',
    'Lynparza Capsule (olaparib)',
    'Striverdi Respimat Spray (olodaterol)',
    'Pazeo (olopatadine hydrochloride solution)',
    'Synribo (omacetaxine mepesuccinate)',
    'Xolair (omalizumab)',
    'Lovaza (omega-3-acid ethyl esters)',
    'Prilosec (omeprazole capsule)',
    'Zofran ODT (ondansetron ODT tablet)',
    'Zofran (ondansetron tablet)',
    'Orbactiv (oritavancin)',
    'Alli (orlistat)',
    'Xenical (orlistat)',
    'Tamiflu (oseltamivir phosphate)',
    'Isturisa tablet (osilodrostat)',
    'Tagrisso (osimertinib)',
    'Osmolite 1 Cal (Osmolite 1 Cal)',
    'Osmolite 1.2 Cal (Osmolite 1.2 Cal)',
    'Osmolite 1.5 Cal (Osmolite 1.5 Cal)',
    'Oxandrin (oxandrolone tablet)',
    'Daypro (oxaprozin)',
    'Serax (oxazepam)',
    'Oxtellar XR Tablet (oxcarbazepine)',
    'Trileptal (oxcarbazepine)',
    'Ditropan XL (oxybutynin)',
    'Oxytrol (oxybutynin)',
    'Gelnique (oxybutynin chloride)',
    'Ditropan (oxybutynin tablet)',
    'Dazidox (oxycodone)',
    'Eth-Oxydose (oxycodone)',
    'Oxaydo (oxycodone)',
    'Oxycontin (oxycodone)',
    'Oxydose (oxycodone)',
    'Oxyfast (oxycodone)',
    'Oxy IR (oxycodone)',
    'Roxicodone (oxycodone)',
    'Roxicodone Intensol (oxycodone)',
    'Pitocin (oxytocin)',
    'Zeposia (ozanimod capsule)',
    'Ibrance (palbociclib)',
    'Kepivance (palifermin)',
    'Invega Sustenna (paliperidone palmitate)',
    'Invega Trinza (paliperidone palmitate)',
    'Synagis (palivizumab)',
    'Aredia (pamidronate)',
    'Creon Delayed-Release capsules (pancrelipase)',
    'Pancreaze Delayed-Release Capsules (pancrelipase)',
    'Vectibix (panitumumab)',
    'Farydak Capsule (panobinostat)',
    'Protonix (pantoprazole sodium)',
    'Pexeva (paroxetine)',
    'Paxil (paroxetine HCL tablet)',
    'Veltassa (patiromer)',
    'Onpattro (patisiran)',
    'Votrient (pazopanib)',
    'PediaSure (PediaSure)',
    'PediaSure 1.5 cal (pediasure 1.5 cal)',
    'PediaSure Enteral 1.0 Cal (PediaSure Enteral 1.0 Cal)',
    'PediaSure Enteral Formula with Fiber (PediaSure Enteral Formula with Fiber)',
    'PediaSure Harvest (pediasure harvest)',
    'PediaSure Peptide 1.0 cal (PediaSure Peptide 1.0 cal)',
    'PediaSure Peptide 1.5 cal (PediaSure Peptide 1.5 cal)',
    'PediaSure with Fiber (PediaSure with Fiber)',
    'Macugen injection (pegaptanb sodium)',
    'Neulasta (pegfilgrastim)',
    'Neulasta Onpro (pegfilgrastim)',
    'Ziextenzo (pegfilgrastim-bmez)',
    'Udenyca (pegfilgrastim-cbqv)',
    'Fulphila (pegfilgrastim-jmdb)',
    'Plegridy Injection (peginterferon beta1a)',
    'Krystexxa IV (pegloticase)',
    'Palynziq (pegvaliase-pqpz)',
    'Somavert (pegvisomant)',
    'Keytruda (pembrolizumab)',
    'Alimta (pemetrexed)',
    'Pemazyre (pemigatinib)',
    'Cuprimine capsules (penicillamine)',
    'Pfizerpen (penicillin G potassium)',
    'Amoxil (penicillin)',
    'Bactocil (penicillin)',
    'Bicillin L-A (penicillin)',
    'Cloxapen (penicillin)',
    'Crysticillin (penicillin)',
    'Dynapen (penicillin)',
    'Geocillin (penicillin)',
    'Nafcil (penicillin)',
    'Pipracil (penicillin)',
    'Staphcillin (penicillin)',
    'Ticar (penicillin)',
    'Veetids (penicillin)',
    'Elmiron (pentosan polysulfate sodium)',
    'Trental (pentoxifylline ER tablet)',
    'Peptamen (peptamen)',
    'Peptamen 1.5 (peptamen 1.5)',
    'Peptamen Junior (peptamen junior)',
    'Peptamen Junior Fiber (peptamen junior fiber)',
    'Peptamen Junior PreBio (peptamen junior prebio)',
    'Peptamen PreBio (peptamen prebio)',
    'Fycompa Tablet (perampanel)',
    'Perative (Perative)',
    'Aceon (perindopril)',
    'Trilafon (perphenazine tablet)',
    'PERJETA (pertuzumab)',
    'Turalio capsule (pexidartinib)',
    'Nardil (phenelzine sulfate)',
    'Phenex-1 Powder (Phenex-1 Powder)',
    'Phenex-2 Powder (Phenex-2 Powder)',
    'Luminal (phenobarbital)',
    'Donnatal Elixir (Phenobarbital, Hyoscyamine Sulfate, Atropine Sulfate, Scopolamine Hydrobromide)',
    'Dibenzyline capsule (phenoxybenzamine)',
    'OraVerse (phentolamine)',
    'Regitine (phentolamine)',
    'Neo-Synephrine (phenylephrine)',
    'Nostril (phenylephrine)',
    'Pretz-D (phenylephrine)',
    'Rhinall (phenylephrine)',
    'Tur-Bi-Cal (phenylephrine)',
    'Vicks Sinex (phenylephrine)',
    'Omidria solution (phenylephrine/ketorolac tromethamine solution)',
    'Phenytek (phenytoin)',
    'Dilantin (phenytoin sodium capsule)',
    'Eserine (physostigmine (opththalmic route))',
    'Isopto Eserine (physostigmine (opththalmic route))',
    'Mephyton tablets (phytonadione)',
    'Salagen Tablet (pilocarpine)',
    'Isopto Carpine (pilocarpine (ophthalmic route))',
    'Ocu-Carpine (pilocarpine (ophthalmic route))',
    'Ocusert Pilo (pilocarpine (ophthalmic route))',
    'Pilocar (pilocarpine (ophthalmic route))',
    'Pilopine-HS (pilocarpine (ophthalmic route))',
    'Nuplazid (pimavanserin)',
    'Elidel (pimecrolimus)',
    'ORAP (tablets) (pimozide)',
    'Visken (pindolol)',
    'Actos (pioglitazone hydrochloride)',
    'Esbriet (pirfenidone)',
    'Feldene (piroxicam)',
    'Livalo (pitavastatin)',
    'Pitava (pitavastatin)',
    'Trulance (plecanatide)',
    'Mozobil (plerixafor injection)',
    'Prevnar 13 (pneumococcal 13-valent conjugate vaccine [Diphtheria CRM197 Protein])',
    'Pneumovax 23 (pneumococcal vaccine polyvalent)',
    'PNV Prenatal Multivitamin Plus Iron (PNV Prenatal Multivitamin Plus Iron)',
    'Polivy (polatuzumab vedotin-piiq)',
    'Gliadel Wafer (polifeprosan 20 with carmustine implant)',
    'Miralax (polyethylene glycol 3350, powder)',
    'Plenvu (polyethylene glycol 3350, sodium ascorbate, sodium sulfate, ascorbic acid, sodium chloride and potassium chloride)',
    'MoviPrep (polyethylene glycol 3350, sodium sulfate, sodium chloride, potassium chloride, sodium ascorbate, and ascorbic acid for oral solution)',
    'Poly-Rx (Polymyxin B)',
    'Menactra (Polysaccharide Diphtheria Toxoid Conjugate Vaccine)',
    'Pomalyst capsule (pomalidomide)',
    'Iclusig (ponatinib)',
    'Noxafil (posaconazole)',
    'Klor-Con 8mEQ (potassium chloride ER tablet)',
    'Klor-Con M10 (potassium chloride ER tablet)',
    'K-Dur 20MEQ (potassium chloride ER tablet)',
    'Klor-Con 10mEQ (potassium chloride ER tablet)',
    'Klor-Con M20 (potassium chloride ER tablet)',
    'Cytra-K (potassium citrate)',
    'SSKI oral solution (potassium Iodide)',
    'Folotyn (pralatrexate injection)',
    'Protopam Chloride (pralidoxime)',
    'Mirapex (pramipexole dihydrochloride tablet )',
    'Mirapex ER (pramipexole dihydrochloride tablet, extended release)',
    'Mirapex tablets (pramipexole dihydrochloride tablets)',
    'Symlin (pramlintide acetate)',
    'Selektine (pravastatin)',
    'Pravachol (pravastatin tablet)',
    'Biltricide (praziquantel)',
    'Minizide (prazosin and polythiazide)',
    'prazosin capsule (prazosin capsule)',
    'Minipress (prazosin hydrochloride)',
    'Bubbli-Pred (prednisolone)',
    'Cotolone (prednisolone)',
    'Flo-Pred (prednisolone)',
    'Millipred (prednisolone)',
    'Orapred (prednisolone)',
    'Pediapred (prednisolone)',
    'Prelone (prednisolone)',
    'Veripred 20 (prednisolone)',
    'Pred Forte Ophthalmic Suspension 1.0% (prednisolone acetate)',
    'Rayos Tablet, Extended Release (prednisone)',
    'Deltasone (prednisone tablet)',
    'Prednicot (prednisone tablet)',
    'Prednisone Intensol (prednisone tablet)',
    'Sterapred (prednisone tablet)',
    'Lyrica (pregabalin)',
    'Lyrica CR (pregabalin)',
    'Enfamom (prenatal supplement)',
    'Primaquine (primaquine)',
    'Mysoline (primidone)',
    'Benemid (probenecid)',
    'Probalan (probenecid)',
    'Pronestyl (procainamide)',
    'Procanbid (procainamide HCI extended-release tablets)',
    'Matulane (procarbazine)',
    'Compazine (prochlorperazine tablet)',
    'Kemadrin (procyclidine HCL)',
    'Progesterone capsule (progesterone capsule)',
    'Crinone (progesterone gel)',
    'Phenergan (Promethazine Hydrochloride)',
    'Promacot (Promethazine Hydrochloride)',
    'Promote (Promote)',
    'Promote with Fiber (Promote with Fiber)',
    'Rythmol SR (propafenone hydrochloride)',
    'Rythmol (propafenone hydrochloride)',
    'Hemangeol (propranolol)',
    'Inderal XL (propranolol)',
    'InnoPran XL (propranolol)',
    'Propranolol HCl Intensol (propranolol)',
    'Propimex-1 Powder (Propimex-1 Powder)',
    'Propimex-2 Powder (Propimex-2 Powder)',
    'Diprivan (propofol)',
    'Inderide (propranolol and hydrochlorothiazide)',
    'Inderal LA Capsules (propranolol HCL ER)',
    'Inderal (propranolol tablet)',
    'Propacil (propylthiouracil tablet)',
    'Protamine (protamine sulfate)',
    'Vivactil (protriptyline)',
    'ProViMin Powder (ProViMin Powder)',
    'Motegrity (prucalopride)',
    'Pulmocare (Pulmocare)',
    'Zinamide (pyrazinamide)',
    'Mestinon (pyridostigmine bromide)',
    'Vitamin B-6 (pyridoxine)',
    'Aminoxin (pyridoxine)',
    'Pyri-500 (pyridoxine)',
    'Rodex (pyridoxine)',
    'Vitabee 6 (pyridoxine)',
    'Daraprim tablet (pyrimethamine)',
    'Seroquel (quetiapine fumarate)',
    'Accupril (quinapril HCI)',
    'Accuretic (quinapril/HCTZ tablet)',
    'Cardioquin (quinidine)',
    'Quinaglute (quinidine)',
    'Quinalan (quinidine)',
    'Quinidex Extentabs (quinidine)',
    'Qualaquin (quinine)',
    'Quinamm (quinine)',
    'Quiphile (quinine)',
    'Aciphex (rabeprazole sodium)',
    'Imogam (rabies immune globulin)',
    'Imovax (rabies vaccine)',
    'Xofigo injection (radium Ra 223 dichloride)',
    'Evista (raloxifene tablet)',
    'Isentress (raltegravir)',
    'Isentress HD tablet (raltegravir)',
    'Rozerem (ramelteon)',
    'Altace (ramipril)',
    'Cyramza (ramucirumab injection)',
    'Lucentis (ranibizumab injection)',
    'Zantac (Ranitidine)',
    'Ranexa (ranolazine extended-release tablets)',
    'Azilect (rasagiline tablets)',
    'Elitek (rasburicase)',
    'Ultomiris (ravulizumab-cwvz injection; iv)',
    'RCF (Ross Carbohydrate Free) (RCF (Ross Carbohydrate Free))',
    'BeneFIX injection (recombinant)',
    'Recombinate rAHF (recominant)',
    'Lexiscan (regadenoson injection)',
    'Stivarga (regorafenib)',
    'Humulin R Injection (Regular human insulin (rDNA))',
    'Humulin R U-500 Injection; Concentrated (regular insulin human [rDNA Origin])',
    'Novolin R Vials (regular, human insulin injection (rDNA))',
    'Prandin (repaglinide tablet)',
    'Acthar Gel (repository corticotropin injection)',
    'Cinqair (reslizumab)',
    'Kisqali (ribociclib)',
    'Kisqali Femara Co-Pack tablets (ribociclib and letrozole)',
    'Mycobutin (rifabutin)',
    'Rifadin (rifampin)',
    'Rimactane (rifampin)',
    'Priftin (rifapentine tablets)',
    'Xifaxan (rifaximin)',
    'Edurant (rilpivirne)',
    'Myobloc Injection (rimabotulinumtoxinB)',
    'Nurtec ODT (rimegepant)',
    'Adempas Tablet (riociguat)',
    'Qinlock (ripretinib tablet)',
    'Skyrizi (risankizumab-rzaa injectable)',
    'Actonel (risedronate sodium tablet)',
    'Risperdal Consta (risperidone)',
    'Risperdal (risperidone)',
    'Norvir (ritonavir)',
    'Norvir oral solution (ritonavir oral solution)',
    'Norvir Soft Gelatin Capsules (ritonavir soft gelatin capsules)',
    'Norvir Tablets (ritonavir tablets)',
    'Rituxan (rituximab)',
    'Truxima (rituximab-abbs)',
    'Ruxience (rituximab-pvvr)',
    'Rituxan Hycela (rituximab/hyaluronidase human)',
    'Xarelto (rivaroxaban tablets)',
    'Exelon (rivastigmine tartrate capsule)',
    'Maxalt (rizatriptan benzoate)',
    'Maxalt-MLT (rizatriptan benzoate)',
    'Zemuron (rocuronium)',
    'Daliresp (roflumilast)',
    'Varubi tablet (rolapitant tablet)',
    'Istodax injection (romidepsin)',
    'Nplate (romiplostim)',
    'Evenity (romosozumab)',
    'Requip tablets (ropinirole hydrochloride)',
    'Requip XL (ropinirole hydrochloride tablet, film coated, extended release)',
    'Requip (ropinirole tablet, film coated)',
    'Naropin (ropivicaine)',
    'Avandia tablets (rosiglitazone maleate)',
    'Crestor (rosuvastatin calcium)',
    'Neupro Transdermal System (rotigotine)',
    'Rubraca (rucaparib)',
    'Banzel (rufinamide)',
    'Jakafi Tablet (ruxolitinib)',
    'Trodelvy injection (sacituzumab govitecan-hziy injection)',
    'Sucraid Oral Solution (sacrosidase)',
    'Entresto (sacubitril/valsartan)',
    'Albuterol (salbutamol)',
    'Serevent   (salmeterol)',
    'Serevent Diskus (Inhalation Powder) (salmeterol xinafoate)',
    'Kuvan (sapropterin dihydrochloride)',
    'Leukine (sargramostim)',
    'Kevzara (sarilumab)',
    'Onglyza (saxagliptin)',
    'Kombiglyze XR (saxagliptin/metformin hcl extended-release)',
    'Transderm Scop (scopolamine)',
    'Kanuma (sebelipase alfa)',
    'Solosec (secnidazole)',
    'Cosentyx (secukinumab)',
    'Emsam (selegiline)',
    'Zelapar (selegiline HCI)',
    'Uptravi (selexipag)',
    'Retevmo (selpercatinib)',
    'Koselugo (selumetinib)',
    'Ozempic (semaglutide)',
    'Senna (senna glycoside)',
    'Zoloft (sertraline HCI)',
    'Revatio (sildenafil citrate tablet)',
    'Viagra (sildenefil citrate)',
    'Rapaflo (silodosin)',
    'Silsoft Contact Lenses (Silsoft Contact Lenses)',
    'Sylvant (siltuximab)',
    'Lipex (simvastatin)',
    'Zocor (simvastatin tablets)',
    'Mayzent (siponimod)',
    'Provenge (sipuleucel-t)',
    'Rapamune (sirolimus)',
    'Januvia (sitagliptin phosphate)',
    'Alka-Seltzer (sodium bicarbonate)',
    'Monovisc (sodium hyaluronate)',
    'Supartz (sodium hyaluronate)',
    'Buphenyl Powder (sodium phenylbutyrate)',
    'Buphenyl Tablet (sodium phenylbutyrate)',
    'Depacon (sodium valproate)',
    'Lokelma (sodium zirconium cyclosilicate)',
    'Sovaldi Tablet (sofosbuvir)',
    'Vosevi (sofosbuvir, velpatasvir, and voxilaprevir)',
    'Epclusa (sofosbuvir/velpatasvir tablet)',
    'Vesicare (solifenacin)',
    'Sunosi (solriamfetol tablet)',
    'Genotropin (somatropin)',
    'Serostim (somatropin)',
    'Norditropin FlexPro Injection (somatropin (rDNA origin))',
    'Zomacton (somatropin (rDNA origin) injection)',
    'Nutropin AQ (somatropin (rDNA) injection)',
    'Omnitrope (somatropin [rDNA origin] for injection)',
    'Odomzo (sonidegib)',
    'Nexavar (sorafenib)',
    'Betapace (sotalol)',
    'Aldactone (spironolactone)',
    'Aldactazide (spironolactone and hydrochlorothiazide)',
    'Ortho-Cyclen (sprintec tablet)',
    'Potassium Iodide (SSKI oral solution)',
    "St. John's wort (St. John's wort)",
    'Depo-Medrol (sterile methylprednisolone acetate)',
    'Tobradex ointment (steriod and antibiotic ointment)',
    'Chemet Capsules (succimer)',
    'Anectine (succinylcholine)',
    'Carafate (sucralfate)',
    'Velphoro Chewable Tablets (sucroferric oxyhydroxide)',
    'Bactrim DS (sulfamethoxazole/trimethoprim DS tablet)',
    'Septra DS (sulfamethoxazole/trimethoprim DS tablet)',
    'Azulfidine (sulfasalazine)',
    'Azulfidine EN-Tabs (sulfasalazine, USP)',
    'Imitrex (Nasal Spray) (sumatriptan succinate)',
    'Imitrex (Tablets) (sumatriptan succinate)',
    'Sutent (sunitinib malate)',
    'Suplena (suplena)',
    'Belsomra (suvorexant)',
    'Prograf (tacrolimus capsule)',
    'Envarsus XR (tacrolimus extended-release tablets)',
    'Adcirca tablets (tadalafil)',
    'Cialis (tadalafil)',
    'Vyndamax (tafamidis)',
    'Vyndaqel (tafamidis meglumine)',
    'Elzonris (tagraxofusp-erzs injection)',
    'Talzenna (talazoparib)',
    'Tasmar tablets (talcapone)',
    'Elelyso (taliglucerase alfa powder)',
    'Imlygic (talimogene laherparepvec)',
    'Nolvadex (tamoxifen)',
    'Soltamox (tamoxifen)',
    'Flomax (tamsulosin hydrochloride)',
    'Hetlioz (tasimelteon capsule)',
    'Tazverik (tazemetostat tablet)',
    'Granix Injection (tbo-filgrastim)',
    'Sivextro Tablet (tedixolid phosphate)',
    'Gattex Injectable (teduglutide)',
    'Micardis (telmisartan)',
    'Xermelo (telotristat ethyl)',
    'Restoril (temazepam)',
    'Torisel (temsirolimus)',
    'Vemlidy (tenofovir alafenamide)',
    'Truvada (tenofovir disoproxil / emtricitabine)',
    'Tepezza (teprotumumab-trbw)',
    'Hytrin (terazosin capsule)',
    'Brethine (terbutaline)',
    'Aubagio tablets (teriflunomide)',
    'Forteo (teriparatide)',
    'Egrifta SV (tesamorelin for injection)',
    'Depo-Testosterone (testosterone cypionate)',
    'AndroGel (testosterone gel)',
    'Vogelxo gel packet (testosterone gel packet)',
    'Vogelxo gel pump (testosterone gel pump)',
    'Vogelxo gel tube (testosterone gel tube)',
    'Tenivac (tetanus and diptheria toxoids absorbed)',
    'Adacel (tetanus toxoid, reduced diphtheria toxoid and acellular pertussis vaccine)',
    'Xenazine Tablets (tetrabenazine)',
    'Tetrix Cream (tetrix)',
    'Symdeko tablet (tezacaftor/ivacaftor)',
    'Thalomid (thalidomide)',
    'Quibron T (theophylline)',
    'Quibron T/SR (theophylline)',
    'Quibron (theophylline;guaifenesin)',
    'Mellaril (thioridazine)',
    'Navane (thiothixene)',
    'Armour Thyroid (thyroid)',
    'Thyrogen injection (thyrotropin alfa)',
    'Gabitril (tiagabine HCI)',
    'Brilinta Tablets (ticagrelor)',
    'Timentin (ticarcillin-clavulanate)',
    'Timentin Novaplus (ticarcillin-clavulanate)',
    'Ticlid (ticlopidine)',
    'Tygacil (tigecycline)',
    'Ilumya (tildrakizumab-asmn)',
    'Betimol (timolol)',
    'Istalol (timolol)',
    'Timoptic Ocumeter (timolol)',
    'Timoptic-XE Ocumeter (timolol)',
    'Blocadren (timolol)',
    'Timolide (timolol and hydrochlorothiazide)',
    'Timoptic in Occudose (timolol maleate opthalmic solution (.5%,.25%))',
    'Innohep (tinzaparin)',
    'Thiola (tiopromin tablet)',
    'Spiriva (tiotropium bromide)',
    'Spiriva Respimat Spray (tiotropium bromide)',
    'Stiolto Respimat (tiotropium bromide and olodaterol)',
    'Spiriva HandiHaler (tiotropium bromide inhalation powder)',
    'Aptivus capsules (tipranavir)',
    'Zanaflex (Tizanidine 4mg tab)',
    'Bethkis Inhalation Solution (tobramycin)',
    'Actemra (tocilizumab)',
    'Xeljanz tablet (tofacitinib citrate)',
    'Xeljanz XR (tofacitnib)',
    'Tolerex (tolerex)',
    'Detrol LA (tolterodine tartrate)',
    'Detrol (tolterodine tartrate tablet)',
    'Jynarque (tolvaptan)',
    'Samsca Tablets 15mg, 30mg (tolvaptan)',
    'Trokendi XR Capsule (topiramate)',
    'Topamax tablets (topiramate)',
    'Qudexy XR capsule (topiramate ER)',
    'Hycamtin (topotecan)',
    'Hycamtin injection (topotecan HCl)',
    'Demadex (torsemide)',
    'Yondelis (trabectedin)',
    'Ultracet (tramadol hydrochloride/acetaminophen tablets)',
    'Ultram (tramadol tablet)',
    'Mekinist (trametinib)',
    'Tarka (trandolapril and verapamil)',
    'Mavik (trandolapril tablet)',
    'Cyklokapron (tranexamic acid)',
    'Parnate 10mg tablets (tranylcypromine)',
    'Parnate   (tranylcypromine)',
    'Herceptin (trastuzumab)',
    'Kanjiniti (trastuzumab-anns)',
    'Ogivri (trastuzumab-dkst injection)',
    'Herzuma (trastuzumab-pkrb)',
    'Trazimera (trastuzumab-qyyp)',
    'Travatan Z (travoprost solution)',
    'Desyrel (trazodone tablet)',
    'Orenitram tablet; extended release (treprostinil)',
    'Remodulin injection (treprostinil)',
    'Tyvaso inhalation solution (treprostinil)',
    'Retin-A Cream (tretinoin)',
    'Retin-A Gel (tretinoin)',
    'Retin-A Micro (tretinoin)',
    'Renova (tretinoin cream)',
    'Zilretta (triamcinolone acetonide extended release)',
    'Triesence (triamcinolone acetonide injectable suspension)',
    'Triamcinolone cream, 0.1% (triamcinolone cream, 0.1%)',
    'Triamcinolone ointment, 0.1% (triamcinolone ointment, 0.1%)',
    'Dyrenium capsule (triamterene)',
    'Halcion (triazolam)',
    'Syprine capsules (trientine hcl)',
    'Stelazine (now generic only) (trifluoperazine HCl tablet)',
    'Lonsurf (trifluridine and tipiracil)',
    'Viroptic (trifluridine ophthalmic solution)',
    'Dojolvi (triheptanoin liquid; oral)',
    'Artane (trihexyphenidyl)',
    'Trihexane (trihexyphenidyl)',
    'Tritane (trihexyphenidyl)',
    'Mydral (tropicamide)',
    'Mydriacyl (tropicamide)',
    'Ocu-Tropic (tropicamide)',
    'Tropicacyl (tropicamide)',
    'Sanctura (trospium chloride tablet)',
    'Tukysa (tucatinib tablets)',
    'TwoCal (TwoCal HN)',
    'Ofirmiv (tylenol, IV)',
    'Vivotif capsule (typhoid vaccine live oral Ty21a capsule)',
    'Tyrex-1 Powder (Tyrex-1 Powder)',
    'Tyrex-2 Powder (Tyrex-2 Powder)',
    'Ubrelvy (ubrogepant)',
    'Anoro Ellipta (umeclidinium and vilanterol inhalation powder)',
    'Incruse Ellipta (umeclidinium inhalation powder)',
    'Rinvoq (upadacitinib tablet)',
    'Vistogard (uridine triacetate)',
    'Stelara (ustekinumab)',
    'Valtrex tablet (valacyclovir HCL tablet)',
    'Ingrezza (valbenazine)',
    'Valcyte (valganciclovir)',
    'Depakene (valproic acid)',
    'Diovan (valsartan hydrochloride)',
    'Vancocin HCl Pulvules (vancomycin)',
    'Caprelsa (vandetanib)',
    'Chantix (varenicline)',
    'Varivax (Varicella Virus vaccine live)',
    'Varizig (varicella zoster immune globulin (human))',
    'Norcuron (vecuronium)',
    'Entyvio Injection (vedolizumab)',
    'VPRIV Injection (velaglucerase alfa)',
    'Zelboraf (vemurafenib)',
    'Venclexta (venetoclax)',
    'Effexor XR (venlafaxine)',
    'Effexor (venlafaxine tablet)',
    'Calan (verapamil HCl)',
    'Calan-SR (verapamil SR tablet)',
    'Isoptin-SR (verapamil SR tablet)',
    'Isoptin (verapamil)',
    'Verelan (verapamil)',
    'Visudyne (verteporfin for injection)',
    'Mepsevii (vestronidase alfa-vjbk injection)',
    'Lortab (vicodin)',
    'Sabril Powder for Oral Solution (vigabatrin)',
    'Sabril tablet (vigabatrin)',
    'Viibryd tablets (vilazodone)',
    'Marqibo Injectable (vinCRIStine sulfate)',
    'Erivedge (vismodegib)',
    'Vital 1.0 (Vital 1.0)',
    'Vital 1.5 (Vital 1.5)',
    'Vital AF 1.2 cal (Vital AF 1.2 cal)',
    'Vital High Protein (vital high protein)',
    'Vital Peptide 1.5 Cal (vital peptide 1.5 cal)',
    'Vitamin B Complex capsule (OTC) (Vitamin B Complex capsule (OTC))',
    'Vitamin B-6 tablet (OTC) (Vitamin B-6 tablet (OTC))',
    'Vitamin D3 capsule (OTC) (Vitamin D3 capsule (OTC))',
    'Vitamin D3 tablet (OTC) (Vitamin D3 tablet (OTC))',
    'Vivonex Pediatric (vivonex pediatric)',
    'Vivonex Plus (vivonex plus)',
    'Vivonex RTF (vivonex RTF)',
    'Vivonex T.E.N. (vivonex T.E.N.)',
    'Vonvendi (von Willebrand factor complex human)',
    'Vfend (voriconazole)',
    'Zolinza (vorinostat)',
    'Trintellix (vortioxetine)',
    'Coumadin (warfarin )',
    'Jantoven (warfarin sodium)',
    'WINRHO SDF (winrho sdf)',
    'NuShield (wound dressing)',
    'PuraPly AM Wound Dressing (wound matrix)',
    'PuraPly Wound Dressing (wound matrix)',
    'XEN Sterile Injector (XEN sterile injector)',
    'Accolate (zafirlukast)',
    'Sonata (zaleplon)',
    'Relenza (zanamivir for inhalation)',
    'Prialt (ziconotide infusion)',
    'Retrovir (zidovudine)',
    'Zyflo (zileuton)',
    'Galzin (zinc acetate)',
    'Geodon (ziprasidone HCI)',
    'Zaltrap (ziv-afilibercep)',
    'Reclast (zolendronic acid)',
    'Zomig (nasal spray) (zolmitriptan)',
    'Ambien (Zolpidem)',
    'Zonegran (zonisamide)',
    'Zostavax (Zoster vaccine live)',
    'Shingrix (Zoster Vaccine Recombinant, Adjuvanted)',
];

export default getOptionMapping(medications);
