const rawProcedures = {
    '1': 'Operations on the nervous system',
    '1.1': 'Incision and excision of CNS',
    '1.1.1': 'Craniotomy and craniectomy',
    '1.1.2': 'Incision of cerebral meninges',
    '1.1.3': 'Other incision and excision of CNS',
    '1.2': 'Insertion; replacement; or removal of extracranial ventricular shunt',
    '1.3': 'Laminectomy; excision intervertebral disc',
    '1.3.1': 'Excision of intervertebral disc',
    '1.3.2': 'Laminectomy',
    '1.4': 'Diagnostic spinal tap',
    '1.5': 'Insertion of catheter or spinal stimulator and injection into spinal canal',
    '1.6': 'Decompression peripheral nerve',
    '1.6.1': 'Release of carpal tunnel',
    '1.6.2': 'Other lysis of adhesion and decompression of peripheral nerves',
    '1.7': 'Other diagnostic nervous system procedures',
    '1.8': 'Other non-OR or closed therapeutic nervous system procedures',
    '1.9': 'Other OR therapeutic nervous system procedures',
    '2': 'Operations on the endocrine system',
    '2.1': 'Thyroidectomy; partial or complete',
    '2.2': 'Diagnostic endocrine procedures',
    '2.3': 'Other therapeutic endocrine procedures',
    '3': 'Operations on the eye',
    '3.1': 'Corneal transplant',
    '3.2': 'Glaucoma procedures',
    '3.3': 'Lens and cataract procedures',
    '3.3.1': 'Insertion of prosthetic lens',
    '3.3.2': 'Phacoemulsification and aspiration of cataract',
    '3.3.3': 'Other extracapsular extraction of lens',
    '3.3.4': 'Other lens and cataract procedures',
    '3.4': 'Repair of retinal tear; detachment',
    '3.5': 'Destruction of lesion of retina and choroid',
    '3.6': 'Diagnostic procedures on eye',
    '3.7': 'Other therapeutic procedures on eyelids; conjunctiva; cornea',
    '3.8': 'Other intraocular therapeutic procedures',
    '3.9': 'Other extraocular muscle and orbit therapeutic procedures',
    '4': 'Operations on the ear',
    '4.1': 'Tympanoplasty',
    '4.2': 'Myringotomy',
    '4.3': 'Mastoidectomy',
    '4.4': 'Diagnostic procedures on ear',
    '4.5': 'Other therapeutic ear procedures',
    '5': 'Operations on the nose; mouth; and pharynx',
    '5.1': 'Control of epistaxis',
    '5.2': 'Plastic procedures on nose',
    '5.3': 'Dental procedures',
    '5.4': 'Tonsillectomy and/or adenoidectomy',
    '5.4.1': 'Tonsillectomy without adenoidectomy',
    '5.4.2': 'Tonsillectomy with adenoidectomy',
    '5.4.3': 'Adenoidectomy without tonsillectomy',
    '5.4.4': 'Control of hemorrhage after tonsillectomy or adenoidectomy',
    '5.5': 'Diagnostic procedures on nose; mouth and pharynx',
    '5.5.1': 'Diagnostic procedures on nasal sinuses',
    '5.5.2': 'Other diagnostic procedures on nose; mouth and pharynx',
    '5.6': 'Other non-OR therapeutic procedures on nose; mouth and pharynx',
    '5.6.1': 'Non-OR procedures on nasal sinuses',
    '5.6.2': 'Other non-OR procedures on nasal sinuses',
    '5.7': 'Other OR therapeutic procedures on nose; mouth and pharynx',
    '5.7.1': 'OR procedures on nasal sinuses',
    '5.7.2': 'Excision salivary gland',
    '5.7.3': 'Repair cleft lip',
    '5.7.4': 'Correction cleft palate',
    '5.7.5': 'Incision and drainage of tonsils',
    '5.7.6': 'Other procedures on nose; mouth and pharynx',
    '6': 'Operations on the respiratory system',
    '6.1': 'Tracheostomy; temporary and permanent',
    '6.2': 'Tracheoscopy and laryngoscopy with biopsy',
    '6.3': 'Lobectomy or pneumonectomy',
    '6.4': 'Diagnostic bronchoscopy and biopsy of bronchus',
    '6.4.1': 'Bronchoscopy without biopsy',
    '6.4.2': 'Endoscopic biopsy of bronchus',
    '6.4.3': 'Needle biopsy of lung',
    '6.4.4': 'Endoscopic biopsy of lung',
    '6.5': 'Other diagnostic procedures on lung and bronchus',
    '6.6': 'Incision of pleura; thoracentesis; chest drainage',
    '6.6.1': 'Closed chest drainage',
    '6.6.2': 'Open chest drainage',
    '6.6.3': 'Thoracentesis',
    '6.7': 'Other diagnostic procedures of respiratory tract and mediastinum',
    '6.8': 'Other non-OR therapeutic procedures on respiratory system',
    '6.9': 'Other OR therapeutic procedures on respiratory system',
    '7': 'Operations on the cardiovascular system',
    '7.1': 'Heart valve procedures',
    '7.2': 'Coronary artery bypass graft (CABG)',
    '7.2.1': 'Bypass of one coronary artery',
    '7.2.2': 'Bypass of two coronary arteries',
    '7.2.3': 'Bypass of three coronary arteries',
    '7.2.4': 'Bypass of four coronary arteries',
    '7.2.5': 'Other bypass of coronary arteries',
    '7.3': 'Percutaneous transluminal coronary angioplasty (PTCA)',
    '7.3.1': 'Single vessel PTCA',
    '7.3.2': 'Multiple vessel PTCA',
    '7.4': 'Coronary thrombolysis',
    '7.5': 'Diagnostic cardiac catheterization; coronary arteriography',
    '7.5.1': 'Coronary arteriography',
    '7.5.2': 'Cardiac catheterization',
    '7.6': 'Insertion; revision; replacement; removal of cardiac pacemaker or cardioverter/defibr',
    '7.6.1': 'Insertion; revision; replacement; or removal of pacemaker leads',
    '7.6.2': 'Insertion; revision; replacement; or removal of pacemaker device',
    '7.6.3': 'Insertion; revision; replacement; or removal of cardioverter/defibrillator',
    '7.7': 'Other OR heart procedures',
    '7.8': 'Extracorporeal circulation auxiliary to open heart procedures',
    '7.9': 'Endarterectomy; vessel of head and neck',
    '7.10': 'Aortic resection; replacement or anastomosis',
    '7.11': 'Varicose vein stripping; lower limb',
    '7.12': 'Other vascular catheterization; not heart',
    '7.12.1': 'Arterial catheterization',
    '7.12.2': 'Umbilical vein catheterization',
    '7.12.3': 'Venous catheterization',
    '7.13': 'Peripheral vascular bypass',
    '7.14': 'Other vascular bypass and shunt; not heart',
    '7.15': 'Creation; revision and removal of arteriovenous fistula or vessel-to-vessel cannula f',
    '7.16': 'Hemodialysis',
    '7.17': 'Other OR procedures on vessels of head and neck',
    '7.18': 'Embolectomy and endarterectomy of lower limbs',
    '7.19': 'Other OR procedures on vessels other than head and neck',
    '7.19.1': 'Interrupt vena cava',
    '7.19.2': 'Other OR procedures on blood vessels',
    '7.20': 'Other diagnostic cardiovascular procedures',
    '7.21': 'Other non-OR therapeutic cardiovascular procedures',
    '8': 'Operations on the hemic and lymphatic system',
    '8.1': 'Bone marrow transplant',
    '8.2': 'Bone marrow biopsy',
    '8.3': 'Procedures on spleen',
    '8.4': 'Other therapeutic procedures; hemic and lymphatic system',
    '8.4.1': 'Biopsy of lymphatic structure',
    '8.4.2': 'Simple excision of lymphatic structure',
    '8.4.3': 'Regional lymph node excision',
    '8.4.4': 'Radical excision lymph nodes',
    '8.4.5': 'Other hemic and lymphatic procedures',
    '9': 'Operations on the digestive system',
    '9.1': 'Therapeutic procedures on the esophagus',
    '9.1.1': 'Injection or ligation of esophageal varices',
    '9.1.2': 'Esophageal dilatation',
    '9.2': 'Upper gastrointestinal endoscopy; biopsy',
    '9.2.1': 'Esophagoscopy',
    '9.2.2': 'Gastroscopy',
    '9.2.3': 'Esophagogastroduodenoscopy (EGD) without biopsy',
    '9.2.4': 'Esophagogastroduodenoscopy (EGD) with biopsy',
    '9.2.5': 'Endoscopic biopsy small intestine',
    '9.3': 'Gastrostomy; temporary and permanent',
    '9.4': 'Colostomy; temporary and permanent',
    '9.5': 'Ileostomy and other enterostomy',
    '9.6': 'Gastrectomy; partial and total',
    '9.7': 'Small bowel resection',
    '9.8': 'Colonoscopy and biopsy',
    '9.8.1': 'Closed endoscopic biopsy of large intestine',
    '9.8.2': 'Other endoscopy of large intestine',
    '9.9': 'Proctoscopy and anorectal biopsy',
    '9.10': 'Colorectal resection',
    '9.10.1': 'Right hemicolectomy',
    '9.10.2': 'Left hemicolectomy',
    '9.10.3': 'Sigmoidectomy',
    '9.10.4': 'Resection of rectum',
    '9.10.5': 'Other colorectal resections',
    '9.11': 'Local excision of large intestine lesion (not endoscopic)',
    '9.12': 'Appendectomy',
    '9.13': 'Hemorrhoid procedures',
    '9.14': 'Endoscopic retrograde cannulation of pancreas (ERCP)',
    '9.15': 'Biopsy of liver',
    '9.16': 'Cholecystectomy and common duct exploration',
    '9.16.1': 'Open cholecystectomy',
    '9.16.2': 'Laparoscopic cholecystectomy',
    '9.16.3': 'Incision of bile duct',
    '9.17': 'Inguinal and femoral hernia repair',
    '9.17.1': 'Unilateral repair inguinal hernia',
    '9.17.2': 'Bilateral repair inguinal hernia',
    '9.17.3': 'Femoral hernia repair',
    '9.18': 'Other hernia repair',
    '9.18.1': 'Umbilical hernia repair',
    '9.18.2': 'Incisional hernia repair',
    '9.18.3': 'Other abdominal wall hernia repair',
    '9.18.4': 'Other hernia repair',
    '9.19': 'Laparoscopy',
    '9.20': 'Abdominal paracentesis',
    '9.21': 'Exploratory laparotomy',
    '9.22': 'Excision; lysis peritoneal adhesions',
    '9.23': 'Peritoneal dialysis',
    '9.24': 'Other bowel diagnostic procedures',
    '9.25': 'Other non-OR upper GI therapeutic procedures',
    '9.26': 'Other OR upper GI therapeutic procedures',
    '9.27': 'Other non-OR lower GI therapeutic procedures',
    '9.28': 'Other OR lower GI therapeutic procedures',
    '9.28.1': 'Closure of stoma of large intestine',
    '9.28.2': 'Local excision of rectal lesion',
    '9.28.3': 'Incision of perirectal tissue',
    '9.28.4': 'Incision of perianal abscess',
    '9.28.5': 'Incision/excision of anal fistula',
    '9.28.6': 'Other lower GI procedures',
    '9.29': 'Other gastrointestinal diagnostic procedures',
    '9.30': 'Other non-OR gastrointestinal therapeutic procedures',
    '9.31': 'Other OR gastrointestinal therapeutic procedures',
    '9.31.1': 'Radical pancreaticoduodenectomy',
    '9.31.2': 'Incision abdominal wall',
    '9.31.3': 'Excision or destruction of peritoneal tissue',
    '9.31.4': 'Creation of cutaneoperitoneal fistula',
    '9.31.5': 'Other gastrointestinal therapeutic procedures',
    '10': 'Operations on the urinary system',
    '10.1': 'Cystoscopy and other transurethral procedures',
    '10.1.1': 'Endoscopy and endoscopic biopsy of the urinary tract',
    '10.1.2': 'Transurethral excision; drainage; or removal of urinary obstruction',
    '10.1.3': 'Ureteral catheterization',
    '10.2': 'Nephrotomy and nephrostomy',
    '10.3': 'Nephrectomy; partial or complete',
    '10.4': 'Kidney transplant',
    '10.5': 'Genitourinary incontinence procedures',
    '10.6': 'Extracorporeal lithotripsy; urinary',
    '10.7': 'Indwelling catheter',
    '10.8': 'Procedures on the urethra',
    '10.9': 'Other diagnostic procedures of urinary tract',
    '10.10': 'Other non-OR therapeutic procedures of urinary tract',
    '10.11': 'Other OR therapeutic procedures of urinary tract',
    '11': 'Operations on the male genital organs',
    '11.1': 'Transurethral resection of prostate (TURP)',
    '11.2': 'Open prostatectomy',
    '11.3': 'Circumcision',
    '11.4': 'Diagnostic procedures; male genital',
    '11.5': 'Other non-OR therapeutic procedures; male genital',
    '11.6': 'Other OR therapeutic procedures; male genital',
    '11.6.1': 'Unilateral orchiectomy',
    '11.6.2': 'Bilateral orchiectomy',
    '11.6.3': 'Orchiopexy',
    '11.6.4': 'Insert or replace penile prosthesis',
    '11.6.5': 'Other male genital procedures',
    '12': 'Operations on the female genital organs',
    '12.1': 'Oophorectomy; unilateral and bilateral',
    '12.2': 'Other operations on ovary',
    '12.3': 'Ligation of fallopian tubes',
    '12.4': 'Other operations on fallopian tubes',
    '12.5': 'Hysterectomy; abdominal and vaginal',
    '12.5.1': 'Total abdominal hysterectomy',
    '12.5.2': 'Vaginal hysterectomy',
    '12.5.3': 'Other hysterectomy',
    '12.6': 'Other excision of cervix and uterus',
    '12.7': 'Abortion (termination of pregnancy)',
    '12.8': 'Dilatation and curettage (D&C); aspiration after delivery or abortion',
    '12.9': 'Diagnostic dilatation and curettage (D&C)',
    '12.10': 'Repair of cystocele and rectocele; obliteration of vaginal vault',
    '12.11': 'Other diagnostic procedures; female organs',
    '12.12': 'Other non-OR therapeutic procedures; female organs',
    '12.13': 'Other OR therapeutic procedures; female organs',
    '13': 'Obstetrical procedures',
    '13.1': 'Episiotomy',
    '13.2': 'Cesarean section',
    '13.3': 'Forceps; vacuum; and breech delivery',
    '13.3.1': 'Low forceps delivery with episiotomy',
    '13.3.2': 'Vacuum extraction with episiotomy',
    '13.3.3': 'Other vacuum extraction',
    '13.3.4': 'Other forceps or breech delivery',
    '13.4': 'Artificial rupture of membranes to assist delivery',
    '13.4.1': 'Induction of labor by artificial rupture of membranes',
    '13.4.2': 'Other artificial rupture of membranes',
    '13.5': 'Other procedures to assist delivery',
    '13.5.2': 'Medical induction of labor',
    '13.5.3': 'Other manually assisted labor',
    '13.5.4': 'Other delivery procedures',
    '13.6': 'Diagnostic amniocentesis',
    '13.7': 'Fetal monitoring',
    '13.8': 'Repair of current obstetric laceration',
    '13.8.1': 'Repair of obstetric laceration of uterus or cervix',
    '13.8.2': 'Repair of obstetric laceration of bladder or urethra',
    '13.8.3': 'Repair of obstetric laceration of rectum or sphincter',
    '13.8.4': 'Repair of other obstetric laceration',
    '13.9': 'Other therapeutic obstetrical procedures',
    '13.10': 'Removal of ectopic pregnancy',
    '14': 'Operations on the musculoskeletal system',
    '14.1': 'Partial excision bone',
    '14.2': 'Bunionectomy or repair of toe deformities',
    '14.3': 'Treatment of fracture or dislocation',
    '14.3.1': 'Treatment; facial fracture or dislocation',
    '14.3.2': 'Treatment; fracture or dislocation of radius and ulna',
    '14.3.3': 'Treatment; fracture or dislocation of hip and femur',
    '14.3.4': 'Treatment; fracture or dislocation of lower extremity (other than hip or femur)',
    '14.3.5': 'Other fracture and dislocation procedure',
    '14.4': 'Arthroscopy',
    '14.4.1': 'Arthroscopy of knee',
    '14.4.2': 'Other arthroscopy',
    '14.5': 'Division of joint capsule; ligament or cartilage',
    '14.6': 'Excision of semilunar cartilage of knee',
    '14.7': 'Arthroplasty',
    '14.7.1': 'Arthroplasty knee',
    '14.7.2': 'Hip replacement; total and partial',
    '14.7.3': 'Arthroplasty other than hip or knee',
    '14.8': 'Arthrocentesis',
    '14.9': 'Injections and aspirations of muscles; tendons; bursa; joints and soft tissue',
    '14.10': 'Amputation of lower extremity',
    '14.10.1': 'Amputation of toe',
    '14.10.2': 'Amputation through foot',
    '14.10.3': 'Below knee amputation',
    '14.10.4': 'Above knee amputation',
    '14.10.5': 'Other lower extremity amputation',
    '14.11': 'Spinal fusion',
    '14.12': 'Other diagnostic procedures on musculoskeletal system',
    '14.13': 'Other therapeutic procedures on muscles and tendons',
    '14.13.1': 'Rotator cuff repair',
    '14.13.2': 'Other suture of muscle; tendon and fascia',
    '14.13.3': 'Other muscle and tendon procedures',
    '14.14': 'Other OR therapeutic procedures on bone',
    '14.15': 'Other OR therapeutic procedures on joints',
    '14.16': 'Other non-OR therapeutic procedures on musculoskeletal system',
    '14.17': 'Other OR therapeutic procedures on musculoskeletal system',
    '15': 'Operations on the integumentary system',
    '15.1': 'Procedures on the breast',
    '15.1.1': 'Breast biopsy and other diagnostic procedures on breast',
    '15.1.2': 'Lumpectomy; quadrantectomy of breast',
    '15.1.3': 'Mastectomy',
    '15.2': 'Incision and drainage; skin and subcutaneous tissue',
    '15.3': 'Debridement of wound; infection or burn',
    '15.4': 'Excision of skin lesion',
    '15.5': 'Suture of skin and subcutaneous tissue',
    '15.6': 'Skin graft',
    '15.7': 'Other diagnostic procedures on skin and subcutaneous tissue',
    '15.8': 'Other non-OR therapeutic procedures on skin and breast',
    '15.8.1': 'Aspiration of skin and subcutaneous tissue',
    '15.8.2': 'Insertion of totally implantable vascular access device',
    '15.8.3': 'Debridement of nail',
    '15.8.4': 'Other skin and breast procedures; non-OR',
    '15.9': 'Other OR therapeutic procedures on skin and breast',
    '15.9.1': 'Bilateral reduction mammoplasty',
    '15.9.2': 'Excision pilonidal cyst or sinus',
    '15.9.3': 'Other skin and breast procedures; OR',
    '16': 'Miscellaneous diagnostic and therapeutic procedures',
    '16.1': 'Other organ transplantation',
    '16.2': 'Computerized axial tomography (CT) scan',
    '16.2.1': 'Computerized axial tomography (CT) scan head',
    '16.2.2': 'CT scan chest',
    '16.2.3': 'CT scan abdomen',
    '16.2.4': 'Other CT scan',
    '16.3': 'Myelogram',
    '16.4': 'Mammography',
    '16.5': 'Routine chest X-ray',
    '16.6': 'Intraoperative cholangiogram',
    '16.7': 'Upper gastrointestinal X-ray',
    '16.8': 'Lower gastrointestinal X-ray',
    '16.9': 'Intravenous pyelogram',
    '16.10': 'Cerebral arteriogram',
    '16.11': 'Contrast aortogram',
    '16.12': 'Contrast arteriogram of femoral and lower extremity arteries',
    '16.13': 'Arterio or venogram (not heart and head)',
    '16.14': 'Diagnostic ultrasound',
    '16.14.1': 'Diagnostic ultrasound of head and neck',
    '16.14.2': 'Diagnostic ultrasound of heart (echocardiogram)',
    '16.14.3': 'Diagnostic ultrasound of gastrointestinal tract',
    '16.14.4': 'Diagnostic ultrasound of urinary tract',
    '16.14.5': 'Diagnostic ultrasound of abdomen or retroperitoneum',
    '16.14.6': 'Other diagnostic ultrasound',
    '16.15': 'Magnetic resonance imaging',
    '16.16': 'Electroencephalogram (EEG)',
    '16.17': 'Nonoperative urinary system measurements',
    '16.18': 'Cardiac stress tests',
    '16.19': 'Electrocardiogram',
    '16.20': 'Electrographic cardiac monitoring',
    '16.21': 'Swan-Ganz catheterization for monitoring',
    '16.22': 'Arterial blood gases',
    '16.23': 'Microscopic examination (bacterial smear; culture; toxicology)',
    '16.24': 'Radioisotope scan',
    '16.24.1': 'Radioisotope bone scan',
    '16.24.2': 'Radioisotope pulmonary scan',
    '16.24.3': 'Radioisotope scan and function studies',
    '16.24.4': 'Other radioisotope scan',
    '16.25': 'Therapeutic radiology',
    '16.26': 'Physical therapy',
    '16.26.1': 'Diagnostic physical therapy',
    '16.26.2': 'Physical therapy exercises; manipulation; and other procedures',
    '16.26.3': 'Traction; splints; and other wound care',
    '16.26.4': 'Other physical therapy and rehabilitation',
    '16.27': 'Respiratory intubation and mechanical ventilation',
    '16.27.1': 'Endotracheal intubation',
    '16.27.2': 'Continuous mechanical ventilation less than 96 hours',
    '16.27.3': 'Continuous mechanical ventilation 96 hours or more',
    '16.27.4': 'Other respiratory intubation and mechanical ventilation',
    '16.28': 'Other respiratory therapy',
    '16.28.1': 'Respiratory medication administered by nebulizer',
    '16.28.2': 'Oxygen therapy',
    '16.28.3': 'Other respiratory treatments',
    '16.29': 'Psychological and psychiatric evaluation and therapy',
    '16.29.1': 'Psychiatric drug therapy',
    '16.29.2': 'Electroconvulsive therapy',
    '16.29.3': 'Individual psychotherapy',
    '16.29.4': 'Other psychological and psychiatric evaluation and therapy',
    '16.30': 'Alcohol and drug rehabilitation/ detoxification',
    '16.30.1': 'Alcohol rehabilitation',
    '16.30.2': 'Alcohol detoxification',
    '16.30.3': 'Alcohol rehabilitation and detoxification',
    '16.30.4': 'Drug rehabilitation',
    '16.30.5': 'Drug detoxification',
    '16.30.6': 'Drug rehabilitation and detoxification',
    '16.30.7': 'Alcohol and drug rehabilitation',
    '16.30.8': 'Alcohol and drug detoxification',
    '16.30.9': 'Alcohol and drug rehabilitation and detoxification',
    '16.31': 'Ophthalmologic and otologic diagnosis and treatment',
    '16.32': 'Nasogastric tube',
    '16.33': 'Blood transfusion',
    '16.34': 'Enteral and parenteral nutrition',
    '16.35': 'Cancer chemotherapy',
    '16.36': 'Conversion of cardiac rhythm',
    '16.37': 'Other diagnostic radiology and related techniques',
    '16.38': 'Other diagnostic procedures (interview; evaluation; consultation)',
    '16.39': 'Prophylactic vaccinations and inoculations',
    '16.40': 'Nonoperative removal of foreign body',
    '16.41': 'Extracorporeal shock wave lithotripsy; other than urinary',
    '16.42': 'Other therapeutic procedures',
    '16.42.1': 'Inject antibiotic',
    '16.42.2': 'Other phototherapy (newborn)',
    '16.42.3': 'Injection of Thromobolytic Agent (not coronary)',
    '16.42.4': 'Other therapies',   
}

const procedures = [{
    key: '',
    value: '',
    text: '',
}];

for (const p in rawProcedures) {
    procedures.push({
        key: p,
        value: `${p} ${rawProcedures[p]}`,
        text: rawProcedures[p],
    });
}

export default procedures;