const SearchTermsToQuestionnaireMapping = new Map<string[], string>([
    [['stomach', 'ach'], 'Abdominal Pain'],
    [['stomach', 'hurt'], 'Abdominal Pain'],
    [['stomach', 'pain'], 'Abdominal Pain'],
    [['belly', 'ach'], 'Abdominal Pain'],
    [['belly', 'hurt'], 'Abdominal Pain'],
    [['belly', 'pain'], 'Abdominal Pain'],
    [['abdominal', 'pain'], 'Abdominal Pain'],
    [['acne'], 'Acne'],
    [['zit'], 'Acne'],
    [['adhd'], 'ADHD'],
    [['alcohol'], 'Alcohol Use Disorder Screening'],
    [['drinking', 'too', 'much'], 'Alcohol Use Disorder Screening'],
    [['quit', 'drinking'], 'Alcohol Use Disorder Screening'],
    [['allergi'], 'Allergies'],
    [['animal', 'bit'], 'Animal Bite or Scratch'],
    [['dog', 'bit'], 'Animal Bite or Scratch'],
    [['cat', 'bit'], 'Animal Bite or Scratch'],
    [['ankle', 'pain'], 'Ankle Pain'],
    [['ankle', 'sore'], 'Ankle Pain'],
    [['ankle', 'hurt'], 'Ankle Pain'],
    [['ankle', 'injur'], 'Ankle Pain'],
    [['anxiety'], 'Anxiety'],
    [['anxious'], 'Anxiety'],
    [['joint', 'pain'], 'Joint Pain'],
    [['arthritis'], 'Joint Pain'],
    [['joint', 'ach'], 'Joint Pain'],
    [['asthma'], 'Asthma'],
    [['back', 'pain'], 'Back Pain'],
    [['back', 'sore'], 'Back Pain'],
    [['back', 'hurt'], 'Back Pain'],
    [['back', 'ach'], 'Back Pain'],
    [['back', 'injur'], 'Back Pain'],
    [['bipolar'], 'Bipolar Disorder'],
    [['bloat'], 'Bloating'],
    [['chest', 'pain'], 'Chest Pain'],
    [['chest', 'hurt'], 'Chest Pain'],
    [['chest', 'ach'], 'Chest Pain'],
    [['chest', 'pressure'], 'Chest Pain'],
    [['chest', 'tightness'], 'Chest Pain'],
    [['chronic', 'pain'], 'Chronic Pain'],
    [['bleed', ' eas'], 'Coagulopathy'],
    [['bruis', ' eas'], 'Coagulopathy'],
    [['concentrat'], 'Concentration Problems'],
    [['head', 'injury'], 'Concussion/TBI'],
    [['concussion'], 'Concussion/TBI'],
    [['hit', 'head'], 'Concussion/TBI'],
    [['confusion'], 'Confusion'],
    [['congenital', 'heart', 'disease'], 'Congenital Heart Disease'],
    [['eye', 'infection'], 'Conjunctivitis'],
    [['pink', 'eye'], 'Conjunctivitis'],
    [['red', 'eye'], 'Conjunctivitis'],
    [['eye', 'crust'], 'Conjunctivitis'],
    [['eye', 'discharge'], 'Conjunctivitis'],
    [['eye', 'skin'], 'Inflammation of Skin Around the Eye'],
    [['eyelid', 'inflamm'], 'Inflammation of Skin Around the Eye'],
    [['constipat'], 'Constipation'],
    [['hard', 'stool'], 'Constipation'],
    [['copd'], 'COPD'],
    [['emphysema'], 'COPD'],
    [['cough', 'months'], 'Chronic Cough'],
    [['cough', 'weeks'], 'Chronic Cough'],
    [['dementia'], `Dementia/Alzheimer's Disease`],
    [['alzheimer'], `Dementia/Alzheimer's Disease`],
    [['depress'], 'PHQ-9 for Depression'],
    [['diabetes'], 'Diabetes'],
    [['diarrhea'], 'Diarrhea'],
    [['loose', 'stool'], 'Diarrhea'],
    [['diet'], 'Diet'],
    [['lose', 'weight'], 'Diet'],
    [['gain', 'weight'], 'Diet'],
    [['dizz'], 'Dizziness or Vertigo'],
    [['vertigo'], 'Dizziness or Vertigo'],
    [['dry', 'skin'], 'Dry Skin'],
    [['leg', 'swell'], 'Suspected DVT'],
    [['trouble', 'swallow'], 'Difficulty Swallowing'],
    [['difficult', 'swallow'], 'Difficulty Swallowing'],
    [['ear', 'pain'], 'Ear Pain'],
    [['ear', 'ach'], 'Ear Pain'],
    [['ear', 'infection'], 'Ear Pain'],
    [['eczema'], 'Eczema'],
    [['nose', 'bleed'], 'Nosebleeds/Epistaxis'],
    [['nose', 'bled'], 'Nosebleeds/Epistaxis'],
    [['nose', 'blood'], 'Nosebleeds/Epistaxis'],
    [['eye', 'pain'], 'Eye Pain'],
    [['eye', 'hurt'], 'Eye Pain'],
    [['eye', 'ach'], 'Eye Pain'],
    [['fatigue'], 'Fatigue'],
    [['low', 'energy'], 'Fatigue'],
    [['less', 'energy'], 'Fatigue'],
    [['no', 'energy'], 'Fatigue'],
    [['fever'], 'Fever'],
    [['flu', 'shot'], 'Flu Shot'],
    [['flu', 'vacc'], 'Flu Shot'],
    [['heart', 'burn'], 'GERD/Reflux'],
    [['reflux'], 'GERD/Reflux'],
    [['gerd'], 'GERD/Reflux'],
    [['blood', 'stool'], 'GI Bleed'],
    [['blood', 'poo'], 'GI Bleed'],
    [['hair', 'loss'], 'Hair Loss/Alopecia'],
    [['alopecia'], 'Hair Loss/Alopecia'],
    [['bald'], 'Hair Loss/Alopecia'],
    [['hair', 'fall'], 'Hair Loss/Alopecia'],
    [['headache'], 'Headache'],
    [['head', 'ach'], 'Headache'],
    [['head', 'pain'], 'Headache'],
    [['migraine'], 'Headache'],
    [['head', 'hurt'], 'Headache'],
    [['hearing', 'loss'], 'Hearing Loss'],
    [['not', 'hear'], 'Hearing Loss'],
    [[`can't`, 'hear'], 'Hearing Loss'],
    [['cannot', 'hear'], 'Hearing Loss'],
    [['heart', 'failure'], 'Heart failure'],
    [['blood', 'vomit'], 'Hematemesis'],
    [['cough', 'blood'], 'Hemoptysis'],
    [['hives'], 'Hives'],
    [['hormone'], 'Hormone Concerns'],
    [['hormonal'], 'Hormone Concerns'],
    [['cholesterol'], 'Hyperlipidemia'],
    [['blood', 'pressure'], 'Hypertension'],
    [['high', 'thyroid'], 'Hyperthyroidism'],
    [['low', 'thyroid'], 'Hypothyroidism'],
    [['hyperthyroidism'], 'Hyperthyroidism'],
    [['hypothyroidism'], 'Hypothyroidism'],
    [['graves', 'disease'], 'Hyperthyroidism'],
    [['inflammatory', 'bowel'], 'IBD (Ulcerative Colitis/Crohns)'],
    [[' ibd '], 'IBD (Ulcerative Colitis/Crohns)'],
    [['ulcerative', 'colitis'], 'IBD (Ulcerative Colitis/Crohns)'],
    [['crohn'], 'IBD (Ulcerative Colitis/Crohns)'],
    [['insect', 'bite'], 'Insect Bite'],
    [['bug', 'bite'], 'Insect Bite'],
    [['spider', 'bite'], 'Insect Bite'],
    [['mosquito', 'bite'], 'Insect Bite'],
    [['sleep'], 'Insomnia'],
    [['insomnia'], 'Insomnia'],
    [['leg', 'pain'], 'Leg pain'],
    [['leg', 'ach'], 'Leg pain'],
    [['leg', 'hurt'], 'Leg pain'],
    [['leg', 'sore'], 'Leg pain'],
    [['leg', 'injur'], 'Leg Pain'],
    [['low t '], 'Low Testosterone'],
    [['testosterone'], 'Low Testosterone'],
    [['liver'], 'Cirrhosis/liver disease'],
    [['cirrhosis'], 'Cirrhosis/liver disease'],
    [['large', 'lymph', 'node'], 'lymphadenopathy'],
    [['swollen', 'lymph', 'node'], 'Lymphadenopathy'],
    [['big', 'lymph', 'node'], 'Lymphadenopathy'],
    [['memory'], 'Memory Problems/Forgetfulness'],
    [['remember'], 'Memory Problems/Forgetfulness'],
    [['forget'], 'Memory Problems/Forgetfulness'],
    [['multiple', 'sclerosis'], 'Multiple Sclerosis'],
    [['muscle', 'pain'], 'Muscle Pain'],
    [['nail'], 'Nail Changes'],
    [['nausea'], 'Nausea'],
    [['neck', 'pain'], 'Neck Pain'],
    [['neck', 'ach'], 'Neck Pain'],
    [['neck', 'hurt'], 'Neck Pain'],
    [['neck', 'sore'], 'Neck Pain'],
    [['neck', 'injur'], 'Neck Pain'],
    [['pregnan'], 'New Pregnancy/Possible Pregnancy'],
    [['numb'], 'Numbness'],
    [['opiate'], 'Opiate Use'],
    [['osteoporosis'], 'Osteoporosis'],
    [['weak', 'bones'], 'Osteoporosis'],
    [['pacemaker'], 'Pacemaker issue'],
    [['prenatal'], 'Prenatal Care'],
    [['psoriasis'], 'Psoriasis'],
    [['pcos'], 'PCOS (Polycystic Ovary Syndrome)'],
    [['cyst', 'ovar'], 'PCOS (Polycystic Ovary Syndrome)'],
    [['ptsd'], 'Post Traumatic Stress Disorder (PTSD)'],
    [['rash'], 'Rash'],
    [['cold'], 'Upper Respiratory Infection Symptoms'],
    [['sore', 'throat'], 'Upper Respiratory Infection Symptoms'],
    [['runny', 'nose'], 'Upper Respiratory Infection Symptoms'],
    [['sinus', 'infection'], 'Upper Respiratory Infection Symptoms'],
    [['sarcoidosis'], 'Sarcoidosis'],
    [['seborrheic'], 'Seborrheic Dermatitis'],
    [['epilepsy'], 'Epilepsy or Seizure'],
    [['seizure'], 'Epilepsy or Seizure'],
    [['sti'], 'Genital Symptoms/STI'],
    [['std'], 'Genital Symptoms/STI'],
    [['chlamydia'], 'Genital Symptoms/STI'],
    [['gonorrhea'], 'Genital Symptoms/STI'],
    [['trich'], 'Genital Symptoms/STI'],
    [['yeast', 'infection'], 'Genital Symptoms/STI'],
    [['vaginosis'], 'Genital Symptoms/STI'],
    [['vaginal', 'discharge'], 'Changes in Vaginal Discharge'],
    [['short', 'breath'], 'Shortness of Breath'],
    [['out', 'of', 'breath'], 'Shortness of Breath'],
    [['mole'], 'Skin Lesion'],
    [['skin', 'spot'], 'Skin Lesion'],
    [['quit', 'smoking'], 'Smoking/Tobacco Use'],
    [['fainting'], 'Syncope'],
    [['fell', 'out'], 'Syncope'],
    [['lost', 'consciousness'], 'Syncope'],
    [['loss', 'of', 'consciousness'], 'Syncope'],
    [['fainted'], 'Syncope'],
    [['black', 'out'], 'Syncope'],
    [['tingling'], 'Tingling'],
    [['pain', 'urin'], 'Urinary Symptoms/UTI'],
    [['bladder', 'pain'], 'Urinary Symptoms/UTI'],
    [['seeing'], 'Vision Problems'],
    [['hoarse'], 'Hoarseness or Voice Changes'],
    [['voice'], 'Hoarseness or Voice Changes'],
    [['vomit'], 'Vomiting'],
    [['barf'], 'Vomiting'],
    [['throw', 'up'], 'Vomiting'],
    [['weight'], 'Weight Concerns'],
    [['wheez'], 'Wheezing'],
    [['wrist', 'hurt'], 'Wrist Pain'],
    [['wrist', 'ach'], 'Wrist Pain'],
    [['wrist', 'pain'], 'Wrist Pain'],
    [['wrist', 'sore'], 'Wrist Pain'],
    [['shoulder', 'hurt'], 'Shoulder Pain'],
    [['shoulder', 'ach'], 'Shoulder Pain'],
    [['shoulder', 'pain'], 'Shoulder Pain'],
    [['shoulder', 'sore'], 'Shoulder Pain'],
    [['knee', 'hurt'], 'Knee Pain'],
    [['knee', 'ach'], 'Knee Pain'],
    [['knee', 'pain'], 'Knee Pain'],
    [['knee', 'sore'], 'Knee Pain'],
    [['knee', 'injur'], 'Knee Pain'],
    [['painful', 'period'], 'Painful Periods/Menstrual Cramping'],
    [['menstrual', 'cramp'], 'Painful Periods/Menstrual Cramping'],
    [['heavy', 'period'], 'Heavy Periods'],
    [
        ['irregular', 'period'],
        'Irregular Periods/More Frequent Periods/Less Frequent Periods',
    ],
    [['pain', 'intercourse'], 'Painful Intercourse'],
    [['pain', 'sex'], 'Painful Intercourse'],
    [['hot', 'flash'], 'Hot Flashes'],
    [['vagin', 'dry'], 'Vaginal Dryness'],
    [['low', 'libido'], 'Low Libido'],
    [
        ['breast', 'pain'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['breast', 'ach'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['breast', 'hurt'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['breast', 'sore'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['breast', 'lump'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['breast', 'mass'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['nipple', 'leak'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['nipple', 'discharge'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [
        ['nipple', 'fluid'],
        'Breast Concerns (Breast Pain, Breast Lump, and/or Nipple Discharge)',
    ],
    [['birth', 'control'], 'Birth Control Consultation'],
]);

export default SearchTermsToQuestionnaireMapping;
