import { getOptionMapping } from '../_processOptions';

const rawSideEffects = [
    'abdominal pain',
    'agitation',
    'allergic reaction',
    'anemia',
    'anxiety',
    'asthma attack',
    'back pain',
    'behavior changes',
    'bleeding',
    'blindness',
    'blister',
    'bruising',
    'chest pain',
    'confusion',
    'constipation',
    'crying',
    'deafness',
    'delirium',
    'depression',
    'diarrhea',
    'difficulty breathing',
    'difficulty staying asleep',
    'difficulty swallowing',
    'dizziness',
    'drowsiness',
    'dry mouth',
    'excessive sweating',
    'face swelling',
    'faintness',
    'falls',
    'fatigue',
    'fever',
    'gas',
    'hallucinations',
    'headache',
    'heart attack',
    'heart failure',
    'heartburn',
    'high blood pressure',
    'hives',
    'hoarseness',
    'increased appetite',
    'increased heart rate',
    'increased temperature',
    'insomnia',
    'irritability',
    'itching',
    'jaundice',
    'joint pain',
    'joint swelling',
    'kidney problems',
    'lightheadedness',
    'liver problems',
    'loss of appetite',
    'low blood pressure',
    'mania',
    'memory problems',
    'mood changes',
    'muscle injury',
    'muscle pain',
    'muscle soreness',
    'muscle weakness',
    'nausea',
    'nervousness',
    'nose swelling',
    'numbness',
    'pounding heart',
    'psychosis',
    'purple blotches on skin',
    'rash',
    'restlessness',
    'ringing in ears',
    'runny nose',
    'sadness',
    'seizures',
    'sore throat',
    'stomach ache',
    'stroke',
    'stuffy nose',
    'suicidal thoughts',
    'tendon injury',
    'throat swelling',
    'tics',
    'tingling',
    'tongue swelling',
    'twitching',
    'ulcer',
    'vertigo',
    'violent behavior',
    'visual impairment',
    'vomiting',
    'water retention',
    'weakness',
    'weight gain',
    'weight loss',
];

// TODO: remove this once all sideeffect dropdowns migrate to the
// optimized dropdown (if they do... otherwise delete the other one)
export const sideEffects = rawSideEffects.map((se, index) => {
    return { key: index, value: se, text: se };
});

export default getOptionMapping(rawSideEffects);
