const rawSideEffects = [
    'abdominal pain',
    'agitation',
    'allergic reaction',
    'allergy',
    'anemia',
    'anxiety',
    'asthma attack',
    'asthma',
    'back pain',
    'behavior changes',
    'bleeding gums',
    'bleeding',
    'blindness',
    'blister',
    'bloating',
    'blurriness',
    'breast lumps',
    'breast masses',
    'breast pain',
    'bronchitis',
    'bruising',
    'change in appetite',
    'change in coordination',
    'change in hair',
    'change in hearing',
    'change in nails',
    'change in stream',
    'change in teeth',
    'change in vision',
    'change in weight',
    'chest pain',
    'chills',
    'claudication',
    'cold intolerance',
    'colds',
    'confusion',
    'constipation',
    'contacts',
    'contraception',
    'cough',
    'crying',
    'deafness',
    'delirium',
    'depression',
    'diabetes',
    'diarrhea',
    'difficulty breathing',
    'difficulty staying asleep',
    'difficulty swallowing',
    'difficulty walking',
    'discharge',
    'dizziness',
    'double vision',
    'drowsiness',
    'dry mouth',
    'dryness',
    'dysphagia',
    'dyspnea on exertion',
    'dyspnea',
    'earache',
    'easy bleeding',
    'easy bruising',
    'edema',
    'emphysema',
    'excess hair growth',
    'excessive sweating',
    'face swelling',
    'fainting/blackouts',
    'faintness',
    'falls',
    'fatigue',
    'fever',
    'fevers',
    'frequency',
    'gas',
    'glasses',
    'hallucinations',
    'headache',
    'hearing loss',
    'heart attack',
    'heart failure',
    'heartburn',
    'heat intolerance',
    'hematemesis',
    'hematochezia',
    'hematuria',
    'hemorrhoids',
    'hernias',
    'hesitancy',
    'high blood pressure',
    'high bp',
    'hives',
    'hoarseness',
    'hyperthyroidism',
    'hypothyroidism',
    'incontinence',
    'increased appetite',
    'increased heart rate',
    'increased temperature',
    'insomnia',
    'irritability',
    'itching',
    'jaundice',
    'joint pain',
    'joint stiffness',
    'joint swelling',
    'kidney problems',
    'lightheadedness',
    'liver problems',
    'loss of appetite',
    'loss of sensation',
    'low blood pressure',
    'low bp',
    'lumps',
    'mania',
    'melena',
    'memory loss',
    'memory problems',
    'moles',
    'mood changes',
    'murmurs',
    'muscle cramps',
    'muscle injury',
    'muscle pain',
    'muscle soreness',
    'muscle weakness',
    'nausea',
    'nervousness',
    'night sweats',
    'nocturia',
    'nocturnal dyspnea',
    'nose swelling',
    'nosebleed',
    'numbness',
    'orthopnea',
    'osteoarthritis',
    'pain',
    'palpitations',
    'paralysis',
    'period irregularities',
    'pneumonia',
    'polydipsia',
    'polyphagia',
    'polyuria',
    'pounding heart',
    'pregnancy complications',
    'psychosis',
    'purple blotches on skin',
    'rash',
    'rashes',
    'restlessness',
    'rheumatoid arthritis',
    'ringing in ears',
    'runny nose',
    'sadness',
    'seizures',
    'skin color change',
    'sneezing',
    'sore throat',
    'sores',
    'std',
    'stiffness',
    'stomach ache',
    'stones',
    'stroke',
    'stuffiness',
    'stuffy nose',
    'suicidal thoughts',
    'suicide attempts',
    'swelling',
    'tendon injury',
    'testicular mass',
    'testicular/vaginal pain',
    'throat swelling',
    'tics',
    'tingling',
    'tinnitus',
    'tongue swelling',
    'transfusions',
    'tremor',
    'tuberculosis',
    'twitching',
    'ulcer',
    'urgency',
    'urinary tract infection',
    'varicose veins',
    'vertigo',
    'vertigo/dizziness',
    'violent behavior',
    'visual impairment',
    'vomiting',
    'water retention',
    'weakness',
    'weight gain',
    'weight loss',
    'wheezing',
];

export const sideEffects = rawSideEffects.map((se, index) => {
    return { key: index, value: se, text: se }
});