import { getOptionMapping } from '_processOptions';
export const drugNames = [
    { key: 'Benzodiazepine', text: 'Benzodiazepine', value: 'Benzodiazepine' },
    { key: 'Ativan®', text: 'Ativan®', value: 'Ativan®' },
    { key: 'Halcion®', text: 'Halcion®', value: 'Halcion®' },
    { key: 'Klonopin®', text: 'Klonopin®', value: 'Klonopin®' },
    { key: 'Librium®', text: 'Librium®', value: 'Librium®' },
    { key: 'Rohypnol®', text: 'Rohypnol®', value: 'Rohypnol®' },
    { key: 'Valium®', text: 'Valium®', value: 'Valium®' },
    { key: 'Xanax®', text: 'Xanax®', value: 'Xanax®' },
    { key: 'Hallucinogen', text: 'Hallucinogen', value: 'Hallucinogen' },
    { key: 'Ayahuasca', text: 'Ayahuasca', value: 'Ayahuasca' },
    {
        key: 'DMT (N,N-dimethyltryptamine)',
        text: 'DMT (N,N-dimethyltryptamine)',
        value: 'DMT (N,N-dimethyltryptamine)',
    },
    {
        key: 'GHB (gamma-Hydroxybutyric)',
        text: 'GHB (gamma-Hydroxybutyric)',
        value: 'GHB (gamma-Hydroxybutyric)',
    },
    { key: 'Ketamine', text: 'Ketamine', value: 'Ketamine' },
    { key: 'Khat', text: 'Khat', value: 'Khat' },
    { key: 'Kratom', text: 'Kratom', value: 'Kratom' },
    {
        key: 'LSD (D-lysergic acid diethylamide)',
        text: 'LSD (D-lysergic acid diethylamide)',
        value: 'LSD (D-lysergic acid diethylamide)',
    },
    { key: 'Mescaline', text: 'Mescaline', value: 'Mescaline' },
    { key: 'Mushrooms', text: 'Mushrooms', value: 'Mushrooms' },
    {
        key: 'PCP (phencyclidine)',
        text: 'PCP (phencyclidine)',
        value: 'PCP (phencyclidine)',
    },
    { key: 'Peyote', text: 'Peyote', value: 'Peyote' },
    { key: 'Psilocybin', text: 'Psilocybin', value: 'Psilocybin' },
    {
        key: 'Salvia divinorum',
        text: 'Salvia divinorum',
        value: 'Salvia divinorum',
    },
    {
        key: 'Synthetic Cathinones',
        text: 'Synthetic Cathinones',
        value: 'Synthetic Cathinones',
    },
    { key: 'Heroin', text: 'Heroin', value: 'Heroin' },
    { key: 'Cocaine', text: 'Cocaine', value: 'Cocaine' },
    { key: 'Marijuana', text: 'Marijuana', value: 'Marijuana' },
    { key: 'MDMA/Ecstasy', text: 'MDMA/Ecstasy', value: 'MDMA/Ecstasy' },
    {
        key: 'Methamphetamine',
        text: 'Methamphetamine',
        value: 'Methamphetamine',
    },
    {
        key: 'Other illicit drug',
        text: 'Other illicit drug',
        value: 'Other illicit drug',
    },
    { key: 'Amyl Nitrate', text: 'Amyl Nitrate', value: 'Amyl Nitrate' },
    {
        key: 'Isobutyl Nitrate',
        text: 'Isobutyl Nitrate',
        value: 'Isobutyl Nitrate',
    },
    { key: 'Nitrous Oxide', text: 'Nitrous Oxide', value: 'Nitrous Oxide' },
    { key: 'Opioid', text: 'Opioid', value: 'Opioid' },
    { key: 'Buprenorphine', text: 'Buprenorphine', value: 'Buprenorphine' },
    { key: 'Codeine', text: 'Codeine', value: 'Codeine' },
    {
        key: 'Codeine with Promethazine',
        text: 'Codeine with Promethazine',
        value: 'Codeine with Promethazine',
    },
    { key: 'Fentanyl', text: 'Fentanyl', value: 'Fentanyl' },
    { key: 'Hydrocodone', text: 'Hydrocodone', value: 'Hydrocodone' },
    { key: 'Hydromorphone', text: 'Hydromorphone', value: 'Hydromorphone' },
    { key: 'Meperidine', text: 'Meperidine', value: 'Meperidine' },
    { key: 'Methadone', text: 'Methadone', value: 'Methadone' },
    { key: 'Morphine', text: 'Morphine', value: 'Morphine' },
    { key: 'Oxycodone', text: 'Oxycodone', value: 'Oxycodone' },
    { key: 'Oxymorphone', text: 'Oxymorphone', value: 'Oxymorphone' },
    { key: 'Propoxyphene', text: 'Propoxyphene', value: 'Propoxyphene' },
    { key: 'Tramadol', text: 'Tramadol', value: 'Tramadol' },
    {
        key: 'Dimenhydrinate (Dramamine®)',
        text: 'Dimenhydrinate (Dramamine®)',
        value: 'Dimenhydrinate (Dramamine®)',
    },
    {
        key: 'DXM (dextromethorphan)',
        text: 'DXM (dextromethorphan)',
        value: 'DXM (dextromethorphan)',
    },
    {
        key: 'Pseudoephedrine (Sudafed®)',
        text: 'Pseudoephedrine (Sudafed®)',
        value: 'Pseudoephedrine (Sudafed®)',
    },
    { key: 'Ambien®', text: 'Ambien®', value: 'Ambien®' },
    { key: 'Lunesta®', text: 'Lunesta®', value: 'Lunesta®' },
    { key: 'Sonata®', text: 'Sonata®', value: 'Sonata®' },
    { key: 'Amytal®', text: 'Amytal®', value: 'Amytal®' },
    { key: 'Stimulant', text: 'Stimulant', value: 'Stimulant' },
    { key: 'Adderall®', text: 'Adderall®', value: 'Adderall®' },
    { key: 'Dexedrine®', text: 'Dexedrine®', value: 'Dexedrine®' },
    { key: 'Paxil®', text: 'Paxil®', value: 'Paxil®' },
    { key: 'Prozac®', text: 'Prozac®', value: 'Prozac®' },
    { key: 'Zoloft®', text: 'Zoloft®', value: 'Zoloft®' },
    { key: 'phentermine', text: 'phentermine', value: 'phentermine' },
    { key: 'Adipex®', text: 'Adipex®', value: 'Adipex®' },
    { key: 'Concerta®', text: 'Concerta®', value: 'Concerta®' },
    { key: 'Ritalin®', text: 'Ritalin®', value: 'Ritalin®' },
    { key: 'nandrolone', text: 'nandrolone', value: 'nandrolone' },
    { key: 'testosterone', text: 'testosterone', value: 'testosterone' },
    { key: 'Other', text: 'Other', value: 'Other' },
];

export enum DrugName {
    None = '',
    Benzodiazepine = 'Benzodiazepine',
    Ativan = 'Ativan®',
    Halcion = 'Halcion®',
    Klonopin = 'Klonopin®',
    Librium = 'Librium',
    Rohypnol = 'Rohypnol®',
    Valium = 'Valium®',
    Xanax = 'Xanax®',
    Hallucinogen = 'Hallucinogen',
    Ayahuasca = 'Ayahuasca',
    DMT = 'DMT (N,N-dimethyltryptamine)',
    GHB = 'GHB (gamma-Hydroxybutyric)',
    Ketamine = 'Ketamine',
    Khat = 'Khat',
    Kratom = 'Kratom',
    LSD = 'LSD (D-lysergic acid diethylamide)',
    Mescaline = 'Mescaline',
    Mushrooms = 'Mushrooms',
    PCP = 'PCP (phencyclidine)',
    Peyote = 'Peyote',
    Psilocybin = 'Psilocybin',
    SalviaDivinorum = 'Salvia divinorum',
    SyntheticCathinones = 'Synthetic Cathinones',
    Heroin = 'Heroin',
    Cocaine = 'Cocaine',
    Marijuana = 'Marijuana',
    MDMA_Ecstasy = 'MDMA/Ecstasy',
    Methamphetamine = 'Methamphetamine',
    OtherIllicitDrug = 'Other illicit drug',
    AmylNitrate = 'Amyl Nitrate',
    IsobutylNitrate = 'Isobutyl Nitrate',
    NitrousOxide = 'Nitrous Oxide',
    Opioid = 'Opioid',
    Buprenorphine = 'Buprenorphine',
    Codeine = 'Codeine',
    CodeineWithPromethazine = 'Codeine with Promethazine',
    Fentanyl = 'Fentanyl',
    Hydrocodone = 'Hydrocodone',
    Hydromorphone = 'Hydromorphone',
    Meperidine = 'Meperidine',
    Methadone = 'Methadone',
    Morphine = 'Morphine',
    Oxycodone = 'Oxycodone',
    Oxymorphone = 'Oxymorphone',
    Propoxyphene = 'Propoxyphene',
    Tramadol = 'Tramadol',
    Dimenhydrinate__Dramamine = 'Dimenhydrinate (Dramamine®)',
    DXM = 'DXM (dextromethorphan)',
    Pseudoephedrine__Sudafed = 'Pseudoephedrine (Sudafed®)',
    Ambien = 'Ambien®',
    Lunesta = 'Lunesta®',
    Sonata = 'Sonata®',
    Amytal = 'Amytal®',
    Stimulant = 'Stimulant',
    Adderall = 'Adderall®',
    Dexedrine = 'Dexedrine®',
    Paxil = 'Paxil®',
    Prozac = 'Prozac®',
    Zoloft = 'Zoloft®',
    phentermine = 'phentermine',
    Adipex = 'Adipex®',
    Concerta = 'Concerta®',
    Ritalin = 'Ritalin®',
    nandrolone = 'nandrolone',
    testosterone = 'testosterone',
    Other = 'Other',
}

// TODO: Eventually replace options with updated version from
// knowledge graph to avoid this hacky method.
export default getOptionMapping(drugNames.map((option) => option.key));
