const drugNames = [
    {key: 'Benzodiazepine', text: 'Benzodiazepine', value: 'Benzodiazepine'},
    {key: 'Ativan®', text: 'Ativan®', value: 'Ativan®'},
    {key: 'Halcion®', text: 'Halcion®', value: 'Halcion®'},
    {key: 'Klonopin®', text: 'Klonopin®', value: 'Klonopin®'},
    {key: 'Librium®', text: 'Librium®', value: 'Librium®'},
    {key: 'Rohypnol®', text: 'Rohypnol®', value: 'Rohypnol®'},
    {key: 'Valium®', text: 'Valium®', value: 'Valium®'},
    {key: 'Xanax®', text: 'Xanax®', value: 'Xanax®'},
    {key: 'Hallucinogen', text: 'Hallucinogen', value: 'Hallucinogen'},
    {key: 'Ayahuasca', text: 'Ayahuasca', value: 'Ayahuasca'},
    {key: 'DMT (N,N-dimethyltryptamine)', text: 'DMT (N,N-dimethyltryptamine)', value: 'DMT (N,N-dimethyltryptamine)'},
    {key: 'GHB (gamma-Hydroxybutyric)', text: 'GHB (gamma-Hydroxybutyric)', value: 'GHB (gamma-Hydroxybutyric)'},
    {key: 'Ketamine', text: 'Ketamine', value: 'Ketamine'},
    {key: 'Khat', text: 'Khat', value: 'Khat'},
    {key: 'Kratom', text: 'Kratom', value: 'Kratom'},
    {key: 'LSD (D-lysergic acid diethylamide)', text: 'LSD (D-lysergic acid diethylamide)', value: 'LSD (D-lysergic acid diethylamide)'},
    {key: 'Mescaline', text: 'Mescaline', value: 'Mescaline'},
    {key: 'Mushrooms', text: 'Mushrooms', value: 'Mushrooms'},
    {key: 'PCP (phencyclidine)', text: 'PCP (phencyclidine)', value: 'PCP (phencyclidine)'},
    {key: 'Peyote', text: 'Peyote', value: 'Peyote'},
    {key: 'Psilocybin', text: 'Psilocybin', value: 'Psilocybin'},
    {key: 'Salvia divinorum', text: 'Salvia divinorum', value: 'Salvia divinorum'},
    {key: 'Synthetic Cathinones', text: 'Synthetic Cathinones', value: 'Synthetic Cathinones'},
    {key: 'Heroin', text: 'Heroin', value: 'Heroin'},
    {key: 'Cocaine', text: 'Cocaine', value: 'Cocaine'},
    {key: 'Marijuana', text: 'Marijuana', value: 'Marijuana'},
    {key: 'MDMA/Ecstasy', text: 'MDMA/Ecstasy', value: 'MDMA/Ecstasy'},
    {key: 'Methamphetamine', text: 'Methamphetamine', value: 'Methamphetamine'},
    {key: 'Other illicit drug', text: 'Other illicit drug', value: 'Other illicit drug'},
    {key: 'Amyl Nitrate', text: 'Amyl Nitrate', value: 'Amyl Nitrate'},
    {key: 'Isobutyl Nitrate', text: 'Isobutyl Nitrate', value: 'Isobutyl Nitrate'},
    {key: 'Nitrous Oxide', text: 'Nitrous Oxide', value: 'Nitrous Oxide'},
    {key: 'Opioid', text: 'Opioid', value: 'Opioid'},
    {key: 'Buprenorphine', text: 'Buprenorphine', value: 'Buprenorphine'},
    {key: 'Codeine', text: 'Codeine', value: 'Codeine'},
    {key: 'Codeine with Promethazine', text: 'Codeine with Promethazine', value: 'Codeine with Promethazine'},
    {key: 'Fentanyl', text: 'Fentanyl', value: 'Fentanyl'},
    {key: 'Hydrocodone', text: 'Hydrocodone', value: 'Hydrocodone'},
    {key: 'Hydromorphone', text: 'Hydromorphone', value: 'Hydromorphone'},
    {key: 'Meperidine', text: 'Meperidine', value: 'Meperidine'},
    {key: 'Methadone', text: 'Methadone', value: 'Methadone'},
    {key: 'Morphine', text: 'Morphine', value: 'Morphine'},
    {key: 'Oxycodone', text: 'Oxycodone', value: 'Oxycodone'},
    {key: 'Oxymorphone', text: 'Oxymorphone', value: 'Oxymorphone'},
    {key: 'Propoxyphene', text: 'Propoxyphene', value: 'Propoxyphene'},
    {key: 'Tramadol', text: 'Tramadol', value: 'Tramadol'},
    {key: 'Dimenhydrinate (Dramamine®)', text: 'Dimenhydrinate (Dramamine®)', value: 'Dimenhydrinate (Dramamine®)'},
    {key: 'DXM (dextromethorphan)', text: 'DXM (dextromethorphan)', value: 'DXM (dextromethorphan)'},
    {key: 'Pseudoephedrine (Sudafed®)', text: 'Pseudoephedrine (Sudafed®)', value: 'Pseudoephedrine (Sudafed®)'},
    {key: 'Ambien®', text: 'Ambien®', value: 'Ambien®'},
    {key: 'Lunesta®', text: 'Lunesta®', value: 'Lunesta®'},
    {key: 'Sonata®', text: 'Sonata®', value: 'Sonata®'},
    {key: 'Amytal®', text: 'Amytal®', value: 'Amytal®'},
    {key: 'Stimulant', text: 'Stimulant', value: 'Stimulant'},
    {key: 'Adderall®', text: 'Adderall®', value: 'Adderall®'},
    {key: 'Dexedrine®', text: 'Dexedrine®', value: 'Dexedrine®'},
    {key: 'Paxil®', text: 'Paxil®', value: 'Paxil®'},
    {key: 'Prozac®', text: 'Prozac®', value: 'Prozac®'},
    {key: 'Zoloft®', text: 'Zoloft®', value: 'Zoloft®'},
    {key: 'phentermine', text: 'phentermine', value: 'phentermine'},
    {key: 'Adipex®', text: 'Adipex®', value: 'Adipex®'},
    {key: 'Concerta®', text: 'Concerta®', value: 'Concerta®'},
    {key: 'Ritalin®', text: 'Ritalin®', value: 'Ritalin®'},
    {key: 'nandrolone', text: 'nandrolone', value: 'nandrolone'},
    {key: 'testosterone', text: 'testosterone', value: 'testosterone'},
    {key: 'Other', text: 'Other', value: 'Other'}
];

export default drugNames;