name: Lint Check

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0
    - name: Build project
      run: npm ci && npm run build --if-present
      env: 
        CI: false
    - name: Run lint checks
      run: npm run lint
      
