name: Lint Check

on:
    push:
    pull_request:
        branches: [master]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: create env file
              run: |
                touch .env
                echo NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }} >> .env
                echo NEXT_PUBLIC_APP_ENV=${{ env.NEXT_PUBLIC_APP_ENV }} >> .env
                echo NEXT_PUBLIC_COGNITO_CLIENT_ID=${{ env.NEXT_PUBLIC_COGNITO_CLIENT_ID }} >> .env
                echo NEXT_PUBLIC_COGNITO_POOL_ID=${{ env.NEXT_PUBLIC_COGNITO_POOL_ID }} >> .env
                echo NEXT_PUBLIC_GRAPH_URL=${{ env.NEXT_PUBLIC_GRAPH_URL }} >> .env
                echo NEXT_PUBLIC_REGION=${{ env.NEXT_PUBLIC_REGION }} >> .env
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Build project
              run: echo $NPM_AUTH_TOKEN && npm ci && npm run build --if-present
              env:
                  CI: false
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
                  NODE_OPTIONS: '--max_old_space_size=4096'
            - name: Run lint checks
              run: npm run lint
            - name: Run unit tests
              run: npm run test-ci
